%Legendario
legendario('Articuno').
legendario('Zapdos').
legendario('Moltres').
legendario('Mewtwo').
legendario('Raikou').
legendario('Entei').
legendario('Suicune').
legendario('Lugia').
legendario('Ho-Oh').
legendario('Regirock').
legendario('Regice').
legendario('Registeel').
legendario('Latias').
legendario('Latios').
legendario('Kyogre').
legendario('Groudon').
legendario('Rayquaza').
legendario('Uxie').
legendario('Mesprit').
legendario('Azelf').
legendario('Dialga').
legendario('Palkia').
legendario('Giratina').
legendario('Heatran').
legendario('Regigigas').
legendario('Cresselia').
legendario('Cobalion').
legendario('Terrakion').
legendario('Virizion').
legendario('Tornadus').
legendario('Thundurus').
legendario('Landorus').
legendario('Reshiram').
legendario('Zekrom').
legendario('Kyurem').
legendario('Xerneas').
legendario('Yveltal').
legendario('Zygarde').
legendario('Tapu-Koko').
legendario('Tapu-Lele').
legendario('Tapu-Bulu').
legendario('Tapu-Fini').
legendario('Solgaleo').
legendario('Lunala').
legendario('Necrozma').
legendario('Silvally').
legendario('Type:Null').
legendario('Cosmog').
legendario('Cosmoem').

%singular
singular('Mew').
singular('Celebi').
singular('Jirachi').
singular('Deoxys').
singular('Phione').
singular('Manaphy').
singular('Darkrai').
singular('Shaymin').
singular('Arceus').
singular('Victini').
singular('Keldeo').
singular('Meloetta').
singular('Genesect').
singular('Diancie').
singular('Hoopa').
singular('Volcanion').
singular('Magearna').
singular('Marshadow').
singular('Zeraora').
singular('Meltan').
singular('Melmetal').

%ultraente
ultra_ente('Nihilego').
ultra_ente('Buzzwole').
ultra_ente('Pheromosa').
ultra_ente('Xurkitree').
ultra_ente('Celesteela').
ultra_ente('Kartana').
ultra_ente('Guzzlord').
ultra_ente('Poipole').
ultra_ente('Naganadel').
ultra_ente('Stakataka').
ultra_ente('Blacephalon').

%regular
regular('Bulbasaur').
regular('Ivysaur').
regular('Venusaur').
regular('Charmander').
regular('Charmeleon').
regular('Charizard').
regular('Squirtle').
regular('Wartortle').
regular('Blastoise').
regular('Caterpie').
regular('Metapod').
regular('Butterfree').
regular('Weedle').
regular('Kakuna').
regular('Beedrill').
regular('Pidgey').
regular('Pidgeotto').
regular('Pidgeot').
regular('Rattata').
regular('Raticate').
regular('Spearow').
regular('Fearow').
regular('Ekans').
regular('Arbok').
regular('Pikachu').
regular('Raichu').
regular('Sandshrew').
regular('Sandslash').
regular('Nidoran-F').
regular('Nidorina').
regular('Nidoqueen').
regular('Nidoran-M').
regular('Nidorino').
regular('Nidoking').
regular('Clefairy').
regular('Clefable').
regular('Vulpix').
regular('Ninetales').
regular('Jigglypuff').
regular('Wigglytuff').
regular('Zubat').
regular('Golbat').
regular('Oddish').
regular('Gloom').
regular('Vileplume').
regular('Paras').
regular('Parasect').
regular('Venonat').
regular('Venomoth').
regular('Diglett').
regular('Dugtrio').
regular('Meowth').
regular('Persian').
regular('Psyduck').
regular('Golduck').
regular('Mankey').
regular('Primeape').
regular('Growlithe').
regular('Arcanine').
regular('Poliwag').
regular('Poliwhirl').
regular('Poliwrath').
regular('Abra').
regular('Kadabra').
regular('Alakazam').
regular('Machop').
regular('Machoke').
regular('Machamp').
regular('Bellsprout').
regular('Weepinbell').
regular('Victreebel').
regular('Tentacool').
regular('Tentacruel').
regular('Geodude').
regular('Graveler').
regular('Golem').
regular('Ponyta').
regular('Rapidash').
regular('Slowpoke').
regular('Slowbro').
regular('Magnemite').
regular('Magneton').
regular('Farfetchd').
regular('Doduo').
regular('Dodrio').
regular('Seel').
regular('Dewgong').
regular('Grimer').
regular('Muk').
regular('Shellder').
regular('Cloyster').
regular('Gastly').
regular('Haunter').
regular('Gengar').
regular('Onix').
regular('Drowzee').
regular('Hypno').
regular('Krabby').
regular('Kingler').
regular('Voltorb').
regular('Electrode').
regular('Exeggcute').
regular('Exeggutor').
regular('Cubone').
regular('Marowak').
regular('Hitmonlee').
regular('Hitmonchan').
regular('Lickitung').
regular('Koffing').
regular('Weezing').
regular('Rhyhorn').
regular('Rhydon').
regular('Chansey').
regular('Tangela').
regular('Kangaskhan').
regular('Horsea').
regular('Seadra').
regular('Goldeen').
regular('Seaking').
regular('Staryu').
regular('Starmie').
regular('Mr.Mime').
regular('Scyther').
regular('Jynx').
regular('Electabuzz').
regular('Magmar').
regular('Pinsir').
regular('Tauros').
regular('Magikarp').
regular('Gyarados').
regular('Lapras').
regular('Ditto').
regular('Eevee').
regular('Vaporeon').
regular('Jolteon').
regular('Flareon').
regular('Porygon').
regular('Omanyte').
regular('Omastar').
regular('Kabuto').
regular('Kabutops').
regular('Aerodactyl').
regular('Snorlax').
regular('Dratini').
regular('Dragonair').
regular('Dragonite').
regular('Chikorita').
regular('Bayleef').
regular('Meganium').
regular('Cyndaquil').
regular('Quilava').
regular('Typhlosion').
regular('Totodile').
regular('Croconaw').
regular('Feraligatr').
regular('Sentret').
regular('Furret').
regular('Hoothoot').
regular('Noctowl').
regular('Ledyba').
regular('Ledian').
regular('Spinarak').
regular('Ariados').
regular('Crobat').
regular('Chinchou').
regular('Lanturn').
regular('Pichu').
regular('Cleffa').
regular('Igglybuff').
regular('Togepi').
regular('Togetic').
regular('Natu').
regular('Xatu').
regular('Mareep').
regular('Flaaffy').
regular('Ampharos').
regular('Bellossom').
regular('Marill').
regular('Azumarill').
regular('Sudowoodo').
regular('Politoed').
regular('Hoppip').
regular('Skiploom').
regular('Jumpluff').
regular('Aipom').
regular('Sunkern').
regular('Sunflora').
regular('Yanma').
regular('Wooper').
regular('Quagsire').
regular('Espeon').
regular('Umbreon').
regular('Murkrow').
regular('Slowking').
regular('Misdreavus').
regular('Unown').
regular('Wobbuffet').
regular('Girafarig').
regular('Pineco').
regular('Forretress').
regular('Dunsparce').
regular('Gligar').
regular('Steelix').
regular('Snubbull').
regular('Granbull').
regular('Qwilfish').
regular('Scizor').
regular('Shuckle').
regular('Heracross').
regular('Sneasel').
regular('Teddiursa').
regular('Ursaring').
regular('Slugma').
regular('Magcargo').
regular('Swinub').
regular('Piloswine').
regular('Corsola').
regular('Remoraid').
regular('Octillery').
regular('Delibird').
regular('Mantine').
regular('Skarmory').
regular('Houndour').
regular('Houndoom').
regular('Kingdra').
regular('Phanpy').
regular('Donphan').
regular('Porygon2').
regular('Stantler').
regular('Smeargle').
regular('Tyrogue').
regular('Hitmontop').
regular('Smoochum').
regular('Elekid').
regular('Magby').
regular('Miltank').
regular('Blissey').
regular('Larvitar').
regular('Pupitar').
regular('Tyranitar').
regular('Treecko').
regular('Grovyle').
regular('Sceptile').
regular('Torchic').
regular('Combusken').
regular('Blaziken').
regular('Mudkip').
regular('Marshtomp').
regular('Swampert').
regular('Poochyena').
regular('Mightyena').
regular('Zigzagoon').
regular('Linoone').
regular('Wurmple').
regular('Silcoon').
regular('Beautifly').
regular('Cascoon').
regular('Dustox').
regular('Lotad').
regular('Lombre').
regular('Ludicolo').
regular('Seedot').
regular('Nuzleaf').
regular('Shiftry').
regular('Taillow').
regular('Swellow').
regular('Wingull').
regular('Pelipper').
regular('Ralts').
regular('Kirlia').
regular('Gardevoir').
regular('Surskit').
regular('Masquerain').
regular('Shroomish').
regular('Breloom').
regular('Slakoth').
regular('Vigoroth').
regular('Slaking').
regular('Nincada').
regular('Ninjask').
regular('Shedinja').
regular('Whismur').
regular('Loudred').
regular('Exploud').
regular('Makuhita').
regular('Hariyama').
regular('Azurill').
regular('Nosepass').
regular('Skitty').
regular('Delcatty').
regular('Sableye').
regular('Mawile').
regular('Aron').
regular('Lairon').
regular('Aggron').
regular('Meditite').
regular('Medicham').
regular('Electrike').
regular('Manectric').
regular('Plusle').
regular('Minun').
regular('Volbeat').
regular('Illumise').
regular('Roselia').
regular('Gulpin').
regular('Swalot').
regular('Carvanha').
regular('Sharpedo').
regular('Wailmer').
regular('Wailord').
regular('Numel').
regular('Camerupt').
regular('Torkoal').
regular('Spoink').
regular('Grumpig').
regular('Spinda').
regular('Trapinch').
regular('Vibrava').
regular('Flygon').
regular('Cacnea').
regular('Cacturne').
regular('Swablu').
regular('Altaria').
regular('Zangoose').
regular('Seviper').
regular('Lunatone').
regular('Solrock').
regular('Barboach').
regular('Whiscash').
regular('Corphish').
regular('Crawdaunt').
regular('Baltoy').
regular('Claydol').
regular('Lileep').
regular('Cradily').
regular('Anorith').
regular('Armaldo').
regular('Feebas').
regular('Milotic').
regular('Castform').
regular('Kecleon').
regular('Shuppet').
regular('Banette').
regular('Duskull').
regular('Dusclops').
regular('Tropius').
regular('Chimecho').
regular('Absol').
regular('Wynaut').
regular('Snorunt').
regular('Glalie').
regular('Spheal').
regular('Sealeo').
regular('Walrein').
regular('Clamperl').
regular('Huntail').
regular('Gorebyss').
regular('Relicanth').
regular('Luvdisc').
regular('Bagon').
regular('Shelgon').
regular('Salamence').
regular('Beldum').
regular('Metang').
regular('Metagross').
regular('Turtwig').
regular('Grotle').
regular('Torterra').
regular('Chimchar').
regular('Monferno').
regular('Infernape').
regular('Piplup').
regular('Prinplup').
regular('Empoleon').
regular('Starly').
regular('Staravia').
regular('Staraptor').
regular('Bidoof').
regular('Bibarel').
regular('Kricketot').
regular('Kricketune').
regular('Shinx').
regular('Luxio').
regular('Luxray').
regular('Budew').
regular('Roserade').
regular('Cranidos').
regular('Rampardos').
regular('Shieldon').
regular('Bastiodon').
regular('Burmy').
regular('Wormadam').
regular('Mothim').
regular('Combee').
regular('Vespiquen').
regular('Pachirisu').
regular('Buizel').
regular('Floatzel').
regular('Cherubi').
regular('Cherrim').
regular('Shellos').
regular('Gastrodon').
regular('Ambipom').
regular('Drifloon').
regular('Drifblim').
regular('Buneary').
regular('Lopunny').
regular('Mismagius').
regular('Honchkrow').
regular('Glameow').
regular('Purugly').
regular('Chingling').
regular('Stunky').
regular('Skuntank').
regular('Bronzor').
regular('Bronzong').
regular('Bonsly').
regular('Mime-Jr.').
regular('Happiny').
regular('Chatot').
regular('Spiritomb').
regular('Gible').
regular('Gabite').
regular('Garchomp').
regular('Munchlax').
regular('Riolu').
regular('Lucario').
regular('Hippopotas').
regular('Hippowdon').
regular('Skorupi').
regular('Drapion').
regular('Croagunk').
regular('Toxicroak').
regular('Carnivine').
regular('Finneon').
regular('Lumineon').
regular('Mantyke').
regular('Snover').
regular('Abomasnow').
regular('Weavile').
regular('Magnezone').
regular('Lickilicky').
regular('Rhyperior').
regular('Tangrowth').
regular('Electivire').
regular('Magmortar').
regular('Togekiss').
regular('Yanmega').
regular('Leafeon').
regular('Glaceon').
regular('Gliscor').
regular('Mamoswine').
regular('Porygon-Z').
regular('Gallade').
regular('Probopass').
regular('Dusknoir').
regular('Froslass').
regular('Rotom').
regular('Snivy').
regular('Servine').
regular('Serperior').
regular('Tepig').
regular('Pignite').
regular('Emboar').
regular('Oshawott').
regular('Dewott').
regular('Samurott').
regular('Patrat').
regular('Watchog').
regular('Lillipup').
regular('Herdier').
regular('Stoutland').
regular('Purrloin').
regular('Liepard').
regular('Pansage').
regular('Simisage').
regular('Pansear').
regular('Simisear').
regular('Panpour').
regular('Simipour').
regular('Munna').
regular('Musharna').
regular('Pidove').
regular('Tranquill').
regular('Unfezant').
regular('Blitzle').
regular('Zebstrika').
regular('Roggenrola').
regular('Boldore').
regular('Gigalith').
regular('Woobat').
regular('Swoobat').
regular('Drilbur').
regular('Excadrill').
regular('Audino').
regular('Timburr').
regular('Gurdurr').
regular('Conkeldurr').
regular('Tympole').
regular('Palpitoad').
regular('Seismitoad').
regular('Throh').
regular('Sawk').
regular('Sewaddle').
regular('Swadloon').
regular('Leavanny').
regular('Venipede').
regular('Whirlipede').
regular('Scolipede').
regular('Cottonee').
regular('Whimsicott').
regular('Petilil').
regular('Lilligant').
regular('Basculin').
regular('Sandile').
regular('Krokorok').
regular('Krookodile').
regular('Darumaka').
regular('Darmanitan').
regular('Maractus').
regular('Dwebble').
regular('Crustle').
regular('Scraggy').
regular('Scrafty').
regular('Sigilyph').
regular('Yamask').
regular('Cofagrigus').
regular('Tirtouga').
regular('Carracosta').
regular('Archen').
regular('Archeops').
regular('Trubbish').
regular('Garbodor').
regular('Zorua').
regular('Zoroark').
regular('Minccino').
regular('Cinccino').
regular('Gothita').
regular('Gothorita').
regular('Gothitelle').
regular('Solosis').
regular('Duosion').
regular('Reuniclus').
regular('Ducklett').
regular('Swanna').
regular('Vanillite').
regular('Vanillish').
regular('Vanilluxe').
regular('Deerling').
regular('Sawsbuck').
regular('Emolga').
regular('Karrablast').
regular('Escavalier').
regular('Foongus').
regular('Amoonguss').
regular('Frillish').
regular('Jellicent').
regular('Alomomola').
regular('Joltik').
regular('Galvantula').
regular('Ferroseed').
regular('Ferrothorn').
regular('Klink').
regular('Klang').
regular('Klinklang').
regular('Tynamo').
regular('Eelektrik').
regular('Eelektross').
regular('Elgyem').
regular('Beheeyem').
regular('Litwick').
regular('Lampent').
regular('Chandelure').
regular('Axew').
regular('Fraxure').
regular('Haxorus').
regular('Cubchoo').
regular('Beartic').
regular('Cryogonal').
regular('Shelmet').
regular('Accelgor').
regular('Stunfisk').
regular('Mienfoo').
regular('Mienshao').
regular('Druddigon').
regular('Golett').
regular('Golurk').
regular('Pawniard').
regular('Bisharp').
regular('Bouffalant').
regular('Rufflet').
regular('Braviary').
regular('Vullaby').
regular('Mandibuzz').
regular('Heatmor').
regular('Durant').
regular('Deino').
regular('Zweilous').
regular('Hydreigon').
regular('Larvesta').
regular('Volcarona').
regular('Chespin').
regular('Quilladin').
regular('Chesnaught').
regular('Fennekin').
regular('Braixen').
regular('Delphox').
regular('Froakie').
regular('Frogadier').
regular('Greninja').
regular('Bunnelby').
regular('Diggersby').
regular('Fletchling').
regular('Fletchinder').
regular('Talonflame').
regular('Scatterbug').
regular('Spewpa').
regular('Vivillon').
regular('Litleo').
regular('Pyroar').
regular('Flabébé').
regular('Floette').
regular('Florges').
regular('Skiddo').
regular('Gogoat').
regular('Pancham').
regular('Pangoro').
regular('Furfrou').
regular('Espurr').
regular('Meowstic').
regular('Honedge').
regular('Doublade').
regular('Aegislash').
regular('Spritzee').
regular('Aromatisse').
regular('Swirlix').
regular('Slurpuff').
regular('Inkay').
regular('Malamar').
regular('Binacle').
regular('Barbaracle').
regular('Skrelp').
regular('Dragalge').
regular('Clauncher').
regular('Clawitzer').
regular('Helioptile').
regular('Heliolisk').
regular('Tyrunt').
regular('Tyrantrum').
regular('Amaura').
regular('Aurorus').
regular('Sylveon').
regular('Hawlucha').
regular('Dedenne').
regular('Carbink').
regular('Goomy').
regular('Sliggoo').
regular('Goodra').
regular('Klefki').
regular('Phantump').
regular('Trevenant').
regular('Pumpkaboo').
regular('Gourgeist').
regular('Bergmite').
regular('Avalugg').
regular('Noibat').
regular('Noivern').
regular('Rowlet').
regular('Dartrix').
regular('Decidueye').
regular('Litten').
regular('Torracat').
regular('Incineroar').
regular('Popplio').
regular('Brionne').
regular('Primarina').
regular('Pikipek').
regular('Trumbeak').
regular('Toucannon').
regular('Yungoos').
regular('Gumshoos').
regular('Grubbin').
regular('Charjabug').
regular('Vikavolt').
regular('Crabrawler').
regular('Crabominable').
regular('Oricorio').
regular('Cutiefly').
regular('Ribombee').
regular('Rockruff').
regular('Lycanroc').
regular('Wishiwashi').
regular('Mareanie').
regular('Toxapex').
regular('Mudbray').
regular('Mudsdale').
regular('Dewpider').
regular('Araquanid').
regular('Fomantis').
regular('Lurantis').
regular('Morelull').
regular('Shiinotic').
regular('Salandit').
regular('Salazzle').
regular('Stufful').
regular('Bewear').
regular('Bounsweet').
regular('Steenee').
regular('Tsareena').
regular('Comfey').
regular('Oranguru').
regular('Passimian').
regular('Wimpod').
regular('Golisopod').
regular('Sandygast').
regular('Palossand').
regular('Pyukumuku').
regular('Minior').
regular('Komala').
regular('Turtonator').
regular('Togedemaru').
regular('Mimikyu').
regular('Bruxish').
regular('Drampa').
regular('Dhelmise').
regular('Jangmo-o').
regular('Hakamo-o').
regular('Kommo-o').
regular('Missingno').