color('Amarillo','Abra').
color('Amarillo','Aegislash').
color('Amarillo','Alakazam').
color('Amarillo','Ampharos').
color('Amarillo','Bayleef').
color('Amarillo','Beedrill').
color('Amarillo','Bellsprout').
color('Amarillo','Braixen').
color('Amarillo','Bruxish').
color('Amarillo','Chingling').
color('Amarillo','Cosmoem').
color('Amarillo','Cutiefly').
color('Amarillo','Drowzee').
color('Amarillo','Dunsparce').
color('Amarillo','Electabuzz').
color('Amarillo','Electivire').
color('Amarillo','Elekid').
color('Amarillo','Fennekin').
color('Amarillo','Flabébé').
color('Amarillo','Galvantula').
color('Amarillo','Girafarig').
color('Amarillo','Haxorus').
color('Amarillo','Heliolisk').
color('Amarillo','Helioptile').
color('Amarillo','Hypno').
color('Amarillo','Jirachi').
color('Amarillo','Jolteon').
color('Amarillo','Joltik').
color('Amarillo','Kadabra').
color('Amarillo','Kakuna').
color('Amarillo','Lunatone').
color('Amarillo','Makuhita').
color('Amarillo','Mega-Alakazam').
color('Amarillo','Mega-Ampharos').
color('Amarillo','Mega-Beedrill').
color('Amarillo','Mienfoo').
color('Amarillo','Ninetales').
color('Amarillo','Numel').
color('Amarillo','Pichu').
color('Amarillo','Pikachu').
color('Amarillo','Psyduck').
color('Amarillo','Raichu').
color('Amarillo','Raikou').
color('Amarillo','Ribombee').
color('Amarillo','Rotom-Ventilador').
color('Amarillo','Sableye').
color('Amarillo','Sandshrew').
color('Amarillo','Sandslash').
color('Amarillo','Shuckle').
color('Amarillo','Snorunt').%%%%%%%%%%%%%%%%%%%
color('Amarillo','Sunflora').
color('Amarillo','Sunkern').
color('Amarillo','Togepi').
color('Amarillo','Turtonator').
color('Amarillo','Victreebel').
color('Amarillo','Weepinbell').
color('Amarillo','Zapdos').
color('Amarillo','Zeraora').
color('Azul','Altaria').
color('Azul','Amaura').
color('Azul','Armaldo').
color('Azul','Articuno').
color('Azul','Aurorus').
color('Azul','Avalugg').
color('Azul','Azelf').
color('Azul','Azumarill').
color('Azul','Bagon').
color('Azul','Bergmite').
color('Azul','Blastoise').
color('Azul','Boldore').
color('Azul','Braviary').
color('Azul','Brionne').
color('Azul','Bronzong').
color('Azul','Bronzor').
color('Azul','Carnivine').
color('Azul','Carracosta').
color('Azul','Carvanha').
color('Azul','Chinchou').
color('Azul','Clamperl').
color('Azul','Clauncher').
color('Azul','Clawitzer').
color('Azul','Cobalion').
color('Azul','Cresselia').
color('Azul','Croconaw').
color('Azul','Cryogonal').
color('Azul','Cubchoo').
color('Azul','Deino').
color('Azul','Dewott').
color('Azul','Dhelmise').
color('Azul','Dialga').
color('Azul','Donphan').
color('Azul','Dragonair').
color('Azul','Dratini').
color('Azul','Druddigon').
color('Azul','Ducklett').
color('Azul','Eelektrik').
color('Azul','Eelektross').
color('Azul','Elgyem').
color('Azul','Empoleon').
color('Azul','Feraligatr').
color('Azul','Frillish').
color('Azul','Froakie').
color('Azul','Frogadier').
color('Azul','Gabite').
color('Azul','Garchomp').
color('Azul','Gastrodon').
color('Azul','Gible').
color('Azul','Gigalith').
color('Azul','Glaceon').
color('Azul','Gloom').
color('Azul','Golbat').
color('Azul','Golduck').
color('Azul','Golett').
color('Azul','Golurk').
color('Azul','Greninja').
color('Azul','Gyarados').
color('Azul','Hariyama').
color('Azul','Heracross').
color('Azul','Hippopotas').
color('Azul','Hitmontop').
color('Azul','Honchkrow').
color('Azul','Horsea').
color('Azul','Huntail').
color('Azul','Hydreigon').
color('Azul','Inkay').
color('Azul','Ivysaur').
color('Azul','Jellicent').
color('Azul','Jumpluff').
color('Azul','Karrablast').
color('Azul','Kingdra').
color('Azul','Komala').
color('Azul','Kyogre').
color('Azul','Lanturn').
color('Azul','Lapras').
color('Azul','Latios').
color('Azul','Lotad').
color('Azul','Lucario').
color('Azul','Lumineon').
color('Azul','Luxio').
color('Azul','Luxray').
color('Azul','Machamp').
color('Azul','Machoke').
color('Azul','Machop').
color('Azul','Manaphy').
color('Azul','Manectric').
color('Azul','Mantyke').
color('Azul','Mareanie').
color('Azul','Mareep').
color('Azul','Marill').
color('Azul','Marshtomp').
color('Azul','Meditite').
color('Azul','Mega-Blastoise').
color('Azul','Mega-Garchomp').
color('Azul','Mega-Gyarados').
color('Azul','Mega-Heracross').
color('Azul','Mega-Latios').
color('Azul','Mega-Lucario').
color('Azul','Mega-Manectric').
color('Azul','Mega-Metagross').
color('Azul','Mega-Salamence').
color('Azul','Mega-Sharpedo').
color('Azul','Mega-Swampert').
color('Azul','Mesprit').
color('Azul','Mudkip').
color('Azul','Munchlax').
color('Azul','Nidoqueen').
color('Azul','Nidoran♀').
color('Azul','Nidorina').
color('Azul','Ninetales-de-Alola').
color('Azul','Oddish').
color('Azul','Omanyte').
color('Azul','Omastar').
color('Azul','Oshawott').
color('Azul','Palpitoad').
color('Azul','Panpour').
color('Azul','Phanpy').
color('Azul','Phione').
color('Azul','Piplup').
color('Azul','Poliwag').
color('Azul','Poliwhirl').
color('Azul','Poliwrath').
color('Azul','Popplio').
color('Azul','Primarina').
color('Azul','Prinplup').
color('Azul','Probopass').
color('Azul','Quagsire').
color('Azul','Regice').
color('Azul','Remoraid').
color('Azul','Riolu').
color('Azul','Roggenrola').
color('Azul','Rotom-Lavado').
color('Azul','Salamence').
color('Azul','Samurott').
color('Azul','Sandshrew-de-Alola').
color('Azul','Sandslash-de-Alola').
color('Azul','Sawk').
color('Azul','Seadra').
color('Azul','Sealeo').
color('Azul','Seismitoad').
color('Azul','Sharpedo').
color('Azul','Shinx').
color('Azul','Simisear').
color('Azul','Sneasel').
color('Azul','Snorlax').
color('Azul','Spheal').
color('Azul','Squirtle').
color('Azul','Suicune').
color('Azul','Surskit').
color('Azul','Swablu').
color('Azul','Swampert').
color('Azul','Swellow').
color('Azul','Swoobat').
color('Azul','Taillow').
color('Azul','Tangela').
color('Azul','Tangrowth').
color('Azul','Tentacool').
color('Azul','Tentacruel').
color('Azul','Thundurus').
color('Azul','Thundurus-Therian').
color('Azul','Tirtouga').
color('Azul','Totodile').
color('Azul','Toxapex').
color('Azul','Toxicroak').
color('Azul','Tympole').
color('Azul','Uxie').
color('Azul','Vanillish').
color('Azul','Vanilluxe').
color('Azul','Vaporeon').
color('Azul','Venusaur').
color('Azul','Vikavolt').
color('Azul','Vileplume').
color('Azul','Vulpix-de-Alola').
color('Azul','Wailmer').
color('Azul','Wailord').
color('Azul','Walrein').
color('Azul','Wartortle').
color('Azul','Whiscash').
color('Azul','Wobbuffet').
color('Azul','Woobat').
color('Azul','Wooper').
color('Azul','Wynaut').
color('Azul','Zebstrika').
color('Azul','Zubat').
color('Azul','Zweilous').
color('Beige','Baltoy').
color('Beige','Chesnaught').
color('Beige','Cyndaquil').
color('Beige','Foongus').
color('Beige','Keldeo').
color('Beige','Keldeo-Resolete').
color('Beige','Leafeon').
color('Beige','Mankey').
color('Beige','Mega-Mawile').
color('Beige','Mega-Pidgeot').
color('Beige','Meowth').
color('Beige','Milotic').
color('Beige','Mimikyu').
color('Beige','Minun').
color('Beige','Persian').
color('Beige','Plusle').
color('Beige','Ponyta').
color('Beige','Primeape').
color('Beige','Quilava').
color('Beige','Rapidash').
color('Beige','Shroomish').
color('Beige','Slakoth').
color('Beige','Smeargle').
color('Beige','Spinda').
color('Beige','Typhlosion').
color('Beige','Victini').
color('Blanco','Abomasnow').
color('Blanco','Absol').
color('Blanco','Aerodactyl').
color('Blanco','Arceus').
color('Blanco','Beartic').
color('Blanco','Blacephalon').
color('Blanco','Cascoon').
color('Blanco','Chimecho').
color('Blanco','Cottonee').
color('Blanco','Crabominable').
color('Blanco','Dewgong').
color('Blanco','Diancie').
color('Blanco','Drampa').
color('Blanco','Electrode').
color('Blanco','Emolga').
color('Blanco','Exeggcute').
color('Blanco','Floette').
color('Blanco','Forretress').
color('Blanco','Froslass').
color('Blanco','Furfrou').
color('Blanco','Gallade').
color('Blanco','Gardevoir').
color('Blanco','Glalie').
color('Blanco','Goldeen').
color('Blanco','Grubbin').
color('Blanco','Kartana').
color('Blanco','Kirlia').
color('Blanco','Klefki').
color('Blanco','Larvesta').
color('Blanco','Litwick').
color('Blanco','Lugia').
color('Blanco','Magearna').
color('Blanco','Mantine').
color('Blanco','Masquerain').
color('Blanco','Mawile').
color('Blanco','Mega-Abomasnow').
color('Blanco','Mega-Absol').
color('Blanco','Mega-Altaria').
color('Blanco','Mega-Audino').
color('Blanco','Mega-Gallade').
color('Blanco','Mega-Gardevoir').
color('Blanco','Mega-Medicham').
color('Blanco','Mega-Mewtwo-X').
color('Blanco','Mega-Mewtwo-Y').
color('Blanco','Meloetta').
color('Blanco','Meloetta-Pirueta').
color('Blanco','Meowstic').
color('Blanco','Mewtwo').
color('Blanco','Mienshao').
color('Blanco','Minccino').
color('Blanco','Morelull').
color('Blanco','Nihilego').
color('Blanco','Nincada').
color('Blanco','Oranguru').
color('Blanco','Pachirisu').
color('Blanco','Palkia').
color('Blanco','Passimian').
color('Blanco','Pelipper').
color('Blanco','Pheromosa').
color('Blanco','Ralts').
color('Blanco','Regigigas').
color('Blanco','Reshiram').
color('Blanco','Rufflet').
color('Blanco','Seaking').
color('Blanco','Seel').
color('Blanco','Shiinotic').
color('Blanco','Silcoon').
color('Blanco','Silvally').
color('Blanco','Skarmory').
color('Blanco','Snover').
color('Blanco','Solgaleo').
color('Blanco','Spewpa').
color('Blanco','Steenee').
color('Blanco','Swanna').
color('Blanco','Swirlix').
color('Blanco','Sylveon').
color('Blanco','Togedemaru').
color('Blanco','Togekiss').
color('Blanco','Togetic').
color('Blanco','Tsareena').
color('Blanco','Tynamo').
color('Blanco','Vanillite').
color('Blanco','Venomoth').
color('Blanco','Vigoroth').
color('Blanco','Wingull').
color('Blanco','Wishiwashi').
color('Blanco','Zangoose').
color('Cafe','Barbaracle').
color('Cafe','Basculin').
color('Cafe','Beheeyem').
color('Cafe','Bibarel').
color('Cafe','Bidoof').
color('Cafe','Bonsly').
color('Cafe','Bouffalant').
color('Cafe','Buneary').
color('Cafe','Chespin').
color('Cafe','Chimchar').
color('Cafe','Conkeldurr').
color('Cafe','Cubone').
color('Cafe','Dartrix').
color('Cafe','Decidueye').
color('Cafe','Diglett').
color('Cafe','Diglett-de-Alola').
color('Cafe','Dodrio').
color('Cafe','Doduo').
color('Cafe','Doublade').
color('Cafe','Dragalge').
color('Cafe','Drilbur').
color('Cafe','Dugtrio').
color('Cafe','Dugtrio-de-Alola').
color('Cafe','Eevee').
color('Cafe','Entei').
color('Cafe','Excadrill').
color('Cafe','Exeggutor').
color('Cafe','Exeggutor-de-Alola').
color('Cafe','Farfetch’d').
color('Cafe','Fearow').
color('Cafe','Feebas').
color('Cafe','Furret').
color('Cafe','Garbodor').
color('Cafe','Geodude').
color('Cafe','Gogoat').
color('Cafe','Golem').
color('Cafe','Golem-de-Alola').
color('Cafe','Gourgeist').
color('Cafe','Graveler').
color('Cafe','Graveler-de-Alola').
color('Cafe','Gumshoos').
color('Cafe','Gurdurr').
color('Cafe','Heatran').
color('Cafe','Herdier').
color('Cafe','Hippowdon').
color('Cafe','Hitmonchan').
color('Cafe','Hitmonlee').
color('Cafe','Honedge').
color('Cafe','Hoothoot').
color('Cafe','Infernape').
color('Cafe','Kabuto').
color('Cafe','Kabutops').
color('Cafe','Kangaskhan').
color('Cafe','Lillipup').
color('Cafe','Linoone').
color('Cafe','Litleo').
color('Cafe','Lopunny').
color('Cafe','Lycanroc').
color('Cafe','Mamoswine').
color('Cafe','Mandibuzz').
color('Cafe','Marowak').
color('Cafe','Mega-Kangskhan').
color('Cafe','Mega-Lopunny').
color('Cafe','Mega-Pinsir').
color('Cafe','Minior').
color('Cafe','Monferno').
color('Cafe','Mudbray').
color('Cafe','Mudsdale').
color('Cafe','Noctowl').
color('Cafe','Nuzleaf').
color('Cafe','Palossand').
color('Cafe','Patrat').
color('Cafe','Phantump').
color('Cafe','Pidgeot').
color('Cafe','Pidgeotto').
color('Cafe','Pidgey').
color('Cafe','Piloswine').
color('Cafe','Pinsir').
color('Cafe','Pumpkaboo').
color('Cafe','Pyroar').
color('Cafe','Quilladin').
color('Cafe','Raichu-de-Alola').
color('Cafe','Raticate').
color('Cafe','Raticate-de-Alola').
color('Cafe','Rattata-de-Alola').
color('Cafe','Regirock').
color('Cafe','Relicanth').
color('Cafe','Rockruff').
color('Cafe','Rowlet').
color('Cafe','Sandile').
color('Cafe','Sandygast').
color('Cafe','Sawsbuck').
color('Cafe','Seedot').
color('Cafe','Sentret').
color('Cafe','Shedinja').
color('Cafe','Shiftry').
color('Cafe','Skiddo').
color('Cafe','Skorupi').
color('Cafe','Slaking').
color('Cafe','Spearow').
color('Cafe','Stantler').
color('Cafe','Staryu').
color('Cafe','Stoutland').
color('Cafe','Sudowoodo').
color('Cafe','Swinub').
color('Cafe','Tauros').
color('Cafe','Timburr').
color('Cafe','Trevenant').
color('Cafe','Tyrunt').
color('Cafe','Ursaring').
color('Cafe','Vullaby').
color('Cafe','Vulpix').
color('Cafe','Watchog').
color('Cafe','Weedle').
color('Cafe','Whimsicott').
color('Cafe','Yungoos').
color('Cafe','Zigzagoon').
color('Gris','Accelgor').
color('Gris','Aggron').
color('Gris','Amoonguss').
color('Gris','Aron').
color('Gris','Azurill').
color('Gris','Banette').
color('Gris','Barboach').
color('Gris','Beldum').
color('Gris','Bunnelby').
color('Gris','Carbink').
color('Gris','Castform').
color('Gris','Cinccino').
color('Gris','Cranidos').
color('Gris','Diggersby').
color('Gris','Durant').
color('Gris','Dusclops').
color('Gris','Dusknoir').
color('Gris','Duskull').
color('Gris','Escavalier').
color('Gris','Espurr').
color('Gris','Ferroseed').
color('Gris','Ferrothorn').
color('Gris','Geodude-de-Alola').
color('Gris','Giratina').
color('Gris','Glameow').
color('Gris','Golisopod').
color('Gris','Hakamo-o').
color('Gris','Hoopa').
color('Gris','Jangmo-o').
color('Gris','Klang').
color('Gris','Klink').
color('Gris','Klinklang').
color('Gris','Kommo-o').
color('Gris','Kyurem').
color('Gris','Lairon').
color('Gris','Magnemite').
color('Gris','Magneton').
color('Gris','Magnezone').
color('Gris','Mega-Aggron').
color('Gris','Mega-Diancie').
color('Gris','Mega-Glalie').
color('Gris','Mega-Steelix').
color('Gris','Melmetal').%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
color('Gris','Meltan').
color('Gris','Metagross').
color('Gris','Metang').
color('Gris','Musharna').
color('Gris','Onix').
color('Gris','Pancham').
color('Gris','Pangoro').
color('Gris','Pawniard').
color('Gris','Pidove').
color('Gris','Poochyena').
color('Gris','Pupitar').
color('Gris','Purugly').
color('Gris','Registeel').
color('Gris','Rhydon').
color('Gris','Rhyhorn').
color('Gris','Rhyperior').
color('Gris','Scatterbug').
color('Gris','Shelgon').
color('Gris','Spoink').
color('Gris','Steelix').
color('Gris','Terrakion').
color('Gris','Wimpod').
color('Morado','Aipom').
color('Morado','Ambipom').
color('Morado','Arbok').
color('Morado','Butterfree').
color('Morado','Chandelure').
color('Morado','Cherrim').
color('Morado','Cloyster').
color('Morado','Crabrawler').
color('Morado','Croagunk').
color('Morado','Crobat').
color('Morado','Delcatty').
color('Morado','Ditto').
color('Morado','Drapion').
color('Morado','Drifblim').
color('Morado','Drifloon').
color('Morado','Dustox').
color('Morado','Ekans').
color('Morado','Espeon').
color('Morado','Exploud').
color('Morado','Gastly').
color('Morado','Genesect').
color('Morado','Gengar').
color('Morado','Gliscor').
color('Morado','Goodra').
color('Morado','Goomy').
color('Morado','Gothita').
color('Morado','Gothitelle').
color('Morado','Gothorita').
color('Morado','Granbull').
color('Morado','Grimer').
color('Morado','Grumpig').
color('Morado','Haunter').
color('Morado','Illumise').
color('Morado','Jynx').
color('Morado','Koffing').
color('Morado','Kyogre-Primigenio').
color('Morado','Lileep').
color('Morado','Loudred').
color('Morado','Lunala').
color('Morado','Malamar').
color('Morado','Marowak-de-Alola').
color('Morado','Mega-Aerodactyl').
color('Morado','Mega-Gengar').
color('Morado','Mega-Sableye').
color('Morado','Meowth-de-Alola').
color('Morado','Mismagius').
color('Morado','Missingno').
color('Morado','Muk').
color('Morado','Munna').
color('Morado','Naganadel').
color('Morado','Nidoking').
color('Morado','Nidoran♂').
color('Morado','Nidorino').
color('Morado','Noibat').
color('Morado','Noivern').
color('Morado','Persian-de-Alola').
color('Morado','Poipole').
color('Morado','Rattata').
color('Morado','Rotom-Frio').
color('Morado','Scolipede').
color('Morado','Shellder').
color('Morado','Shuppet').
color('Morado','Skitty').
color('Morado','Skrelp').
color('Morado','Skuntank').
color('Morado','Sliggoo').
color('Morado','Starmie').
color('Morado','Stunky').
color('Morado','Swalot').
color('Morado','Tapu-Fini').
color('Morado','Tyrogue').
color('Morado','Venonat').
color('Morado','Weavile').
color('Morado','Weezing').
color('Morado','Whirlipede').
color('Morado','Zoroark').
color('Morado','Zorua').
color('Morao','Purrloin').
color('Naranja','Arcanine').
color('Naranja','Archeops').
color('Naranja','Bastiodon').
color('Naranja','Binacle').
color('Naranja','Buizel').
color('Naranja','Camerupt').
color('Naranja','Charizard').
color('Naranja','Charmander').
color('Naranja','Combee').
color('Naranja','Combusken').
color('Naranja','Corphish').
color('Naranja','Crustle').
color('Naranja','Dedenne').
color('Naranja','Deoxys').
color('Naranja','Dragonite').
color('Naranja','Dwebble').
color('Naranja','Emboar').
color('Naranja','Fletchinder').
color('Naranja','Fletchling').
color('Naranja','Floatzel').
color('Naranja','Growlithe').
color('Naranja','Kingler').
color('Naranja','Krabby').
color('Naranja','Kricketot').
color('Naranja','Landorus').
color('Naranja','Landorus-Therian').
color('Naranja','Ledyba').
color('Naranja','Magikarp').
color('Naranja','Maractus').
color('Naranja','Mega-Charizard-Y').
color('Naranja','Moltres').
color('Naranja','Mothim').
color('Naranja','Paras').
color('Naranja','Parasect').
color('Naranja','Pignite').
color('Naranja','Rotom').
color('Naranja','Rotom-Calor').
color('Naranja','Scraggy').
color('Naranja','Shieldon').
color('Naranja','Solrock').
color('Naranja','Stunfisk').
color('Naranja','Talonflame').
color('Naranja','Tapu-Koko').
color('Naranja','Teddiursa').
color('Naranja','Tepig').
color('Naranja','Torchic').
color('Naranja','Torkoal').
color('Naranja','Torracat').
color('Naranja','Trapinch').
color('Naranja','Vespiquen').
color('Naranja','Volcarona').
color('Naranja','Yanma').
color('Negro','Araquanid').
color('Negro','Beautifly').%%%%%%%%%%%
color('Negro','Bewear').
color('Negro','Blitzle').
color('Negro','Claydol').
color('Negro','Cofagrigus').
color('Negro','Cosmog').
color('Negro','Darkrai').
color('Negro','Guzzlord').
color('Negro','Houndoom').
color('Negro','Houndour').
color('Negro','Lampent').
color('Negro','Litten').
color('Negro','Marshadow').
color('Negro','Mega-Banette').
color('Negro','Mega-Charizard-X').
color('Negro','Mega-Houndoom').
color('Negro','Mightyena').
color('Negro','Misdreavus').
color('Negro','Murkrow').%%%%%%%%%%%%%%%%
color('Negro','Necrozma').
color('Negro','Ninjask').
color('Negro','Pikipek').
color('Negro','Pyukumuku').
color('Negro','Rampardos').
color('Negro','Salandit').
color('Negro','Salazzle').
color('Negro','Scrafty').
color('Negro','Seviper').
color('Negro','Sigilyph').
color('Negro','Stakataka').
color('Negro','Staraptor').
color('Negro','Staravia').
color('Negro','Starly').
color('Negro','Toucannon').
color('Negro','Tranquill').
color('Negro','Trumbeak').
color('Negro','Type:Null').
color('Negro','Umbreon').
color('Negro','Unfezant').
color('Negro','Unown').
color('Negro','Xerneas').
color('Negro','Xurkitree').
color('Negro','Yamask').
color('Negro','Zekrom').
color('Negro','Zygarde').
color('Rojo','Archen').
color('Rojo','Ariados').
color('Rojo','Bisharp').
color('Rojo','Blaziken').
color('Rojo','Buzzwole').
color('Rojo','Charmeleon').
color('Rojo','Crawdaunt').
color('Rojo','Darumaka').
color('Rojo','Delibird').
color('Rojo','Delphox').
color('Rojo','Flareon').
color('Rojo','Groudon').
color('Rojo','Groudon-Primigenio').
color('Rojo','Heatmor').
color('Rojo','Ho-Oh').
color('Rojo','Incineroar').
color('Rojo','Kricketune').
color('Rojo','Krokorok').
color('Rojo','Krookodile').
color('Rojo','Latias').
color('Rojo','Ledian').
color('Rojo','Magby').
color('Rojo','Magcargo').
color('Rojo','Magmar').
color('Rojo','Magmortar').
color('Rojo','Mega-Blaziken').
color('Rojo','Mega-Camerupt').
color('Rojo','Mega-Latias').
color('Rojo','Mega-Scizor').
color('Rojo','Octillery').
color('Rojo','Oricorio').
color('Rojo','Pansear').
color('Rojo','Scizor').
color('Rojo','Simisage').
color('Rojo','Slugma').
color('Rojo','Tapu-Bulu').
color('Rojo','Throh').
color('Rojo','Tyrantrum').
color('Rojo','Venipede').
color('Rojo','Volbeat').
color('Rojo','Volcanion').
color('Rojo','Voltorb').
color('Rojo','Wurmple').
color('Rojo','Yveltal').
color('Rosa','Alomomola').
color('Rosa','Aromatisse').
color('Rosa','Audino').
color('Rosa','Blissey').
color('Rosa','Bounsweet').
color('Rosa','Chansey').
color('Rosa','Cherubi').
color('Rosa','Clefable').
color('Rosa','Clefairy').
color('Rosa','Cleffa').
color('Rosa','Corsola').
color('Rosa','Deerling').
color('Rosa','Flaaffy').
color('Rosa','Fomantis').
color('Rosa','Gligar').
color('Rosa','Gorebyss').
color('Rosa','Happiny').
color('Rosa','Hoppip').
color('Rosa','Igglybuff').
color('Rosa','Jigglypuff').
color('Rosa','Lickilicky').
color('Rosa','Lickitung').
color('Rosa','Lurantis').
color('Rosa','Luvdisc').
color('Rosa','Medicham').
color('Rosa','Mega-Slowbro').
color('Rosa','Mew').
color('Rosa','Miltank').
color('Rosa','Mime-Jr.').
color('Rosa','Mr.Mime').
color('Rosa','Nosepass').
color('Rosa','Politoed').
color('Rosa','Porygon').
color('Rosa','Porygon-Z').
color('Rosa','Porygon2').
color('Rosa','Shellos').
color('Rosa','Shelmet').
color('Rosa','Simipour').
color('Rosa','Slowbro').
color('Rosa','Slowking').
color('Rosa','Slowpoke').
color('Rosa','Slurpuff').
color('Rosa','Smoochum').
color('Rosa','Snubbull').
color('Rosa','Spiritomb').
color('Rosa','Spritzee').
color('Rosa','Stufful').
color('Rosa','Tapu-Lele').
color('Rosa','Vivillon').
color('Rosa','Whismur').
color('Rosa','Wigglytuff').
color('Verde','Anorith').
color('Verde','Axew').
color('Verde','Bellossom').
color('Verde','Breloom').
color('Verde','Budew').
color('Verde','Bulbasaur').
color('Verde','Burmy').
color('Verde','Cacnea').
color('Verde','Cacturne').
color('Verde','Caterpie').
color('Verde','Celebi').
color('Verde','Celesteela').
color('Verde','Charjabug').
color('Verde','Chatot').
color('Verde','Chikorita').
color('Verde','Comfey').
color('Verde','Cradily').
color('Verde','Darmanitan').
color('Verde','Dewpider').
color('Verde','Duosion').
color('Verde','Electrike').
color('Verde','Finneon').
color('Verde','Florges').
color('Verde','Flygon').
color('Verde','Fraxure').
color('Verde','Grimer-de-Alola').
color('Verde','Grotle').
color('Verde','Grovyle').
color('Verde','Gulpin').
color('Verde','Hawlucha').
color('Verde','Kecleon').
color('Verde','Larvitar').
color('Verde','Leavanny').
color('Verde','Liepard').
color('Verde','Lilligant').
color('Verde','Lombre').
color('Verde','Ludicolo').
color('Verde','Mega-Rayquaza').
color('Verde','Mega-Sceptile').
color('Verde','Mega-Tyranitar').
color('Verde','Mega-Venusaur').
color('Verde','Meganium').
color('Verde','Metapod').
color('Verde','Muk-de-Alola').
color('Verde','Natu').
color('Verde','Pansage').
color('Verde','Petilil').
color('Verde','Pineco').%%%%%%%%%%%%
color('Verde','Qwilfish').
color('Verde','Rayquaza').
color('Verde','Reuniclus').
color('Verde','Roselia').
color('Verde','Roserade').
color('Verde','Rotom-Corte').
color('Verde','Sceptile').
color('Verde','Scyther').
color('Verde','Serperior').
color('Verde','Servine').
color('Verde','Sewaddle').
color('Verde','Shaymin').
color('Verde','Skiploom').
color('Verde','Snivy').
color('Verde','Solosis').
color('Verde','Spinarak').
color('Verde','Swadloon').
color('Verde','Tornadus').
color('Verde','Tornadus-Therian').
color('Verde','Torterra').
color('Verde','Treecko').
color('Verde','Tropius').
color('Verde','Trubbish').
color('Verde','Turtwig').
color('Verde','Tyranitar').
color('Verde','Vibrava').
color('Verde','Virizion').
color('Verde','Wormadam').
color('Verde','Xatu').
color('Verde','Yanmega').