evolucion('Primera','Bulbasaur').
evolucion('Segunda','Ivysaur').
evolucion('Tercera','Venusaur').
evolucion('Primera','Charmander').
evolucion('Segunda','Charmeleon').
evolucion('Tercera','Charizard').
evolucion('Primera','Squirtle').
evolucion('Segunda','Wartortle').
evolucion('Tercera','Blastoise').
evolucion('Primera','Caterpie').
evolucion('Segunda','Metapod').
evolucion('Tercera','Butterfree').
evolucion('Primera','Weedle').
evolucion('Segunda','Kakuna').
evolucion('Tercera','Beedrill').
evolucion('Primera','Pidgey').
evolucion('Segunda','Pidgeotto').
evolucion('Tercera','Pidgeot').
evolucion('Primera','Rattata').
evolucion('Segunda','Raticate').
evolucion('Primera','Spearow').
evolucion('Segunda','Fearow').
evolucion('Primera','Ekans').
evolucion('Segunda','Arbok').
evolucion('Segunda','Pikachu').
evolucion('Tercera','Raichu').
evolucion('Primera','Sandshrew').
evolucion('Segunda','Sandslash').
evolucion('Primera','Nidoran♀').
evolucion('Segunda','Nidorina').
evolucion('Tercera','Nidoqueen').
evolucion('Primera','Nidoran♂').
evolucion('Segunda','Nidorino').
evolucion('Tercera','Nidoking').
evolucion('Segunda','Clefairy').
evolucion('Tercera','Clefable').
evolucion('Primera','Vulpix').
evolucion('Segunda','Ninetales').
evolucion('Segunda','Jigglypuff').
evolucion('Tercera','Wigglytuff').
evolucion('Primera','Zubat').
evolucion('Segunda','Golbat').
evolucion('Primera','Oddish').
evolucion('Segunda','Gloom').
evolucion('Tercera','Vileplume').
evolucion('Primera','Paras').
evolucion('Segunda','Parasect').
evolucion('Primera','Venonat').
evolucion('Segunda','Venomoth').
evolucion('Primera','Diglett').
evolucion('Segunda','Dugtrio').
evolucion('Primera','Meowth').
evolucion('Segunda','Persian').
evolucion('Primera','Psyduck').
evolucion('Segunda','Golduck').
evolucion('Primera','Mankey').
evolucion('Segunda','Primeape').
evolucion('Primera','Growlithe').
evolucion('Segunda','Arcanine').
evolucion('Primera','Poliwag').
evolucion('Segunda','Poliwhirl').
evolucion('Tercera','Poliwrath').
evolucion('Primera','Abra').
evolucion('Segunda','Kadabra').
evolucion('Tercera','Alakazam').
evolucion('Primera','Machop').
evolucion('Segunda','Machoke').
evolucion('Tercera','Machamp').
evolucion('Primera','Bellsprout').
evolucion('Segunda','Weepinbell').
evolucion('Tercera','Victreebel').
evolucion('Primera','Tentacool').
evolucion('Segunda','Tentacruel').
evolucion('Primera','Geodude').
evolucion('Segunda','Graveler').
evolucion('Tercera','Golem').
evolucion('Primera','Ponyta').
evolucion('Segunda','Rapidash').
evolucion('Primera','Slowpoke').
evolucion('Segunda','Slowbro').
evolucion('Primera','Magnemite').
evolucion('Segunda','Magneton').
evolucion('Unica','Farfetch’d').
evolucion('Primera','Doduo').
evolucion('Segunda','Dodrio').
evolucion('Primera','Seel').
evolucion('Segunda','Dewgong').
evolucion('Primera','Grimer').
evolucion('Segunda','Muk').
evolucion('Primera','Shellder').
evolucion('Segunda','Cloyster').
evolucion('Primera','Gastly').
evolucion('Segunda','Haunter').
evolucion('Tercera','Gengar').
evolucion('Primera','Onix').
evolucion('Primera','Drowzee').
evolucion('Segunda','Hypno').
evolucion('Primera','Krabby').
evolucion('Segunda','Kingler').
evolucion('Primera','Voltorb').
evolucion('Segunda','Electrode').
evolucion('Primera','Exeggcute').
evolucion('Segunda','Exeggutor').
evolucion('Primera','Cubone').
evolucion('Segunda','Marowak').
evolucion('Segunda','Hitmonlee').
evolucion('Segunda','Hitmonchan').
evolucion('Primera','Lickitung').
evolucion('Primera','Koffing').
evolucion('Segunda','Weezing').
evolucion('Primera','Rhyhorn').
evolucion('Segunda','Rhydon').
evolucion('Segunda','Chansey').
evolucion('Primera','Tangela').
evolucion('Unica','Kangaskhan').
evolucion('Primera','Horsea').
evolucion('Segunda','Seadra').
evolucion('Primera','Goldeen').
evolucion('Segunda','Seaking').
evolucion('Primera','Staryu').
evolucion('Segunda','Starmie').
evolucion('Segunda','Mr.Mime').
evolucion('Primera','Scyther').
evolucion('Segunda','Jynx').
evolucion('Segunda','Electabuzz').
evolucion('Segunda','Magmar').
evolucion('Unica','Pinsir').
evolucion('Unica','Tauros').
evolucion('Primera','Magikarp').
evolucion('Segunda','Gyarados').
evolucion('Unica','Lapras').
evolucion('Unica','Ditto').
evolucion('Primera','Eevee').
evolucion('Segunda','Vaporeon').
evolucion('Segunda','Jolteon').
evolucion('Segunda','Flareon').
evolucion('Primera','Porygon').
evolucion('Primera','Omanyte').
evolucion('Segunda','Omastar').
evolucion('Primera','Kabuto').
evolucion('Segunda','Kabutops').
evolucion('Unica','Aerodactyl').
evolucion('Segunda','Snorlax').
evolucion('Unica','Articuno').
evolucion('Unica','Zapdos').
evolucion('Unica','Moltres').
evolucion('Primera','Dratini').
evolucion('Segunda','Dragonair').
evolucion('Tercera','Dragonite').
evolucion('Unica','Mewtwo').
evolucion('Unica','Mew').

evolucion('Primera','Chikorita').
evolucion('Segunda','Bayleef').
evolucion('Tercera','Meganium').
evolucion('Primera','Cyndaquil').
evolucion('Segunda','Quilava').
evolucion('Tercera','Typhlosion').
evolucion('Primera','Totodile').
evolucion('Segunda','Croconaw').
evolucion('Tercera','Feraligatr').
evolucion('Primera','Sentret').
evolucion('Segunda','Furret').
evolucion('Primera','Hoothoot').
evolucion('Segunda','Noctowl').
evolucion('Primera','Ledyba').
evolucion('Segunda','Ledian').
evolucion('Primera','Spinarak').
evolucion('Segunda','Ariados').
evolucion('Tercera','Crobat').
evolucion('Primera','Chinchou').
evolucion('Segunda','Lanturn').
evolucion('Primera','Pichu').
evolucion('Primera','Cleffa').
evolucion('Primera','Igglybuff').
evolucion('Primera','Togepi').
evolucion('Segunda','Togetic').
evolucion('Primera','Natu').
evolucion('Segunda','Xatu').
evolucion('Primera','Mareep').
evolucion('Segunda','Flaaffy').
evolucion('Tercera','Ampharos').
evolucion('Tercera','Bellossom').
evolucion('Segunda','Marill').
evolucion('Tercera','Azumarill').
evolucion('Segunda','Sudowoodo').
evolucion('Tercera','Politoed').
evolucion('Primera','Hoppip').
evolucion('Segunda','Skiploom').
evolucion('Tercera','Jumpluff').
evolucion('Primera','Aipom').
evolucion('Primera','Sunkern').
evolucion('Segunda','Sunflora').
evolucion('Primera','Yanma').
evolucion('Primera','Wooper').
evolucion('Segunda','Quagsire').
evolucion('Segunda','Espeon').
evolucion('Segunda','Umbreon').
evolucion('Primera','Murkrow').
evolucion('Segunda','Slowking').
evolucion('Primera','Misdreavus').
evolucion('Unica','Unown').
evolucion('Segunda','Wobbuffet').
evolucion('Unica','Girafarig').
evolucion('Primera','Pineco').
evolucion('Segunda','Forretress').
evolucion('Unica','Dunsparce').
evolucion('Primera','Gligar').
evolucion('Segunda','Steelix').
evolucion('Primera','Snubbull').
evolucion('Segunda','Granbull').
evolucion('Unica','Qwilfish').
evolucion('Segunda','Scizor').
evolucion('Unica','Shuckle').
evolucion('Unica','Heracross').
evolucion('Primera','Sneasel').
evolucion('Primera','Teddiursa').
evolucion('Segunda','Ursaring').
evolucion('Primera','Slugma').
evolucion('Segunda','Magcargo').
evolucion('Primera','Swinub').
evolucion('Segunda','Piloswine').
evolucion('Unica','Corsola').
evolucion('Primera','Remoraid').
evolucion('Segunda','Octillery').
evolucion('Unica','Delibird').
evolucion('Segunda','Mantine').
evolucion('Unica','Skarmory').
evolucion('Primera','Houndour').
evolucion('Segunda','Houndoom').
evolucion('Tercera','Kingdra').
evolucion('Primera','Phanpy').
evolucion('Segunda','Donphan').
evolucion('Segunda','Porygon2').
evolucion('Unica','Stantler').
evolucion('Unica','Smeargle').
evolucion('Primera','Tyrogue').
evolucion('Segunda','Hitmontop').
evolucion('Primera','Smoochum').
evolucion('Primera','Elekid').
evolucion('Primera','Magby').
evolucion('Unica','Miltank').
evolucion('Tercera','Blissey').
evolucion('Unica','Raikou').
evolucion('Unica','Entei').
evolucion('Unica','Suicune').
evolucion('Primera','Larvitar').
evolucion('Segunda','Pupitar').
evolucion('Tercera','Tyranitar').
evolucion('Unica','Lugia').
evolucion('Unica','Ho-Oh').
evolucion('Unica','Celebi').

evolucion('Primera','Treecko').
evolucion('Segunda','Grovyle').
evolucion('Tercera','Sceptile').
evolucion('Primera','Torchic').
evolucion('Segunda','Combusken').
evolucion('Tercera','Blaziken').
evolucion('Primera','Mudkip').
evolucion('Segunda','Marshtomp').
evolucion('Tercera','Swampert').
evolucion('Primera','Poochyena').
evolucion('Segunda','Mightyena').
evolucion('Primera','Zigzagoon').
evolucion('Segunda','Linoone').
evolucion('Primera','Wurmple').
evolucion('Segunda','Silcoon').
evolucion('Tercera','Beautifly').
evolucion('Segunda','Cascoon').
evolucion('Tercera','Dustox').
evolucion('Primera','Lotad').
evolucion('Segunda','Lombre').
evolucion('Tercera','Ludicolo').
evolucion('Primera','Seedot').
evolucion('Segunda','Nuzleaf').
evolucion('Tercera','Shiftry').
evolucion('Primera','Taillow').
evolucion('Segunda','Swellow').
evolucion('Primera','Wingull').
evolucion('Segunda','Pelipper').
evolucion('Primera','Ralts').
evolucion('Segunda','Kirlia').
evolucion('Tercera','Gardevoir').
evolucion('Primera','Surskit').
evolucion('Segunda','Masquerain').
evolucion('Primera','Shroomish').
evolucion('Segunda','Breloom').
evolucion('Primera','Slakoth').
evolucion('Segunda','Vigoroth').
evolucion('Tercera','Slaking').
evolucion('Primera','Nincada').
evolucion('Segunda','Ninjask').
evolucion('Segunda','Shedinja').
evolucion('Primera','Whismur').
evolucion('Segunda','Loudred').
evolucion('Tercera','Exploud').
evolucion('Primera','Makuhita').
evolucion('Segunda','Hariyama').
evolucion('Primera','Azurill').
evolucion('Primera','Nosepass').
evolucion('Primera','Skitty').
evolucion('Segunda','Delcatty').
evolucion('Unica','Sableye').
evolucion('Unica','Mawile').
evolucion('Primera','Aron').
evolucion('Segunda','Lairon').
evolucion('Tercera','Aggron').
evolucion('Primera','Meditite').
evolucion('Segunda','Medicham').
evolucion('Primera','Electrike').
evolucion('Segunda','Manectric').
evolucion('Unica','Plusle').
evolucion('Unica','Minun').
evolucion('Unica','Volbeat').
evolucion('Unica','Illumise').
evolucion('Segunda','Roselia').
evolucion('Primera','Gulpin').
evolucion('Segunda','Swalot').
evolucion('Primera','Carvanha').
evolucion('Segunda','Sharpedo').
evolucion('Primera','Wailmer').
evolucion('Segunda','Wailord').
evolucion('Primera','Numel').
evolucion('Segunda','Camerupt').
evolucion('Unica','Torkoal').
evolucion('Primera','Spoink').
evolucion('Segunda','Grumpig').
evolucion('Unica','Spinda').
evolucion('Primera','Trapinch').
evolucion('Segunda','Vibrava').
evolucion('Tercera','Flygon').
evolucion('Primera','Cacnea').
evolucion('Segunda','Cacturne').
evolucion('Primera','Swablu').
evolucion('Segunda','Altaria').
evolucion('Unica','Zangoose').
evolucion('Unica','Seviper').
evolucion('Unica','Lunatone').
evolucion('Unica','Solrock').
evolucion('Primera','Barboach').
evolucion('Segunda','Whiscash').
evolucion('Primera','Corphish').
evolucion('Segunda','Crawdaunt').
evolucion('Primera','Baltoy').
evolucion('Segunda','Claydol').
evolucion('Primera','Lileep').
evolucion('Segunda','Cradily').
evolucion('Primera','Anorith').
evolucion('Segunda','Armaldo').
evolucion('Primera','Feebas').
evolucion('Segunda','Milotic').
evolucion('Unica','Castform').
evolucion('Unica','Kecleon').
evolucion('Primera','Shuppet').
evolucion('Segunda','Banette').
evolucion('Primer','Duskull').
evolucion('Segunda','Dusclops').
evolucion('Unica','Tropius').
evolucion('Segunda','Chimecho').
evolucion('Unica','Absol').
evolucion('Primera','Wynaut').
evolucion('Primera','Snorunt').
evolucion('Segunda','Glalie').
evolucion('Primera','Spheal').
evolucion('Segunda','Sealeo').
evolucion('Tercera','Walrein').
evolucion('Primera','Clamperl').
evolucion('Segunda','Huntail').
evolucion('Segunda','Gorebyss').
evolucion('Unica','Relicanth').
evolucion('Unica','Luvdisc').
evolucion('Primera','Bagon').
evolucion('Segunda','Shelgon').
evolucion('Tercera','Salamence').
evolucion('Primera','Beldum').
evolucion('Segunda','Metang').
evolucion('Tercera','Metagross').
evolucion('Unica','Regirock').
evolucion('Unica','Regice').
evolucion('Unica','Registeel').
evolucion('Unica','Latias').
evolucion('Unica','Latios').
evolucion('Unica','Kyogre').
evolucion('Unica','Groudon').
evolucion('Unica','Rayquaza').
evolucion('Unica','Jirachi').
evolucion('Unica','Deoxys').

evolucion('Primera','Turtwig').
evolucion('Segunda','Grotle').
evolucion('Tercera','Torterra').
evolucion('Primera','Chimchar').
evolucion('Segunda','Monferno').
evolucion('Tercera','Infernape').
evolucion('Primera','Piplup').
evolucion('Segunda','Prinplup').
evolucion('Tercera','Empoleon').
evolucion('Primera','Starly').
evolucion('Segunda','Staravia').
evolucion('Tercera','Staraptor').
evolucion('Primera','Bidoof').
evolucion('Segunda','Bibarel').
evolucion('Primera','Kricketot').
evolucion('Segunda','Kricketune').
evolucion('Primera','Shinx').
evolucion('Segunda','Luxio').
evolucion('Tercera','Luxray').
evolucion('Primera','Budew').
evolucion('Tercera','Roserade').
evolucion('Primera','Cranidos').
evolucion('Segunda','Rampardos').
evolucion('Primera','Shieldon').
evolucion('Segunda','Bastiodon').
evolucion('Primera','Burmy').
evolucion('Segunda','Wormadam').
evolucion('Segunda','Mothim').
evolucion('Primera','Combee').
evolucion('Segunda','Vespiquen').
evolucion('Unica','Pachirisu').
evolucion('Primera','Buizel').
evolucion('Segunda','Floatzel').
evolucion('Primera','Cherubi').
evolucion('Segunda','Cherrim').
evolucion('Primera','Shellos').
evolucion('Segunda','Gastrodon').
evolucion('Segunda','Ambipom').
evolucion('Primera','Drifloon').
evolucion('Segunda','Drifblim').
evolucion('Primera','Buneary').
evolucion('Segunda','Lopunny').
evolucion('Segunda','Mismagius').
evolucion('Segunda','Honchkrow').
evolucion('Primera','Glameow').
evolucion('Segunda','Purugly').
evolucion('Primera','Chingling').
evolucion('Primera','Stunky').
evolucion('Segunda','Skuntank').
evolucion('Primera','Bronzor').
evolucion('Segunda','Bronzong').
evolucion('Primera','Bonsly').
evolucion('Primera','Mime.Jr').
evolucion('Primera','Happiny').
evolucion('Unica','Chatot').
evolucion('Unica','Spiritomb').
evolucion('Primera','Gible').
evolucion('Segunda','Gabite').
evolucion('Tercera','Garchomp').
evolucion('Primera','Munchlax').
evolucion('Primera','Riolu').
evolucion('Segunda','Lucario').
evolucion('Primera','Hippopotas').
evolucion('Segunda','Hippowdon').
evolucion('Primera','Skorupi').
evolucion('Segunda','Drapion').
evolucion('Primera','Croconaw').
evolucion('Segunda','Toxicroak').
evolucion('Unica','Carnivine').
evolucion('Primera','Finneon').
evolucion('Segunda','Lumineon').
evolucion('Primera','Mantyke').
evolucion('Primera','Snover').
evolucion('Segunda','Abomasnow').
evolucion('Segunda','Weavile').
evolucion('Tercera','Magnezone').
evolucion('Tercera','Lickilicky').
evolucion('Tercera','Rhyperior').
evolucion('Tercera','Tangrowth').
evolucion('Tercera','Electivire').
evolucion('Tercera','Magmortar').
evolucion('Tercera','Togekiss').
evolucion('Tercera','Yanmega').
evolucion('Segunda','Leafeon').
evolucion('Segunda','Glaceon').
evolucion('Segunda','Gliscor').
evolucion('Tercera','Mamoswine').
evolucion('Tercera','Porygon-Z').
evolucion('Tercera','Gallade').
evolucion('Segunda','Probopass').
evolucion('Tercera','Dusknoir').
evolucion('Segunda','Froslass').
evolucion('Unica','Rotom').
evolucion('Unica','Uxie').
evolucion('Unica','Mesprit').
evolucion('Unica','Azelf').
evolucion('Unica','Dialga').
evolucion('Unica','Palkia').
evolucion('Unica','Heatran').
evolucion('Unica','Regigigas').
evolucion('Unica','Giratina').
evolucion('Unica','Cresselia').
evolucion('Unica','Phione').
evolucion('Unica','Manaphy').
evolucion('Unica','Darkrai').
evolucion('Unica','Shaymin').
evolucion('Unica','Arceus').

evolucion('Unica','Victini').
evolucion('Primera','Snivy').
evolucion('Segunda','Servine').
evolucion('Tercera','Serperior').
evolucion('Primera','Tepig').
evolucion('Segunda','Pignite').
evolucion('Tercera','Emboar').
evolucion('Primera','Oshawott').
evolucion('Segunda','Dewott').
evolucion('Tercera','Samurott').
evolucion('Primera','Patrat').
evolucion('Segunda','Watchog').
evolucion('Primera','Lillipup').
evolucion('Segunda','Herdier').
evolucion('Tercera','Stoutland').
evolucion('Primera','Purrloin').
evolucion('Segunda','Liepard').
evolucion('Primera','Pansage').
evolucion('Segunda','Simisage').
evolucion('Primera','Pansear').
evolucion('Segunda','Simisear').
evolucion('Primera','Panpour').
evolucion('Segunda','Simipour').
evolucion('Primera','Munna').
evolucion('Segunda','Musharna').
evolucion('Primera','Pidove').
evolucion('Segunda','Tranquill').
evolucion('Tercera','Unfezant').
evolucion('Primera','Blitzle').
evolucion('Segunda','Zebstrika').
evolucion('Primera','Roggenrola').
evolucion('Segunda','Boldore').
evolucion('Tercera','Gigalith').
evolucion('Primera','Woobat').
evolucion('Segunda','Swoobat').
evolucion('Primera','Drilbur').
evolucion('Segunda','Excadrill').
evolucion('Unica','Audino').
evolucion('Primera','Timburr').
evolucion('Segunda','Gurdurr').
evolucion('Tercera','Conkeldurr').
evolucion('Primera','Tympole').
evolucion('Segunda','Palpitoad').
evolucion('Tercera','Seismitoad').
evolucion('Unica','Throh').
evolucion('Unica','Sawk').
evolucion('Primera','Sewaddle').
evolucion('Segunda','Swadloon').
evolucion('Tercera','Leavanny').
evolucion('Primera','Venipede').
evolucion('Segunda','Whirlipede').
evolucion('Tercera','Scolipede').
evolucion('Primera','Cottonee').
evolucion('Segunda','Whimsicott').
evolucion('Primera','Petilil').
evolucion('Segunda','Lilligant').
evolucion('Unica','Basculin').
evolucion('Primera','Sandile').
evolucion('Segunda','Krokorok').
evolucion('Tercera','Krookodile').
evolucion('Primera','Darumaka').
evolucion('Segunda','Darmanitan').
evolucion('Unica','Maractus').
evolucion('Primera','Dwebble').
evolucion('Segunda','Crustle').
evolucion('Primera','Scraggy').
evolucion('Segunda','Scrafty').
evolucion('Unica','Sigilyph').
evolucion('Primera','Yamask').
evolucion('Segunda','Cofagrigus').
evolucion('Primera','Tirtouga').
evolucion('Segunda','Carracosta').
evolucion('Primera','Archen').
evolucion('Segunda','Archeops').
evolucion('Primera','Trubbish').
evolucion('Segunda','Garbodor').
evolucion('Primera','Zorua').
evolucion('Segunda','Zoroark').
evolucion('Primera','Minccino').
evolucion('Segunda','Cinccino').
evolucion('Primera','Gothita').
evolucion('Segunda','Gothorita').
evolucion('Tercera','Gothitelle').
evolucion('Primera','Solosis').
evolucion('Segunda','Duosion').
evolucion('Tercera','Reuniclus').
evolucion('Primera','Ducklett').
evolucion('Segunda','Swanna').
evolucion('Primera','Vanillite').
evolucion('Segunda','Vanillish').
evolucion('Tercera','Vanilluxe').
evolucion('Primera','Deerling').
evolucion('Segunda','Sawsbuck').
evolucion('Unica','Emolga').
evolucion('Primera','Karrablast').
evolucion('Segunda','Escavalier').
evolucion('Primera','Foongus').
evolucion('Segunda','Amoonguss').
evolucion('Primera','Frillish').
evolucion('Segunda','Jellicent').
evolucion('Unica','Alomomola').
evolucion('Primera','Joltik').
evolucion('Segunda','Galvantula').
evolucion('Primera','Ferroseed').
evolucion('Segunda','Ferrothorn').
evolucion('Primera','Klink').
evolucion('Segunda','Klang').
evolucion('Tercera','Klinklang').
evolucion('Primera','Tynamo').
evolucion('Segunda','Eelektrik').
evolucion('Tercera','Eelektross').
evolucion('Primera','Elgyem').
evolucion('Segunda','Beheeyem').
evolucion('Primera','Litwick').
evolucion('Segunda','Lampent').
evolucion('Tercera','Chandelure').
evolucion('Primera','Axew').
evolucion('Segunda','Fraxure').
evolucion('Tercera','Haxorus').
evolucion('Primera','Cubchoo').
evolucion('Segunda','Beartic').
evolucion('Unica','Cryogonal').
evolucion('Primera','Shelmet').
evolucion('Segunda','Accelgor').
evolucion('Unica','Stunfisk').
evolucion('Primera','Mienfoo').
evolucion('Segunda','Mienshao').
evolucion('Unica','Druddigon').
evolucion('Primera','Golett').
evolucion('Segunda','Golurk').
evolucion('Primera','Pawniard').
evolucion('Segunda','Bisharp').
evolucion('Unica','Bouffalant').
evolucion('Primera','Rufflet').
evolucion('Segunda','Braviary').
evolucion('Primera','Vullaby').
evolucion('Segunda','Mandibuzz').
evolucion('Unica','Heatmor').
evolucion('Unica','Durant').
evolucion('Primera','Deino').
evolucion('Segunda','Zweilous').
evolucion('Tercera','Hydreigon').
evolucion('Primera','Larvesta').
evolucion('Segunda','Volcarona').
evolucion('Unica','Cobalion').
evolucion('Unica','Terrakion').
evolucion('Unica','Virizion').
evolucion('Unica','Tornadus').
evolucion('Unica','Thundurus').
evolucion('Unica','Reshiram').
evolucion('Unica','Zekrom').
evolucion('Unica','Landorus').
evolucion('Unica','Kyurem').
evolucion('Unica','Keldeo').
evolucion('Unica','Meloetta').
evolucion('Unica','Genesect').

evolucion('Primera','Chespin').
evolucion('Segunda','Quilladin').
evolucion('Tercera','Chesnaught').
evolucion('Primera','Fennekin').
evolucion('Segunda','Braixen').
evolucion('Tercera','Delphox').
evolucion('Primera','Froakie').
evolucion('Segunda','Frogadier').
evolucion('Tercera','Greninja').
evolucion('Primera','Bunnelby').
evolucion('Segunda','Diggersby').
evolucion('Primera','Fletchling').
evolucion('Segunda','Fletchinder').
evolucion('Tercera','Talonflame').
evolucion('Primera','Scatterbug').
evolucion('Segunda','Spewpa').
evolucion('Tercera','Vivillon').
evolucion('Primera','Litleo').
evolucion('Segunda','Pyroar').
evolucion('Primera','Flabébé').
evolucion('Segunda','Floette').
evolucion('Tercera','Florges').
evolucion('Primera','Skiddo').
evolucion('Segunda','Gogoat').
evolucion('Primera','Pancham').
evolucion('Segunda','Pangoro').
evolucion('Unica','Furfrou').
evolucion('Primera','Espurr').
evolucion('Segunda','Meowstic').
evolucion('Primera','Honedge').
evolucion('Segunda','Doublade').
evolucion('Tercera','Aegislash').
evolucion('Primera','Spritzee').
evolucion('Segunda','Aromatisse').
evolucion('Primera','Swirlix').
evolucion('Segunda','Slurpuff').
evolucion('Primera','Inkay').
evolucion('Segunda','Malamar').
evolucion('Primera','Binacle').
evolucion('Segunda','Barbaracle').
evolucion('Primera','Skrelp').
evolucion('Segunda','Dragalge').
evolucion('Primera','Clauncher').
evolucion('Segunda','Clawitzer').
evolucion('Primera','Helioptile').
evolucion('Segunda','Heliolisk').
evolucion('Primera','Tyrunt').
evolucion('Segunda','Tyrantrum').
evolucion('Primera','Amaura').
evolucion('Segunda','Aurorus').
evolucion('Segunda','Sylveon').
evolucion('Unica','Hawlucha').
evolucion('Unica','Dedenne').
evolucion('Unica','Carbink').
evolucion('Primera','Goomy').
evolucion('Segunda','Sliggoo').
evolucion('Tercera','Goodra').
evolucion('Unica','Klefki').
evolucion('Primera','Phantump').
evolucion('Segunda','Trevenant').
evolucion('Primera','Pumpkaboo').
evolucion('Segunda','Gourgeist').
evolucion('Primera','Bergmite').
evolucion('Segunda','Avalugg').
evolucion('Primera','Noibat').
evolucion('Segunda','Noivern').
evolucion('Unica','Xerneas').
evolucion('Unica','Yveltal').
evolucion('Unica','Zygarde').
evolucion('Unica','Diancie').
evolucion('Unica','Hoopa').
evolucion('Unica','Volcanion').

evolucion('Primera','Rowlet').
evolucion('Segunda','Dartrix').
evolucion('Tercera','Decidueye').
evolucion('Primera','Litten').
evolucion('Segunda','Torracat').
evolucion('Tercera','Incineroar').
evolucion('Primera','Popplio').
evolucion('Segunda','Brionne').
evolucion('Tercera','Primarina').
evolucion('Primera','Pikipek').
evolucion('Segunda','Trumbeak').
evolucion('Tercera','Toucannon').
evolucion('Primera','Yungoos').
evolucion('Segunda','Gumshoos').
evolucion('Primera','Grubbin').
evolucion('Segunda','Charjabug').
evolucion('Tercera','Vikavolt').
evolucion('Primera','Crabrawler').
evolucion('Segunda','Crabominable').
evolucion('Unica','Oricorio').
evolucion('Primera','Cutiefly').
evolucion('Segunda','Ribombee').
evolucion('Primera','Rockruff').
evolucion('Segunda','Lycanroc').
evolucion('Unica','Wishiwashi').
evolucion('Primera','Mareanie').
evolucion('Segunda','Toxapex').
evolucion('Primera','Mudbray').
evolucion('Segunda','Mudsdale').
evolucion('Primera','Dewpider').
evolucion('Segunda','Araquanid').
evolucion('Primera','Fomantis').
evolucion('Segunda','Lurantis').
evolucion('Primera','Morelull').
evolucion('Segunda','Shiinotic').
evolucion('Primera','Salandit').
evolucion('Segunda','Salazzle').
evolucion('Primera','Stufful').
evolucion('Segunda','Bewear').
evolucion('Primera','Bounsweet').
evolucion('Segunda','Steenee').
evolucion('Tercera','Tsareena').
evolucion('Unica','Comfey').
evolucion('Unica','Oranguru').
evolucion('Unica','Passimian').
evolucion('Primera','Wimpod').
evolucion('Segunda','Golisopod').
evolucion('Primera','Sandygast').
evolucion('Segunda','Palossand').
evolucion('Unica','Pyukumuku').
evolucion('Primera','Type:Null').
evolucion('Segunda','Silvally').
evolucion('Unica','Minior').
evolucion('Unica','Komala').
evolucion('Unica','Turtonator').
evolucion('Unica','Togedemaru').
evolucion('Unica','Mimikyu').
evolucion('Unica','Bruxish').
evolucion('Unica','Drampa').
evolucion('Unica','Dhelmise').
evolucion('Primera','Jangmo-o').
evolucion('Segunda','Hakamo-o').
evolucion('Tercera','Kommo-o').
evolucion('Unica','Tapu-Koko').
evolucion('Unica','Tapu-Lele').
evolucion('Unica','Tapu-Bulu').
evolucion('Unica','Tapu-Fini').
evolucion('Primera','Cosmog').
evolucion('Segunda','Cosmoem').
evolucion('Tercera','Solgaleo').
evolucion('Tercera','Lunala').
evolucion('Unica','Nihilego').
evolucion('Unica','Buzzwole').
evolucion('Unica','Pheromosa').
evolucion('Unica','Xurkitree').
evolucion('Unica','Celesteela').
evolucion('Unica','Kartana').
evolucion('Unica','Guzzlord').
evolucion('Unica','Necrozma').
evolucion('Unica','Magearna').
evolucion('Unica','Marshadow').
evolucion('Primera','Poipole').
evolucion('Segunda','Naganadel').
evolucion('Unica','Stakataka').
evolucion('Unica','Blacephalon').
evolucion('Unica','Zeraora').
evolucion('Primera','Meltan').
evolucion('Segunda','Melmetal').

evolucion('Primera','Rattata-de-Alola').
evolucion('Segunda','Raticate-de-Alola').
evolucion('Primera','Meowth-de-Alola').
evolucion('Segunda','Persian-de-Alola').
evolucion('Primera','Sandshrew-de-Alola').
evolucion('Segunda','Sandslash-de-Alola').
evolucion('Primera','Vulpix-de-Alola').
evolucion('Segunda','Ninetales-de-Alola').
evolucion('Segunda','Exeggutor-de-Alola').
evolucion('Segunda','Marowak-de-Alola').
evolucion('Tercera','Raichu-de-Alola').
evolucion('Primera','Grimer-de-Alola').
evolucion('Segunda','Muk-de-Alola').
evolucion('Primera','Diglett-de-Alola').
evolucion('Segunda','Dugtrio-de-Alola').

evolucion('Mega/Otra','Mega-Abomasnow').
evolucion('Mega/Otra','Mega-Absol').
evolucion('Mega/Otra','Mega-Aerodactyl').
evolucion('Mega/Otra','Mega-Aggron').
evolucion('Mega/Otra','Mega-Alakazam').
evolucion('Mega/Otra','Mega-Altaria').
evolucion('Mega/Otra','Mega-Ampharos').
evolucion('Mega/Otra','Mega-Audino').
evolucion('Mega/Otra','Mega-Banette').
evolucion('Mega/Otra','Mega-Beedrill').
evolucion('Mega/Otra','Mega-Blastoise').
evolucion('Mega/Otra','Mega-Blaziken').
evolucion('Mega/Otra','Mega-Camerup').
evolucion('Mega/Otra','Mega-Charizard-X').
evolucion('Mega/Otra','Mega-Charizard-Y').
evolucion('Mega/Otra','Mega-Diancie').
evolucion('Mega/Otra','Mega-Gallade').
evolucion('Mega/Otra','Mega-Garchomp').
evolucion('Mega/Otra','Mega-Gardevoir').
evolucion('Mega/Otra','Mega-Gengar').
evolucion('Mega/Otra','Mega-Glalie').
evolucion('Mega/Otra','Mega-Gyarados').
evolucion('Mega/Otra','Mega-Heracross').
evolucion('Mega/Otra','Mega-Houndoom').
evolucion('Mega/Otra','Mega-Kangaskhan').
evolucion('Mega/Otra','Mega-Latias').
evolucion('Mega/Otra','Mega-Latios').
evolucion('Mega/Otra','Mega-Lopunny').
evolucion('Mega/Otra','Mega-Lucario').
evolucion('Mega/Otra','Mega-Manectric').
evolucion('Mega/Otra','Mega-Mawile').
evolucion('Mega/Otra','Mega-Medicham').
evolucion('Mega/Otra','Mega-Metagross').
evolucion('Mega/Otra','Mega-Mewtwo-X').
evolucion('Mega/Otra','Mega-Mewtwo-Y').
evolucion('Mega/Otra','Mega-Pidgeot').
evolucion('Mega/Otra','Mega-Pinsir').
evolucion('Mega/Otra','Mega-Rayquaza').
evolucion('Mega/Otra','Mega-Sableye').
evolucion('Mega/Otra','Mega-Salamence').
evolucion('Mega/Otra','Mega-Sceptile').
evolucion('Mega/Otra','Mega-Scizor').
evolucion('Mega/Otra','Mega-Sharpedo').
evolucion('Mega/Otra','Mega-Slowbro').
evolucion('Mega/Otra','Mega-Steelix').
evolucion('Mega/Otra','Mega-Swampert').
evolucion('Mega/Otra','Mega-Tyranitar').
evolucion('Mega/Otra','Mega-Venusaur').

evolucion('Mega/Otra','Groudon-Primigenio').
evolucion('Mega/Otra','Kyogre-Primigenio').
evolucion('Mega/Otra','Meloetta-Pirueta').
evolucion('Mega/Otra','Keldeo-Resolete').
evolucion('Mega/Otra','Tornadus-Therian').
evolucion('Mega/Otra','Thundurus-Therian').
evolucion('Mega/Otra','Landorus-Therian').
evolucion('Mega/Otra','Rotom-Calor').
evolucion('Mega/Otra','Rotom-Frio').
evolucion('Mega/Otra','Rotom-Ventilador').
evolucion('Mega/Otra','Rotom-Corte').
evolucion('Mega/Otra','Rotom-Lavado').

evolucion('Unica','Missingno').