figura('Cabeza','Shellder').
figura('Cabeza','Cloyster').
figura('Cabeza','Gastly').
figura('Cabeza','Voltorb').
figura('Cabeza','Electrode').
figura('Cabeza','Koffing').
figura('Cabeza','Ditto').
figura('Cabeza','Sunkern').
figura('Cabeza','Misdreavus').
figura('Cabeza','Unown').
figura('Cabeza','Pineco').
figura('Cabeza','Forretress').
figura('Cabeza','Silcoon').
figura('Cabeza','Cascoon').
figura('Cabeza','Lunatone').
figura('Cabeza','Solrock').
figura('Cabeza','Castform').
figura('Cabeza','Shuppet').
figura('Cabeza','Glalie').
figura('Cabeza','Mega-Glalie').
figura('Cabeza','Clamperl').
figura('Cabeza','Mismagius').
figura('Cabeza','Bronzor').
figura('Cabeza','Rotom').
figura('Cabeza','Rotom-Calor').
figura('Cabeza','Rotom-Lavado').
figura('Cabeza','Rotom-Corte').
figura('Cabeza','Rotom-Frio').
figura('Cabeza','Rotom-Ventilador').
figura('Cabeza','Whirlipede').
figura('Cabeza','Cottonee').
figura('Cabeza','Solosis').
figura('Cabeza','Duosion').
figura('Cabeza','Ferroseed').
figura('Cabeza','Cryogonal').
figura('Cabeza','Shelmet').
figura('Cabeza','Carbink').
figura('Cabeza','Klefki').
figura('Cabeza','Pumpkaboo').
figura('Cabeza','Comfey').
figura('Cabeza','Minior').
figura('Cabeza','Cosmog').
figura('Cabeza','Cosmoem').
figura('Cabeza','Missingno').

figura('Cabeza-Pies','Oddish').
figura('Cabeza-Pies','Poliwag').
figura('Cabeza-Pies','Doduo').
figura('Cabeza-Pies','Dodrio').
figura('Cabeza-Pies','Exeggutor').
figura('Cabeza-Pies','Exeggutor-de-Alola').
figura('Cabeza-Pies','Tangela').
figura('Cabeza-Pies','Porygon').
figura('Cabeza-Pies','Wooper').
figura('Cabeza-Pies','Porygon2').
figura('Cabeza-Pies','Torchic').
figura('Cabeza-Pies','Seedot').
figura('Cabeza-Pies','Shroomish').
figura('Cabeza-Pies','Azurill').
figura('Cabeza-Pies','Cherrim').
figura('Cabeza-Pies','Bonsly').
figura('Cabeza-Pies','Roggenrola').
figura('Cabeza-Pies','Swirlix').
figura('Cabeza-Pies','Dewpider').
figura('Cabeza-Pies','Bounsweet').

figura('Aletas','Seel').
figura('Aletas','Dewgong').
figura('Aletas','Goldeen').
figura('Aletas','Seaking').
figura('Aletas','Magikarp').
figura('Aletas','Lapras').
figura('Aletas','Chinchou').
figura('Aletas','Lanturn').
figura('Aletas','Qwilfish').
figura('Aletas','Remoraid').
figura('Aletas','Carvanha').
figura('Aletas','Sharpedo').
figura('Aletas','Mega-Sharpedo').
figura('Aletas','Wailmer').
figura('Aletas','Wailord').
figura('Aletas','Barboach').
figura('Aletas','Whiscash').
figura('Aletas','Feebas').
figura('Aletas','Spheal').
figura('Aletas','Sealeo').
figura('Aletas','Relicanth').
figura('Aletas','Luvdisc').
figura('Aletas','Kyogre').
figura('Aletas','Kyogre-Primigenio').
figura('Aletas','Finneon').
figura('Aletas','Lumineon').
figura('Aletas','Tympole').
figura('Aletas','Basculin').
figura('Aletas','Alomomola').
figura('Aletas','Tynamo').
figura('Aletas','Eelektrik').
figura('Aletas','Eelektross').
figura('Aletas','Stunfisk').
figura('Aletas','Popplio').
figura('Aletas','Brionne').
figura('Aletas','Primarina').
figura('Aletas','Wishiwashi').
figura('Aletas','Bruxish').

figura('Insecto','Caterpie').
figura('Insecto','Weedle').
figura('Insecto','Paras').
figura('Insecto','Parasect').
figura('Insecto','Krabby').
figura('Insecto','Kingler').
figura('Insecto','Kabuto').
figura('Insecto','Spinarak').
figura('Insecto','Ariados').
figura('Insecto','Shuckle').
figura('Insecto','Corsola').
figura('Insecto','Wurmple').
figura('Insecto','Lotad').
figura('Insecto','Surskit').
figura('Insecto','Nincada').
figura('Insecto','Trapinch').
figura('Insecto','Corphish').
figura('Insecto','Crawdaunt').
figura('Insecto','Anorith').
figura('Insecto','Skorupi').
figura('Insecto','Drapion').
figura('Insecto','Sewaddle').
figura('Insecto','Venipede').
figura('Insecto','Scolipede').
figura('Insecto','Dwebble').
figura('Insecto','Crustle').
figura('Insecto','Joltik').
figura('Insecto','Galvantula').
figura('Insecto','Durant').
figura('Insecto','Larvesta').
figura('Insecto','Scatterbug').
figura('Insecto','Clauncher').
figura('Insecto','Grubbin').
figura('Insecto','Crabrawler').
figura('Insecto','Crabominable').
figura('Insecto','Araquanid').

figura('Cuadrupedo','Bulbasaur').
figura('Cuadrupedo','Ivysaur').
figura('Cuadrupedo','Venusaur').
figura('Cuadrupedo','Mega-Venusaur').
figura('Cuadrupedo','Rattata').
figura('Cuadrupedo','Raticate').
figura('Cuadrupedo','Rattata-de-Alola').
figura('Cuadrupedo','Raticate-de-Alola').
figura('Cuadrupedo','Pikachu').
%figura('Bipedo-Cola','Pikachu').
figura('Cuadrupedo','Nidoran-F').
figura('Cuadrupedo','Nidorina').
figura('Cuadrupedo','Nidoran-M').
figura('Cuadrupedo','Nidorino').
figura('Cuadrupedo','Vulpix').
figura('Cuadrupedo','Ninetales').
figura('Cuadrupedo','Vulpix-de-Alola').
figura('Cuadrupedo','Ninetales-de-Alola').
figura('Cuadrupedo','Meowth').
figura('Cuadrupedo','Persian').
figura('Cuadrupedo','Meowth-de-Alola').
figura('Cuadrupedo','Persian-de-Alola').
figura('Cuadrupedo','Growlithe').
figura('Cuadrupedo','Arcanine').
figura('Cuadrupedo','Ponyta').
figura('Cuadrupedo','Rapidash').
figura('Cuadrupedo','Slowpoke').
figura('Cuadrupedo','Rhyhorn').
figura('Cuadrupedo','Tauros').
figura('Cuadrupedo','Eevee').
figura('Cuadrupedo','Vaporeon').
figura('Cuadrupedo','Jolteon').
figura('Cuadrupedo','Flareon').
figura('Cuadrupedo','Chikorita').
figura('Cuadrupedo','Bayleef').
figura('Cuadrupedo','Meganium').
figura('Cuadrupedo','Quilava').
figura('Cuadrupedo','Typhlosion').
figura('Cuadrupedo','Sentret').
figura('Cuadrupedo','Furret').
figura('Cuadrupedo','Pichu').
figura('Cuadrupedo','Mareep').
figura('Cuadrupedo','Espeon').
figura('Cuadrupedo','Umbreon').
figura('Cuadrupedo','Girafarig').
figura('Cuadrupedo','Swinub').
figura('Cuadrupedo','Piloswine').
figura('Cuadrupedo','Houndour').
figura('Cuadrupedo','Houndoom').
figura('Cuadrupedo','Mega-Houndoom').
figura('Cuadrupedo','Phanpy').
figura('Cuadrupedo','Donphan').
figura('Cuadrupedo','Stantler').
figura('Cuadrupedo','Raikou').
figura('Cuadrupedo','Entei').
figura('Cuadrupedo','Suicune').
figura('Cuadrupedo','Mudkip').
figura('Cuadrupedo','Poochyena').
figura('Cuadrupedo','Mightyena').
figura('Cuadrupedo','Zigzagoon').
figura('Cuadrupedo','Linoone').
figura('Cuadrupedo','Slakoth').
figura('Cuadrupedo','Skitty').
figura('Cuadrupedo','Delcatty').
figura('Cuadrupedo','Aron').
figura('Cuadrupedo','Lairon').
figura('Cuadrupedo','Electrike').
figura('Cuadrupedo','Manectric').
figura('Cuadrupedo','Mega-Manectric').
figura('Cuadrupedo','Numel').
figura('Cuadrupedo','Camerupt').
figura('Cuadrupedo','Mega-Camerupt').
figura('Cuadrupedo','Torkoal').
figura('Cuadrupedo','Tropius').
figura('Cuadrupedo','Absol').
figura('Cuadrupedo','Mega-Absol').
figura('Cuadrupedo','Walrein').
figura('Cuadrupedo','Shelgon').
figura('Cuadrupedo','Turtwig').
figura('Cuadrupedo','Grotle').
figura('Cuadrupedo','Torterra').
figura('Cuadrupedo','Bidoof').
figura('Cuadrupedo','Shinx').
figura('Cuadrupedo','Luxio').
figura('Cuadrupedo','Luxray').
figura('Cuadrupedo','Shieldon').
figura('Cuadrupedo','Bastiodon').
figura('Cuadrupedo','Pachirisu').
figura('Cuadrupedo','Buizel').
figura('Cuadrupedo','Floatzel').
figura('Cuadrupedo','Glameow').
figura('Cuadrupedo','Purugly').
figura('Cuadrupedo','Stunky').
figura('Cuadrupedo','Skuntank').
figura('Cuadrupedo','Hippopotas').
figura('Cuadrupedo','Hippowdon').
figura('Cuadrupedo','Leafeon').
figura('Cuadrupedo','Glaceon').
figura('Cuadrupedo','Mamoswine').
figura('Cuadrupedo','Dialga').
figura('Cuadrupedo','Heatran').
figura('Cuadrupedo','Shaymin').
figura('Cuadrupedo','Arceus').
figura('Cuadrupedo','Tepig').
figura('Cuadrupedo','Samurott').
figura('Cuadrupedo','Patrat').
figura('Cuadrupedo','Lillipup').
figura('Cuadrupedo','Herdier').
figura('Cuadrupedo','Stoutland').
figura('Cuadrupedo','Purrloin').
figura('Cuadrupedo','Liepard').
figura('Cuadrupedo','Munna').
figura('Cuadrupedo','Blitzle').
figura('Cuadrupedo','Zebstrika').
figura('Cuadrupedo','Sandile').
figura('Cuadrupedo','Krokorok').
figura('Cuadrupedo','Darmanitan').
figura('Cuadrupedo','Tirtouga').
figura('Cuadrupedo','Zorua').
figura('Cuadrupedo','Minccino').
figura('Cuadrupedo','Cinccino').
figura('Cuadrupedo','Deerling').
figura('Cuadrupedo','Sawsbuck').
figura('Cuadrupedo','Emolga').
figura('Cuadrupedo','Beartic').
figura('Cuadrupedo','Bouffalant').
figura('Cuadrupedo','Deino').
figura('Cuadrupedo','Zweilous').
figura('Cuadrupedo','Cobalion').
figura('Cuadrupedo','Terrakion').
figura('Cuadrupedo','Virizion').
figura('Cuadrupedo','Landorus').
figura('Cuadrupedo','Keldeo').
figura('Cuadrupedo','Keldeo-Resolete').
figura('Cuadrupedo','Fennekin').
figura('Cuadrupedo','Froakie').
figura('Cuadrupedo','Litleo').
figura('Cuadrupedo','Pyroar').
figura('Cuadrupedo','Skiddo').
figura('Cuadrupedo','Gogoat').
figura('Cuadrupedo','Furfrou').
figura('Cuadrupedo','Amaura').
figura('Cuadrupedo','Aurorus').
figura('Cuadrupedo','Sylveon').
figura('Cuadrupedo','Bergmite').
figura('Cuadrupedo','Avalugg').
figura('Cuadrupedo','Xerneas').
figura('Cuadrupedo','Zygarde').
figura('Cuadrupedo','Volcanion').
figura('Cuadrupedo','Litten').
figura('Cuadrupedo','Torracat').
figura('Cuadrupedo','Yungoos').
figura('Cuadrupedo','Gumshoos').
figura('Cuadrupedo','Rockruff').
figura('Cuadrupedo','Lycanroc').
figura('Cuadrupedo','Mudbray').
figura('Cuadrupedo','Mudsdale').
figura('Cuadrupedo','Salandit').
figura('Cuadrupedo','Salazzle').
figura('Cuadrupedo','Stufful').
figura('Cuadrupedo','Type:Null').
figura('Cuadrupedo','Silvally').
figura('Cuadrupedo','Jangmo-o').
figura('Cuadrupedo','Solgaleo').
figura('Cuadrupedo','Necrozma').
figura('Cuadrupedo','Stakataka').
figura('Cuadrupedo','Tornadus-Therian').
figura('Cuadrupedo','Thundurus-Therian').
figura('Cuadrupedo','Landorus-Therian').

figura('+4-Alas','Butterfree').
figura('+4-Alas','Beedrill').
figura('+4-Alas','Mega-Beedrill').
figura('+4-Alas','Venomoth').
figura('+4-Alas','Scyther').
figura('+4-Alas','Mega-Pinsir').
figura('+4-Alas','Crobat').
figura('+4-Alas','Yanma').
figura('+4-Alas','Scizor').
figura('+4-Alas','Mega-Scizor').
figura('+4-Alas','Beautifly').
figura('+4-Alas','Dustox').
figura('+4-Alas','Masquerain').
figura('+4-Alas','Ninjask').
figura('+4-Alas','Vibrava').
figura('+4-Alas','Kricketune').
figura('+4-Alas','Mothim').
figura('+4-Alas','Vespiquen').
figura('+4-Alas','Yanmega').
figura('+4-Alas','Volcarona').
figura('+4-Alas','Vivillon').
figura('+4-Alas','Ribombee').
figura('+4-Alas','Necrozma').
figura('+4-Alas','Heracross').
figura('+4-Alas','Mega-Heracross').

figura('Combinacion','Dugtrio').
figura('Combinacion','Dugtrio-de-Alola').
figura('Combinacion','Magneton').
figura('Combinacion','Exeggcute').
figura('Combinacion','Weezing').
figura('Combinacion','Metagross').
figura('Combinacion','Mega-Metagross').
figura('Combinacion','Combee').
figura('Combinacion','Cherubi').
figura('Combinacion','Probopass').
figura('Combinacion','Vanilluxe').
figura('Combinacion','Klink').
figura('Combinacion','Klang').
figura('Combinacion','Klinklang').
figura('Combinacion','Doublade').
figura('Combinacion','Binacle').
figura('Combinacion','Barbaracle').
figura('Combinacion','Wishiwashi').

figura('Extremidades','Tentacool').
figura('Extremidades','Tentacruel').
figura('Extremidades','Omanyte').
figura('Extremidades','Omastar').
figura('Extremidades','Octillery').
figura('Extremidades','Carnivine').
figura('Extremidades','Giratina').
figura('Extremidades','Boldore').
figura('Extremidades','Gigalith').
figura('Extremidades','Frillish').
figura('Extremidades','Jellicent').
figura('Extremidades','Ferrothorn').
figura('Extremidades','Inkay').
figura('Extremidades','Trevenant').
figura('Extremidades','Toxapex').
figura('Extremidades','Wimpod').
figura('Extremidades','Nihilego').
figura('Extremidades','Buzzwole').

figura('Cabeza-Base','Diglett').
figura('Cabeza-Base','Diglett-de-Alola').
figura('Cabeza-Base','Weepinbell').
figura('Cabeza-Base','Victreebel').
figura('Cabeza-Base','Horsea').
figura('Cabeza-Base','Seadra').
figura('Cabeza-Base','Staryu').
figura('Cabeza-Base','Starmie').
figura('Cabeza-Base','Wobbuffet').
figura('Cabeza-Base','Kingdra').
figura('Cabeza-Base','Shedinja').
figura('Cabeza-Base','Lileep').
figura('Cabeza-Base','Cradily').
figura('Cabeza-Base','Beldum').
figura('Cabeza-Base','Burmy').
figura('Cabeza-Base','Wormadam-Tronco-Arena').
figura('Cabeza-Base','Wormadam-Tronco-Planta').
figura('Cabeza-Base','Wormadam-Tronco-Basura').
figura('Cabeza-Base','Spiritomb').
figura('Cabeza-Base','Petilil').
figura('Cabeza-Base','Lilligant').
figura('Cabeza-Base','Maractus').
figura('Cabeza-Base','Cofagrigus').
figura('Cabeza-Base','Vanillite').
figura('Cabeza-Base','Vanillish').
figura('Cabeza-Base','Litwick').
figura('Cabeza-Base','Spewpa').
figura('Cabeza-Base','Honedge').
figura('Cabeza-Base','Aegislash').
figura('Cabeza-Base','Malamar').
figura('Cabeza-Base','Skrelp').
figura('Cabeza-Base','Dragalge').
figura('Cabeza-Base','Gourgeist').
figura('Cabeza-Base','Mareanie').
figura('Cabeza-Base','Morelull').
figura('Cabeza-Base','Dhelmise').
figura('Cabeza-Base','Meltan').

figura('Bipedo-Cola','Charmander').
figura('Bipedo-Cola','Charmeleon').
figura('Bipedo-Cola','Squirtle').
figura('Bipedo-Cola','Wartortle').
figura('Bipedo-Cola','Blastoise').
figura('Bipedo-Cola','Mega-Blastoise').
figura('Bipedo-Cola','Raichu').
figura('Bipedo-Cola','Raichu-de-Alola').
figura('Bipedo-Cola','Sandshrew').
figura('Bipedo-Cola','Sandslash').
figura('Bipedo-Cola','Sandshrew-de-Alola').
figura('Bipedo-Cola','Sandslash-de-Alola').
figura('Bipedo-Cola','Nidoqueen').
figura('Bipedo-Cola','Nidoking').
figura('Bipedo-Cola','Clefairy').
figura('Bipedo-Cola','Clefable').
figura('Bipedo-Cola','Psyduck').
figura('Bipedo-Cola','Golduck').
figura('Bipedo-Cola','Mankey').
figura('Bipedo-Cola','Primeape').
figura('Bipedo-Cola','Abra').
figura('Bipedo-Cola','Kadabra').
figura('Bipedo-Cola','Machop').
figura('Bipedo-Cola','Slowbro').
figura('Bipedo-Cola','Gengar').
figura('Bipedo-Cola','Mega-Gengar').
figura('Bipedo-Cola','Cubone').
figura('Bipedo-Cola','Marowak').
figura('Bipedo-Cola','Marowak-de-Alola').
figura('Bipedo-Cola','Lickitung').
figura('Bipedo-Cola','Rhydon').
figura('Bipedo-Cola','Chansey').
figura('Bipedo-Cola','Kangaskhan').
figura('Bipedo-Cola','Mega-Kangaskhan').
figura('Bipedo-Cola','Electabuzz').
figura('Bipedo-Cola','Magmar').
figura('Bipedo-Cola','Kabutops').
figura('Bipedo-Cola','Mewtwo').
figura('Bipedo-Cola','Mega-Mewtwo-X').
figura('Bipedo-Cola','Mega-Mewtwo-Y').
figura('Bipedo-Cola','Mew').
figura('Bipedo-Cola','Totodile').
figura('Bipedo-Cola','Croconaw').
figura('Bipedo-Cola','Feraligatr').
figura('Bipedo-Cola','Cleffa').
figura('Bipedo-Cola','Flaaffy').
figura('Bipedo-Cola','Ampharos').
figura('Bipedo-Cola','Mega-Ampharos').
figura('Bipedo-Cola','Marill').
figura('Bipedo-Cola','Azumarill').
figura('Bipedo-Cola','Hoppip').
figura('Bipedo-Cola','Skiploom').
figura('Bipedo-Cola','Jumpluff').
figura('Bipedo-Cola','Aipom').
figura('Bipedo-Cola','Quagsire').
figura('Bipedo-Cola','Slowking').
figura('Bipedo-Cola','Granbull').
figura('Bipedo-Cola','Sneasel').
figura('Bipedo-Cola','Teddiursa').
figura('Bipedo-Cola','Ursaring').
figura('Bipedo-Cola','Smeargle').
figura('Bipedo-Cola','Hitmontop').
figura('Bipedo-Cola','Magby').
figura('Bipedo-Cola','Miltank').
figura('Bipedo-Cola','Larvitar').
figura('Bipedo-Cola','Tyranitar').
figura('Bipedo-Cola','Mega-Tyranitar').
figura('Bipedo-Cola','Treecko').
figura('Bipedo-Cola','Grovyle').
figura('Bipedo-Cola','Sceptile').
figura('Bipedo-Cola','Mega-Sceptile').
figura('Bipedo-Cola','Combusken').
figura('Bipedo-Cola','Blaziken').
figura('Bipedo-Cola','Mega-Blaziken').
figura('Bipedo-Cola','Marshtomp').
figura('Bipedo-Cola','Swampert').
figura('Bipedo-Cola','Mega-Swampert').
figura('Bipedo-Cola','Breloom').
figura('Bipedo-Cola','Vigoroth').
figura('Bipedo-Cola','Whismur').
figura('Bipedo-Cola','Loudred').
figura('Bipedo-Cola','Exploud').
figura('Bipedo-Cola','Aggron').
figura('Bipedo-Cola','Mega-Aggron').
figura('Bipedo-Cola','Plusle').
figura('Bipedo-Cola','Minun').
figura('Bipedo-Cola','Grumpig').
figura('Bipedo-Cola','Spinda').
figura('Bipedo-Cola','Zangoose').
figura('Bipedo-Cola','Armaldo').
figura('Bipedo-Cola','Kecleon').
figura('Bipedo-Cola','Banette').
figura('Bipedo-Cola','Mega-Banette').
figura('Bipedo-Cola','Wynaut').
figura('Bipedo-Cola','Groudon').
figura('Bipedo-Cola','Groudon-Primigenio').
figura('Bipedo-Cola','Chimchar').
figura('Bipedo-Cola','Monferno').
figura('Bipedo-Cola','Infernape').
figura('Bipedo-Cola','Prinplup').
figura('Bipedo-Cola','Empoleon').
figura('Bipedo-Cola','Bibarel').
figura('Bipedo-Cola','Cranidos').
figura('Bipedo-Cola','Rampardos').
figura('Bipedo-Cola','Ambipom').
figura('Bipedo-Cola','Buneary').
figura('Bipedo-Cola','Lopunny').
figura('Bipedo-Cola','Mega-Lopunny').
figura('Bipedo-Cola','Gible').
figura('Bipedo-Cola','Gabite').
figura('Bipedo-Cola','Garchomp').
figura('Bipedo-Cola','Mega-Garchomp').
figura('Bipedo-Cola','Riolu').
figura('Bipedo-Cola','Lucario').
figura('Bipedo-Cola','Mega-Lucario').
figura('Bipedo-Cola','Snover').
figura('Bipedo-Cola','Abomasnow').
figura('Bipedo-Cola','Mega-Abomasnow').
figura('Bipedo-Cola','Weavile').
figura('Bipedo-Cola','Rhyperior').
figura('Bipedo-Cola','Electivire').
figura('Bipedo-Cola','Magmortar').
figura('Bipedo-Cola','Uxie').
figura('Bipedo-Cola','Mesprit').
figura('Bipedo-Cola','Azelf').
figura('Bipedo-Cola','Palkia').
figura('Bipedo-Cola','Snivy').
figura('Bipedo-Cola','Servine').
figura('Bipedo-Cola','Pignite').
figura('Bipedo-Cola','Emboar').
figura('Bipedo-Cola','Oshawott').
figura('Bipedo-Cola','Dewott').
figura('Bipedo-Cola','Watchog').
figura('Bipedo-Cola','Pansage').
figura('Bipedo-Cola','Simisage').
figura('Bipedo-Cola','Pansear').
figura('Bipedo-Cola','Simisear').
figura('Bipedo-Cola','Panpour').
figura('Bipedo-Cola','Simipour').
figura('Bipedo-Cola','Drilbur').
figura('Bipedo-Cola','Audino').
figura('Bipedo-Cola','Mega-Audino').
figura('Cabeza-Pies','Palpitoad').
figura('Bipedo-Cola','Krookodile').
figura('Bipedo-Cola','Scraggy').
figura('Bipedo-Cola','Scrafty').
figura('Bipedo-Cola','Carracosta').
figura('Bipedo-Cola','Zoroark').
figura('Bipedo-Cola','Elgyem').
figura('Bipedo-Cola','Axew').
figura('Bipedo-Cola','Fraxure').
figura('Bipedo-Cola','Haxorus').
figura('Bipedo-Cola','Cubchoo').
figura('Bipedo-Cola','Mienfoo').
figura('Bipedo-Cola','Mienshao').
figura('Bipedo-Cola','Heatmor').
figura('Bipedo-Cola','Hydreigon').
figura('Bipedo-Cola','Thundurus').
figura('Bipedo-Cola','Kyurem').
figura('Bipedo-Cola','Chespin').
figura('Bipedo-Cola','Quilladin').
figura('Bipedo-Cola','Chesnaught').
figura('Bipedo-Cola','Braixen').
figura('Bipedo-Cola','Delphox').
figura('Bipedo-Cola','Bunnelby').
figura('Bipedo-Cola','Diggersby').
figura('Bipedo-Cola','Pancham').
figura('Bipedo-Cola','Espurr').
figura('Bipedo-Cola','Meowstic').
figura('Bipedo-Cola','Helioptile').
figura('Bipedo-Cola','Heliolisk').
figura('Bipedo-Cola','Tyrunt').
figura('Bipedo-Cola','Tyrantrum').
figura('Bipedo-Cola','Dedenne').
figura('Bipedo-Cola','Goodra').
figura('Bipedo-Cola','Zygarde').
figura('Bipedo-Cola','Hoopa').
figura('Bipedo-Cola','Incineroar').
figura('Bipedo-Cola','Lycanroc').
figura('Bipedo-Cola','Fomantis').
figura('Bipedo-Cola','Bewear').
figura('Bipedo-Cola','Passimian').
figura('Bipedo-Cola','Turtonator').
figura('Bipedo-Cola','Togedemaru').
figura('Bipedo-Cola','Hakamo-o').
figura('Bipedo-Cola','Kommo-o').
figura('Bipedo-Cola','Xurkitree').
figura('Bipedo-Cola','Guzzlord').
figura('Bipedo-Cola','Poipole').

figura('Bipedo','Pinsir').
figura('Bipedo','Jigglypuff').
figura('Bipedo','Wigglytuff').
figura('Bipedo','Gloom').
figura('Bipedo','Vileplume').
figura('Bipedo','Venonat').
figura('Bipedo','Poliwhirl').
figura('Bipedo','Poliwrath').
figura('Bipedo','Alakazam').
figura('Bipedo','Mega-Alakazam').
figura('Bipedo','Machoke').
figura('Bipedo','Machamp').
figura('Bipedo','Bellsprout').
figura('Bipedo','Graveler').
figura('Bipedo','Golem').
figura('Bipedo','Graveler-de-Alola').
figura('Bipedo','Golem-de-Alola').
figura('Bipedo','Drowzee').
figura('Bipedo','Hypno').
figura('Bipedo','Hitmonlee').
figura('Bipedo','Hitmonchan').
figura('Bipedo','Mr.Mime').
figura('Bipedo','Jynx').
figura('Bipedo','Pinsir').
figura('Bipedo','Snorlax').
figura('Bipedo','Cyndaquil').
figura('Bipedo','Igglybuff').
figura('Bipedo','Togepi').
figura('Bipedo','Bellossom').
figura('Bipedo','Sudowoodo').
figura('Bipedo','Politoed').
figura('Bipedo','Sunflora').
figura('Bipedo','Snubbull').
figura('Bipedo','Tyrogue').
figura('Bipedo','Smoochum').
figura('Bipedo','Elekid').
figura('Bipedo','Blissey').
figura('Bipedo','Lombre').
figura('Bipedo','Ludicolo').
figura('Bipedo','Nuzleaf').
figura('Bipedo','Shiftry').
figura('Bipedo','Ralts').
figura('Bipedo','Kirlia').
figura('Bipedo','Gardevoir').
figura('Bipedo','Mega-Gardevoir').
figura('Bipedo','Slaking').
figura('Bipedo','Makuhita').
figura('Bipedo','Hariyama').
figura('Bipedo','Nosepass').
figura('Bipedo','Sableye').
figura('Bipedo','Mega-Sableye').
figura('Bipedo','Mawile').
figura('Bipedo','Mega-Mawile').
figura('Bipedo','Meditite').
figura('Bipedo','Medicham').
figura('Bipedo','Mega-Medicham').
figura('Bipedo','Illumise').
figura('Bipedo','Roselia').
figura('Bipedo','Cacnea').
figura('Bipedo','Cacturne').
figura('Bipedo','Dusclops').
figura('Bipedo','Snorunt').
figura('Bipedo','Bagon').
figura('Bipedo','Regirock').
figura('Bipedo','Regice').
figura('Bipedo','Registeel').
figura('Bipedo','Jirachi').
figura('Bipedo','Deoxys').
figura('Bipedo','Piplup').
figura('Bipedo','Kricketot').
figura('Bipedo','Budew').
figura('Bipedo','Roserade').
figura('Bipedo','Chingling').
figura('Bipedo','Mime-Jr.').
figura('Bipedo','Happiny').
figura('Bipedo','Munchlax').
figura('Bipedo','Croagunk').
figura('Bipedo','Toxicroak').
figura('Bipedo-Cola','Lickilicky').
figura('Bipedo','Tangrowth').
figura('Bipedo','Gallade').
figura('Bipedo','Mega-Gallade').
figura('Bipedo','Regigigas').
figura('Bipedo','Manaphy').
figura('Bipedo','Darkrai').
figura('Bipedo','Victini').
figura('Bipedo','Musharna').
figura('Bipedo','Excadrill').
figura('Bipedo','Timburr').
figura('Bipedo','Gurdurr').
figura('Bipedo','Conkeldurr').
figura('Bipedo','Seismitoad').
figura('Bipedo','Throh').
figura('Bipedo','Sawk').
figura('Bipedo','Leavanny').
figura('Bipedo','Whimsicott').
figura('Bipedo','Darumaka').
figura('Bipedo','Trubbish').
figura('Bipedo','Garbodor').
figura('Bipedo','Gothita').
figura('Bipedo','Gothorita').
figura('Bipedo','Gothitelle').
figura('Bipedo','Karrablast').
figura('Bipedo','Beheeyem').
figura('Bipedo','Golett').
figura('Bipedo','Golurk').
figura('Bipedo','Pawniard').
figura('Bipedo','Bisharp').
figura('Bipedo','Meloetta').
figura('Bipedo','Meloetta-Pirueta').
figura('Bipedo','Genesect').
figura('Bipedo','Frogadier').
figura('Bipedo-Cola','Greninja').
figura('Bipedo','Pangoro').
figura('Bipedo','Aromatisse').
figura('Bipedo','Slurpuff').
figura('Bipedo','Hawlucha').
figura('Bipedo','Lurantis').
figura('Bipedo','Shiinotic').
figura('Bipedo','Melmetal').
figura('Bipedo','Steenee').
figura('Bipedo','Tsareena').
figura('Bipedo','Oranguru').
figura('Bipedo','Golisopod').
figura('Bipedo','Komala').
figura('Bipedo','Pheromosa').
figura('Bipedo','Celesteela').
figura('Bipedo','Kartana').
figura('Bipedo','Magearna').
figura('Bipedo','Marshadow').
figura('Bipedo','Blacephalon').
figura('Bipedo','Zeraora').

figura('2-Alas','Pidgey').
figura('2-Alas','Pidgeotto').
figura('2-Alas','Pidgeot').
figura('2-Alas','Mega-Pidgeot').
figura('2-Alas','Spearow').
figura('2-Alas','Fearow').
figura('2-Alas','Zubat').
figura('2-Alas','Golbat').
figura('2-Alas','Farfetchd').
figura('2-Alas','Aerodactyl').
figura('2-Alas','Mega-Aerodactyl').
figura('2-Alas','Articuno').
figura('2-Alas','Zapdos').
figura('2-Alas','Moltres').
figura('2-Alas','Hoothoot').
figura('2-Alas','Noctowl').
figura('2-Alas','Ledyba').
figura('2-Alas','Ledian').
figura('2-Alas','Natu').
figura('2-Alas','Xatu').
figura('2-Alas','Murkrow').
figura('2-Alas','Gligar').
figura('2-Alas','Delibird').
figura('2-Alas','Mantine').
figura('2-Alas','Skarmory').
figura('2-Alas','Lugia').
figura('2-Alas','Ho-Oh').
figura('2-Alas','Taillow').
figura('2-Alas','Swellow').
figura('2-Alas','Wingull').
figura('2-Alas','Pelipper').
figura('2-Alas','Flygon').
figura('2-Alas','Swablu').
figura('2-Alas','Altaria').
figura('2-Alas','Mega-Altaria').
figura('2-Alas','Latias').
figura('2-Alas','Latios').
figura('2-Alas','Mega-Latias').
figura('2-Alas','Mega-Latios').
figura('2-Alas','Starly').
figura('2-Alas','Staravia').
figura('2-Alas','Staraptor').
figura('2-Alas','Honchkrow').
figura('2-Alas','Chatot').
figura('2-Alas','Mantyke').
figura('2-Alas','Togekiss').
figura('2-Alas','Gliscor').
figura('2-Alas','Pidove').
figura('2-Alas','Tranquill').
figura('2-Alas','Unfezant').
figura('2-Alas','Woobat').
figura('2-Alas','Swoobat').
figura('2-Alas','Sigilyph').
figura('2-Alas','Archen').
figura('2-Alas','Archeops').
figura('2-Alas','Ducklett').
figura('2-Alas','Swanna').
figura('2-Alas','Rufflet').
figura('2-Alas','Braviary').
figura('2-Alas','Vullaby').
figura('2-Alas','Mandibuzz').
figura('2-Alas','Reshiram').
figura('2-Alas','Fletchling').
figura('2-Alas','Fletchinder').
figura('2-Alas','Talonflame').
figura('2-Alas','Noibat').
figura('2-Alas','Noivern').
figura('2-Alas','Yveltal').
figura('2-Alas','Rowlet').
figura('2-Alas','Dartrix').
figura('2-Alas','Decidueye').
figura('2-Alas','Pikipek').
figura('2-Alas','Trumbeak').
figura('2-Alas','Toucannon').
figura('2-Alas','Oricorio').
figura('2-Alas','Lunala').
figura('2-Alas','Necrozma').
figura('2-Alas','Naganadel').
figura('2-Alas','Togetic').
figura('2-Alas','Victini').
figura('2-Alas','Celebi').
%figura('Bipedo','Celebi').
figura('2-Alas','Illumise').
figura('2-Alas','Charizard').
figura('2-Alas','Mega-Charizard-X').
figura('2-Alas','Mega-Charizard-Y').
figura('2-Alas','Druddigon').
figura('2-Alas','Zekrom').
figura('2-Alas','Dragonite').
figura('2-Alas','Volbeat').
figura('2-Alas','Vikavolt').
figura('2-Alas','Cutiefly').
figura('2-Alas','Salamence').
figura('2-Alas','Mega-Salamence').

figura('Serpiente','Metapod').
figura('Serpiente','Kakuna').
figura('Serpiente','Ekans').
figura('Serpiente','Arbok').
figura('Serpiente','Onix').
figura('Serpiente','Gyarados').
figura('Serpiente','Mega-Gyarados').
figura('Serpiente','Dratini').
figura('Serpiente','Dragonair').
figura('Serpiente','Dunsparce').
figura('Serpiente','Steelix').
figura('Serpiente','Mega-Steelix').
figura('Serpiente','Slugma').
figura('Serpiente','Magcargo').
figura('Serpiente','Pupitar').
figura('Serpiente','Seviper').
figura('Serpiente','Milotic').
figura('Serpiente','Huntail').
figura('Serpiente','Gorebyss').
figura('Serpiente','Rayquaza').
figura('Serpiente','Mega-Rayquaza').
figura('Serpiente','Shellos').
figura('Serpiente','Gastrodon').
figura('Serpiente','Giratina').
figura('Serpiente','Cresselia').
figura('Serpiente','Serperior').
figura('Serpiente','Clawitzer').
figura('Serpiente','Goomy').
figura('Serpiente','Sliggoo').
figura('Serpiente','Zygarde').
figura('Serpiente','Charjabug').
figura('Serpiente','Sandygast').
figura('Serpiente','Palossand').
figura('Serpiente','Pyukumuku').
figura('Serpiente','Mimikyu').
figura('Serpiente','Drampa').

figura('Cabeza-Brazos','Geodude').
figura('Cabeza-Brazos','Geodude-de-Alola').
figura('Cabeza-Brazos','Slowbro').
figura('Cabeza-Brazos','Magnemite').
figura('Cabeza-Brazos','Grimer').
figura('Cabeza-Brazos','Grimer-de-Alola').
figura('Cabeza-Brazos','Muk').
figura('Cabeza-Brazos','Muk-de-Alola').
figura('Cabeza-Brazos','Haunter').
figura('Cabeza-Brazos','Gulpin').
figura('Cabeza-Brazos','Swalot').
figura('Cabeza-Brazos','Spoink').
figura('Cabeza-Brazos','Baltoy').
figura('Cabeza-Brazos','Claydol').
figura('Cabeza-Brazos','Duskull').
figura('Cabeza-Brazos','Chimecho').
figura('Cabeza-Brazos','Metang').
figura('Cabeza-Brazos','Drifloon').
figura('Cabeza-Brazos','Drifblim').
figura('Cabeza-Brazos','Bronzong').
figura('Cabeza-Brazos','Magnezone').
figura('Cabeza-Brazos','Porygon-Z').
figura('Cabeza-Brazos','Dusknoir').
figura('Cabeza-Brazos','Froslass').
figura('Cabeza-Brazos','Phione').
figura('Cabeza-Brazos','Swadloon').
figura('Cabeza-Brazos','Yamask').
figura('Cabeza-Brazos','Reuniclus').
figura('Cabeza-Brazos','Escavalier').
figura('Cabeza-Brazos','Foongus').
figura('Cabeza-Brazos','Amoonguss').
figura('Cabeza-Brazos','Lampent').
figura('Cabeza-Brazos','Chandelure').
figura('Cabeza-Brazos','Accelgor').
figura('Cabeza-Brazos','Tornadus').
figura('Cabeza-Brazos','Thundurus').
figura('Cabeza-Brazos','Landorus').
figura('Cabeza-Brazos','Flabébé').
figura('Cabeza-Brazos','Floette').
figura('Cabeza-Brazos','Florges').
figura('Cabeza-Brazos','Spritzee').
figura('Cabeza-Brazos','Phantump').
figura('Cabeza-Brazos','Diancie').
figura('Cabeza-Brazos','Mega-Diancie').
figura('Cabeza-Brazos','Hoopa').
figura('Cabeza-Brazos','Tapu-Koko').
figura('Cabeza-Brazos','Tapu-Lele').
figura('Cabeza-Brazos','Tapu-Bulu').
figura('Cabeza-Brazos','Tapu-Fini').
figura('Cabeza-Brazos','Necrozma').
figura('Cabeza-Brazos','Mega-Slowbro').