peso('intermedio','	Mega-Latios').
peso('intermedio','Aegislash').
peso('intermedio','Aerodactyl').
peso('intermedio','Ampharos').
peso('intermedio','Arbok').
peso('intermedio','Armaldo').
peso('intermedio','Aron').
peso('intermedio','Articuno').
peso('intermedio','Barbaracle').
peso('intermedio','Beldum').
peso('intermedio','Bergmite').
peso('intermedio','Bisharp').
peso('intermedio','Blastoise').
peso('intermedio','Blaziken').
peso('intermedio','Boldore').
peso('intermedio','Bouffalant').
peso('intermedio','Bronzor').
peso('intermedio','Cacnea').
peso('intermedio','Cacturne').
peso('intermedio','Carracosta').
peso('intermedio','Charizard').
peso('intermedio','Chesnaught').
peso('intermedio','Clamperl').
peso('intermedio','Claydol').
peso('intermedio','Cofagrigus').
peso('intermedio','Conkeldurr').
peso('intermedio','Cradily').
peso('intermedio','Cresselia').
peso('intermedio','Crobat').
peso('intermedio','Darkrai').
peso('intermedio','Darmanitan').
peso('intermedio','Deoxys').
peso('intermedio','Dewgong').
peso('intermedio','Dodrio').
peso('intermedio','Donphan').
peso('intermedio','Dragalge').
peso('intermedio','Drapion').
peso('intermedio','Dugtrio-de-Alola').
peso('intermedio','Dusknoir').
peso('intermedio','Eelektross').
peso('intermedio','Electrode').
peso('intermedio','Empoleon').
peso('intermedio','Exeggutor').
peso('intermedio','Exploud').
peso('intermedio','Feraligatr').
peso('intermedio','Ferrothorn').
peso('intermedio','Flygon').
peso('intermedio','Gabite').
peso('intermedio','Gallade').
peso('intermedio','Garbodor').
peso('intermedio','Garchomp').
peso('intermedio','Genesect').
peso('intermedio','Gligar').
peso('intermedio','Gogoat').
peso('intermedio','Golbat').
peso('intermedio','Golduck').
peso('intermedio','Golett').
peso('intermedio','Graveler').
peso('intermedio','Graveler-de-Alola').
peso('intermedio','Grotle').
peso('intermedio','Grumpig').
peso('intermedio','Haxorus').
peso('intermedio','Heatmor').
peso('intermedio','Heracross').
peso('intermedio','Hitmonchan').
peso('intermedio','Hypnoy').
peso('intermedio','Infernape').
peso('intermedio','Kadabra').
peso('intermedio','Kangaskhan').
peso('intermedio','Kingler').
peso('intermedio','Klangn').
peso('intermedio','Klinklang').
peso('intermedio','Krookodile').
peso('intermedio','Lairon').
peso('intermedio','Landorus').
peso('intermedio','Landorus-Therian').
peso('intermedio','Larvitar').
peso('intermedio','Latios').
peso('intermedio','Lickitung').
peso('intermedio','Lucario').
peso('intermedio','Ludicolo').
peso('intermedio','Lunala').
peso('intermedio','Machoke').
peso('intermedio','Magcargo').
peso('intermedio','Magearna').
peso('intermedio','Magmortar').
peso('intermedio','Magneton').
peso('intermedio','Makuhita').
peso('intermedio','Mantyke').
peso('intermedio','Mega-Aerodactyl').
peso('intermedio','Mega-Ampharos').
peso('intermedio','Mega-Blastoise').
peso('intermedio','Mega-Blaziken').
peso('intermedio','Mega-Charizard-X').
peso('intermedio','Mega-Charizard-Y').
peso('intermedio','Mega-Gallade').
peso('intermedio','Mega-Garchomp').
peso('intermedio','Mega-Heracross').
peso('intermedio','Mega-Kangaskhan').
peso('intermedio','Mega-Latias').
peso('intermedio','Mega-Lucario').
peso('intermedio','Mega-Pidgeot').
peso('intermedio','Mega-Pinsir').
peso('intermedio','Mega-Salamence').
peso('intermedio','Mega-Sceptile').
peso('intermedio','Mega-Slowbro').
peso('intermedio','Mega-Swampert').
peso('intermedio','Meganium').
peso('intermedio','Miltank').
peso('intermedio','Moltres').
peso('intermedio','Mr.Mime').
peso('intermedio','Muk-de-Alola').
peso('intermedio','Munchlax').
peso('intermedio','Musharna').
peso('intermedio','Nidoking').
peso('intermedio','Nidoqueen').
peso('intermedio','Nihilego').
peso('intermedio','Noivern').
peso('intermedio','Nosepass').
peso('intermedio','Pignite').
peso('intermedio','Piloswine').
peso('intermedio','Pinsir').
peso('intermedio','Poliwrath').
peso('intermedio','Pyroar').
peso('intermedio','Quagsire').
peso('intermedio','Rampardos').
peso('intermedio','Rapidash').
peso('intermedio','Rhydon').
peso('intermedio','Rhyhorn').
peso('intermedio','Salamence').
peso('intermedio','Samurott').
peso('intermedio','Sandslash-de-Alola').
peso('intermedio','Sawk').
peso('intermedio','Sawsbuck').
peso('intermedio','Sceptile').
peso('intermedio','Scizor').
peso('intermedio','Scyther').
peso('intermedio','Sealeo').
peso('intermedio','Seel').
peso('intermedio','Seismitoad').
peso('intermedio','Serperior').
peso('intermedio','Seviper').
peso('intermedio','Sharpedo').
peso('intermedio','Shelgon').
peso('intermedio','Shieldon').
peso('intermedio','Shiftry').
peso('intermedio','Skarmory').
peso('intermedio','Slowbro').
peso('intermedio','Slowking').
peso('intermedio','Smeargle').
peso('intermedio','Snover').
peso('intermedio','Spiritomb').
peso('intermedio','Stantler').
peso('intermedio','Starmie').
peso('intermedio','Stoutland').
peso('intermedio','Swalot').
peso('intermedio','Swampert').
peso('intermedio','Tauros').
peso('intermedio','Tentacruel').
peso('intermedio','Throh').
peso('intermedio','Thundurus').
peso('intermedio','Thundurus-Therian').
peso('intermedio','Torkoal').
peso('intermedio','Tornadus').
peso('intermedio','Tornadus-Therian').
peso('intermedio','Trevenant').
peso('intermedio','Tropius').
peso('intermedio','Typhlosion').
peso('intermedio','Vanilluxe').
peso('intermedio','Venusaur').
peso('intermedio','Whirlipede').
peso('intermedio','Wishiwashi').
peso('intermedio','Yanmega').
peso('intermedio','Zapdos').
peso('intermedio','Zebstrika').
peso('intermedio','Zoroark').
peso('pesados','Abomasnow').
peso('pesados','Aggron').
peso('pesados','Arcanine').
peso('pesados','Arceus').
peso('pesados','Aurorus').
peso('pesados','Avalugg').
peso('pesados','Bastiodon').
peso('pesados','Beartic').
peso('pesados','Bronzong').
peso('pesados','Camerupt').
peso('pesados','Celesteela').
peso('pesados','Cloyster').
peso('pesados','Cobalion').
peso('pesados','Cosmoem').
peso('pesados','Crustle').
peso('pesados','Cryogonal').
peso('pesados','Dialga').
peso('pesados','Dragonite').
peso('pesados','Druddigon').
peso('pesados','Electivire').
peso('pesados','Emboar').
peso('pesados','Entei').
peso('pesados','Exeggutor-de-Alola').
peso('pesados','Forretress').
peso('pesados','Gigalith').
peso('pesados','Giratina').
peso('pesados','Glalie').
peso('pesados','Golem').
peso('pesados','Golem-de-Alola').
peso('pesados','Golurk').
peso('pesados','Goodra').
peso('pesados','Groudon').
peso('pesados','Groudon-Primigenio').
peso('pesados','Guzzlord').
peso('pesados','Gyarados').
peso('pesados','Hariyama').
peso('pesados','Heatran').
peso('pesados','Hippowdon').
peso('pesados','Ho-Oh').
peso('pesados','Hoopa').
peso('pesados','Hydreigon').
peso('pesados','Jellicent').
peso('pesados','Kingdra').
peso('pesados','Kyogre').
peso('pesados','Kyogre-Primigenio').
peso('pesados','Kyurem').
peso('pesados','Lapras').
peso('pesados','Lickilicky').
peso('pesados','Lugia').
peso('pesados','Buzzswole').
peso('pesados','Lunatone').
peso('pesados','Machamp').
peso('pesados','Magnezone').
peso('pesados','Mamoswine').
peso('pesados','Mantine').
peso('pesados','Mega-Abomasnow').
peso('pesados','Mega-Aggron').
peso('pesados','Mega-Camerupt').
peso('pesados','Mega-Glalie').
peso('pesados','Mega-Gyarados').
peso('pesados','Mega-Metagross').
peso('pesados','Mega-Mewtwo-X').
peso('pesados','Mega-Rayquaza').
peso('pesados','Mega-Sableye').
peso('pesados','Mega-Scizor').
peso('pesados','Mega-Sharpedo').
peso('pesados','Mega-Steelix').
peso('pesados','Mega-Tyranitar').
peso('pesados','Mega-Venusaur').
peso('pesados','Metagross').
peso('pesados','Metang').
peso('pesados','Mewtwo').
peso('pesados','Milotic').
peso('pesados','Mudsdale').
peso('pesados','Naganadel').
peso('pesados','Onix').
peso('pesados','Palkia').
peso('pesados','Pangoro').
peso('pesados','Probopass').
peso('pesados','Pupitar').
peso('pesados','Raikou').
peso('pesados','Rayquaza').
peso('pesados','Regice').
peso('pesados','Regigigas').
peso('pesados','Regirock').
peso('pesados','Registeel').
peso('pesados','Reshiram').
peso('pesados','Rhyperior').
peso('pesados','Scolipede').
peso('pesados','Slaking').
peso('pesados','Snorlax').
peso('pesados','Solgaleo').
peso('pesados','Solrock').
peso('pesados','Stakataka').
peso('pesados','Steelix').
peso('pesados','Suicune').
peso('pesados','Tangrowth').
peso('pesados','Terrakion').
peso('pesados','Torterra').
peso('pesados','Tyranitar').
peso('pesados','Ursaring').
peso('pesados','Virizion').
peso('pesados','Volcanion').
peso('pesados','Wailmer').
peso('pesados','Wailord').
peso('pesados','Walrein').
peso('pesados','Xerneas').
peso('pesados','Yveltal').
peso('pesados','Zekrom').
peso('pesados','Zygarde').
peso('pesados','Melmetal').
peso('poco','Meltan').
peso('poco','Abra').
peso('poco','Absol').
peso('poco','Accelgor').
peso('poco','Aipom').
peso('poco','Alakazam').
peso('poco','Alomomola').
peso('poco','Altaria').
peso('poco','Amaura').
peso('poco','Ambipom').
peso('poco','Amoonguss').
peso('poco','Anorith').
peso('poco','Archen').
peso('poco','Archeops').
peso('poco','Ariados').
peso('poco','Aromatisse').
peso('poco','Audino').
peso('poco','Axew').
peso('poco','Azelf').
peso('poco','Azumarill').
peso('poco','Azurill').
peso('poco','Bagon').
peso('poco','Baltoy').
peso('poco','Banette').
peso('poco','Barboach').
peso('poco','Basculin').
peso('poco','Bayleef').
peso('poco','Beautifly').
peso('poco','Beedrill').
peso('poco','Beheeyem').
peso('poco','Bellossom').
peso('poco','Bellsprout').
peso('poco','Bibarel').
peso('poco','Bidoof').
peso('poco','Binacle').
peso('poco','Blacephalon').
peso('poco','Blissey').
peso('poco','Blitzle').
peso('poco','Bonsly').
peso('poco','Braixen').
peso('poco','Braviary').
peso('poco','Breloom').
peso('poco','Budew').
peso('poco','Buizel').
peso('poco','Bulbasaur').
peso('poco','Buneary').
peso('poco','Bunnelby').
peso('poco','Burmy').
peso('poco','Butterfree').
peso('poco','Carbink').
peso('poco','Carnivine').
peso('poco','Carvanha').
peso('poco','Cascoon').
peso('poco','Castform').
peso('poco','Caterpie').
peso('poco','Celebi').
peso('poco','Chandelure').
peso('poco','Chansey').
peso('poco','Charmander').
peso('poco','Charmeleon').
peso('poco','Chatot').
peso('poco','Cherrim').
peso('poco','Cherubi').
peso('poco','Chespin').
peso('poco','Chikorita').
peso('poco','Chimchar').
peso('poco','Chimecho').
peso('poco','Chinchou').
peso('poco','Chingling').
peso('poco','Cinccino').
peso('poco','Clauncher').
peso('poco','Clawitzer').
peso('poco','Clefable').
peso('poco','Clefairy').
peso('poco','Cleffa').
peso('poco','Combee').
peso('poco','Combusken').
peso('poco','Corphish').
peso('poco','Corsola').
peso('poco','Cosmog').
peso('poco','Cottonee').
peso('poco','Cranidos').
peso('poco','Crawdaunt').
peso('poco','Croagunk').
peso('poco','Croconaw').
peso('poco','Cubchoo').
peso('poco','Cubone').
peso('poco','Cyndaquil').
peso('poco','Darumaka').
peso('poco','Dedenne').
peso('poco','Deerling').
peso('poco','Deino').
peso('poco','Deino').
peso('poco','Delcatty').
peso('poco','Delibird').
peso('poco','Delphox').
peso('poco','Dewott').
peso('poco','Diancie').
peso('poco','Diggersby').
peso('poco','Diglett').
peso('poco','Ditto').
peso('poco','Doduo').
peso('poco','Doublade').
peso('poco','Dragonair').
peso('poco','Dragonair').
peso('poco','Dratini').
peso('poco','Drifblim').
peso('poco','Drifloon').
peso('poco','Drilbur').
peso('poco','Drowzee').
peso('poco','Ducklett').
peso('poco','Dugtrio').
peso('poco','Dunsparce').
peso('poco','Duosion').
peso('poco','Durant').
peso('poco','Dusclops').
peso('poco','Duskull').
peso('poco','Dustox').
peso('poco','Dwebble').
peso('poco','Eelektrik').
peso('poco','Eevee').
peso('poco','Ekans').
peso('poco','Electabuzz').
peso('poco','Electrike').
peso('poco','Elekid').
peso('poco','Elgyem').
peso('poco','Emolga').
peso('poco','Escavalier').
peso('poco','Espeon').
peso('poco','Espurr').
peso('poco','Excadrill').
peso('poco','Exeggcute').
peso('poco','Farfetchd').
peso('poco','Fearow').
peso('poco','Feebas').
peso('poco','Fennekin').
peso('poco','Ferroseed').
peso('poco','Finneon').
peso('poco','Flaaffy').
peso('poco','Flabébé').
peso('poco','Flareon').
peso('poco','Fletchinder').
peso('poco','Fletchling').
peso('poco','Floatzel').
peso('poco','Floette').
peso('poco','Florges').
peso('poco','Foongus').
peso('poco','Fraxure').
peso('poco','Frillish').
peso('poco','Froakie').
peso('poco','Frogadier').
peso('poco','Froslass').
peso('poco','Furfrou').
peso('poco','Furret').
peso('poco','Galvantula').
peso('poco','Gardevoir').
peso('poco','Gastly').
peso('poco','Gastrodon').
peso('poco','Gengar').
peso('poco','Geodude').
peso('poco','Geodude-de-Alola').
peso('poco','Gible').
peso('poco','Girafarig').
peso('poco','Glaceon').
peso('poco','Glameow').
peso('poco','Gliscor').
peso('poco','Gloom').
peso('poco','Goldeen').
peso('poco','Goomy').
peso('poco','Gorebyss').
peso('poco','Gothita').
peso('poco','Gothitelle').
peso('poco','Gothorita').
peso('poco','Gourgeist').
peso('poco','Gourgeist').
peso('poco','Gourgeist').
peso('poco','Gourgeist').
peso('poco','Granbull').
peso('poco','Greninja').
peso('poco','Grimer').
peso('poco','Grimer-de-Alola').
peso('poco','Grovyle').
peso('poco','Growlithe').
peso('poco','Gulpin').
peso('poco','Gurdurr').
peso('poco','Happiny').
peso('poco','Haunter').
peso('poco','Hawlucha').
peso('poco','Heliolisk').
peso('poco','Helioptile').
peso('poco','Herdier').
peso('poco','Hippopotas').
peso('poco','Hitmonlee').
peso('poco','Hitmontop').
peso('poco','Honchkrow').
peso('poco','Hondour').
peso('poco','Honedge').
peso('poco','Hoopa').
peso('poco','Hoothoot').
peso('poco','Hoppip').
peso('poco','Horsea').
peso('poco','Houndoom').
peso('poco','Huntail').
peso('poco','Igglybuff').
peso('poco','Illumise').
peso('poco','Illumise').
peso('poco','Inkay').
peso('poco','Ivysaur').
peso('poco','Jigglypuff').
peso('poco','Jirachi').
peso('poco','Jolteon').
peso('poco','Joltik').
peso('poco','Jumpluff').
peso('poco','Jynx').
peso('poco','Kabuto').
peso('poco','Kabutops').
peso('poco','Kakuna').
peso('poco','Karrablast').
peso('poco','Kartana').
peso('poco','Kecleon').
peso('poco','Keldeo').
peso('poco','Keldeo-Resolete').
peso('poco','Kirlia').
peso('poco','Klefki').
peso('poco','Klink').
peso('poco','Koffing').
peso('poco','Krabby').
peso('poco','Kricketot').
peso('poco','Kricketune').
peso('poco','Krokorok').
peso('poco','Lampent').
peso('poco','Lanturn').
peso('poco','Larvesta').
peso('poco','Latias').
peso('poco','Leafeon').
peso('poco','Leavanny').
peso('poco','Ledian').
peso('poco','Ledyba').
peso('poco','Liepard').
peso('poco','Lileep').
peso('poco','Lilligant').
peso('poco','Lillipup').
peso('poco','Linoone').
peso('poco','Litleo').
peso('poco','Litten').
peso('poco','Litwick').
peso('poco','Lombre').
peso('poco','Lopunny').
peso('poco','Lotad').
peso('poco','Loudred').
peso('poco','Lumineon').
peso('poco','Luvdisc').
peso('poco','Luxio').
peso('poco','Luxray').
peso('poco','Lycanroc').
peso('poco','Machop').
peso('poco','Magby').
peso('poco','Magikarp').
peso('poco','Magmar').
peso('poco','Magnemite').
peso('poco','Malamar').
peso('poco','Manaphy').
peso('poco','Mandibuzz').
peso('poco','Manectric').
peso('poco','Mankey').
peso('poco','Maractus').
peso('poco','Mareep').
peso('poco','Marill').
peso('poco','Marowak').
peso('poco','Marowak-de-Alola').
peso('poco','Marshadow').
peso('poco','Marshtomp').
peso('poco','Masquerain').
peso('poco','Mawile').
peso('poco','Medicham').
peso('poco','Meditite').
peso('poco','Mega-Absol').
peso('poco','Mega-Alakazam').
peso('poco','Mega-Altaria').
peso('poco','Mega-Audino').
peso('poco','Mega-Bannete').
peso('poco','Mega-Beedrill').
peso('poco','Mega-Diancie').
peso('poco','Mega-Gengar').
peso('poco','Mega-Houndoom').
peso('poco','Mega-Lopunny').
peso('poco','Mega-Manectric').
peso('poco','Mega-Mawile').
peso('poco','Mega-Medicham').
peso('poco','Mega-Mewtwo-Y').
peso('poco','Meloetta').
peso('poco','Meloetta-Pirueta').
peso('poco','Meowstic').
peso('poco','Meowth').
peso('poco','Meowth-de-Alola').
peso('poco','Mesprit').
peso('poco','Metapod').
peso('poco','Mew').
peso('poco','Mienfoo').
peso('poco','Mienshao').
peso('poco','Mightyena').
peso('poco','Mime-Jr').
peso('poco','Minccino').
peso('poco','Minior').
peso('poco','Minior').
peso('poco','Minun').
peso('poco','Misdreavus').
peso('poco','Mismagius').
peso('poco','Monferno').
peso('poco','Mothim').
peso('poco','Mudkip').
peso('poco','Muk').
peso('poco','Munna').
peso('poco','Murkrow').
peso('poco','Natu').
peso('poco','Nidoran-F').
peso('poco','Nidoran-M').
peso('poco','Nidorina').
peso('poco','Nidorino').
peso('poco','Nincada').
peso('poco','Ninetales').
peso('poco','Ninetales-de-Alola').
peso('poco','Ninjask').
peso('poco','Noctowl').
peso('poco','Noibat').
peso('poco','Numel').
peso('poco','Nuzleaf').
peso('poco','Octillery').
peso('poco','Oddish').
peso('poco','Omanyte').
peso('poco','Omastar').
peso('poco','Oshawott').
peso('poco','Pachirisu').
peso('poco','Palpitoad').
peso('poco','Palpitoad').
peso('poco','Pancham').
peso('poco','Panpour').
peso('poco','Pansear').
peso('poco','Paras').
peso('poco','Parasect').
peso('poco','Pasange').
peso('poco','Patrat').
peso('poco','Pawniard').
peso('poco','Pelipper').
peso('poco','Persian').
peso('poco','Persian-de-Alola').
peso('poco','Petilil').
peso('poco','Phanpy').
peso('poco','Phantump').
peso('poco','Phione').
peso('poco','Pichu').
peso('poco','Pidgeot').
peso('poco','Pidgeotto').
peso('poco','Pidgey').
peso('poco','Pidove').
peso('poco','Pikachu').
peso('poco','Pineco').
peso('poco','Piplup').
peso('poco','Plusle').
peso('poco','Poipole').
peso('poco','Politoed').
peso('poco','Poliwag').
peso('poco','Poliwhirl').
peso('poco','Ponyta').
peso('poco','Poochyena').
peso('poco','Popplio').
peso('poco','Porygon').
peso('poco','Porygon-Z').
peso('poco','Porygon2').
peso('poco','Primeape').
peso('poco','Prinplup').
peso('poco','Psyduck').
peso('poco','Pumpkaboo').
peso('poco','Pumpkaboo').
peso('poco','Pumpkaboo').
peso('poco','Pumpkaboo').
peso('poco','Purrloin').
peso('poco','Purugly').
peso('poco','Quilava').
peso('poco','Quilladin').
peso('poco','Qwilfish').
peso('poco','Raichu').
peso('poco','Raichu-de-Alola').
peso('poco','Ralts').
peso('poco','Raticate').
peso('poco','Raticate-de-Alola').
peso('poco','Rattata').
peso('poco','Rattata-de-Alola').
peso('poco','Relicanth').
peso('poco','Remoraid').
peso('poco','Reuniclus').
peso('poco','Riolu').
peso('poco','Roggenrola').
peso('poco','Roselia').
peso('poco','Roserade').
peso('poco','Rotom').
peso('poco','Rotom-Calor').
peso('poco','Rotom-Lavado').
peso('poco','Rotom-Corte').
peso('poco','Rotom-Frio').
peso('poco','Rotom-Ventilador').
peso('poco','Rowlet').
peso('poco','Rufflet').
peso('poco','Sableye').
peso('poco','Sandile').
peso('poco','Sandshrew').
peso('poco','Sandshrew-de-Alola').
peso('poco','Sandslash').
peso('poco','Scatterbug').
peso('poco','Scrafty').
peso('poco','Scraggy').
peso('poco','Seadra').
peso('poco','Seaking').
peso('poco','Seedot').
peso('poco','Sentret').
peso('poco','Servine').
peso('poco','Sewaddle').
peso('poco','Shaymin').
peso('poco','Shaymin').
peso('poco','Shedinja').
peso('poco','Shellder').
peso('poco','Shellos').
peso('poco','Shelmet').
peso('poco','Shinx').
peso('poco','Shroomish').
peso('poco','Shuckle').
peso('poco','Shuppet').
peso('poco','Sigilyph').
peso('poco','Silcoon').
peso('poco','Simipour').
peso('poco','Simisage').
peso('poco','Simisear').
peso('poco','Skiddo').
peso('poco','Skiploom').
peso('poco','Skitty').
peso('poco','Skorupi').
peso('poco','Skrelp').
peso('poco','Skuntank').
peso('poco','Slakoth').
peso('poco','Sliggoo').
peso('poco','Sliggoo').
peso('poco','Slowpoke').
peso('poco','Slugma').
peso('poco','Slurpuff').
peso('poco','Smoochum').
peso('poco','Sneasel').
peso('poco','Snivy').
peso('poco','Snorunt').
peso('poco','Snorunt').
peso('poco','Snubbull').
peso('poco','Solosis').
peso('poco','Spearow').
peso('poco','Spewpa').
peso('poco','Spheal').
peso('poco','Spinarak').
peso('poco','Spinda').
peso('poco','Spoink').
peso('poco','Spritzee').
peso('poco','Squirtle').
peso('poco','Staraptor').
peso('poco','Staravia').
peso('poco','Starly').
peso('poco','Staryu').
peso('poco','Stunfisk').
peso('poco','Stunky').
peso('poco','Sudowoodo').
peso('poco','Sunflora').
peso('poco','Sunkern').
peso('poco','Surskit').
peso('poco','Swablu').
peso('poco','Swadloon').
peso('poco','Swanna').
peso('poco','Swellow').
peso('poco','Swinub').
peso('poco','Swirlix').
peso('poco','Swoobat').
peso('poco','Sylveon').
peso('poco','Taillow').
peso('poco','Talonflame').
peso('poco','Tangela').
peso('poco','Tapu-Bulu').
peso('poco','Tapu-Fini').
peso('poco','Tapu-Koko').
peso('poco','Tapu-Lele').
peso('poco','Teddiursa').
peso('poco','Tentacool').
peso('poco','Tepig').
peso('poco','Timburr').
peso('poco','Tirtouga').
peso('poco','Tirtouga').
peso('poco','Togedemaru').
peso('poco','Togekiss').
peso('poco','Togepi').
peso('poco','Togetic').
peso('poco','Torchic').
peso('poco','Totodile').
peso('poco','Toxicroak').
peso('poco','Tranquill').
peso('poco','Trapinch').
peso('poco','Treecko').
peso('poco','Trubbish').
peso('poco','Turtwig').
peso('poco','Tympole').
peso('poco','Tynamo').
peso('poco','Tyrogue').
peso('poco','Tyrunt').
peso('poco','Umbreon').
peso('poco','Unfezant').
peso('poco','Unown').
peso('poco','Uxie').
peso('poco','Vanillish').
peso('poco','Vanillite').
peso('poco','Vaporeon').
peso('poco','Venipede').
peso('poco','Venomoth').
peso('poco','Venonat').
peso('poco','Vespiquen').
peso('poco','Vibrava').
peso('poco','Victini').
peso('poco','Victreebel').
peso('poco','Vigoroth').
peso('poco','Vileplume').
peso('poco','Vivillon').
peso('poco','Vivillon').
peso('poco','Volbeat').
peso('poco','Volcarona').
peso('poco','Voltorb').
peso('poco','Vullaby').
peso('poco','Vulpix').
peso('poco','Vulpix-de-Alola').
peso('poco','Wartortle').
peso('poco','Watchog').
peso('poco','Weavile').
peso('poco','Weedle').
peso('poco','Weepinbell').
peso('poco','Weezing').
peso('poco','Whimsicott').
peso('poco','Whiscash').
peso('poco','Whismur').
peso('poco','Whismur').
peso('poco','Wigglytuff').
peso('poco','Wingull').
peso('poco','Wishiwashi').
peso('poco','Wobbuffet').
peso('poco','Woobat').
peso('poco','Wooper').
peso('poco','Wormadam').
peso('poco','Wurmple').
peso('poco','Wynaut').
peso('poco','Xatu').
peso('poco','Yamask').
peso('poco','Yanma').
peso('poco','Zangoose').
peso('poco','Zeraora').
peso('poco','Zigzagoon').
peso('poco','Zigzagoon').
peso('poco','Zorua').
peso('poco','Zubat').
peso('poco','Zweilous').
peso('poco','Zygarde').
peso('poco','Missingno').
peso('poco','Toxapex').