pokemon('Bulbasaur').
pokemon('Ivysaur').
pokemon('Venusaur').
pokemon('Charmander').
pokemon('Charmeleon').
pokemon('Charizard').
pokemon('Squirtle').
pokemon('Wartortle').
pokemon('Blastoise').
pokemon('Caterpie').
pokemon('Metapod').
pokemon('Butterfree').
pokemon('Weedle').
pokemon('Kakuna').
pokemon('Beedrill').
pokemon('Pidgey').
pokemon('Pidgeotto').
pokemon('Pidgeot').
pokemon('Rattata').
pokemon('Raticate').
pokemon('Spearow').
pokemon('Fearow').
pokemon('Ekans').
pokemon('Arbok').
pokemon('Pikachu').
pokemon('Raichu').
pokemon('Sandshrew').
pokemon('Sandslash').
pokemon('Nidoran-F').
pokemon('Nidorina').
pokemon('Nidoqueen').
pokemon('Nidoran-M').
pokemon('Nidorino').
pokemon('Nidoking').
pokemon('Clefairy').
pokemon('Clefable').
pokemon('Vulpix').
pokemon('Ninetales').
pokemon('Jigglypuff').
pokemon('Wigglytuff').
pokemon('Zubat').
pokemon('Golbat').
pokemon('Oddish').
pokemon('Gloom').
pokemon('Vileplume').
pokemon('Paras').
pokemon('Parasect').
pokemon('Venonat').
pokemon('Venomoth').
pokemon('Diglett').
pokemon('Dugtrio').
pokemon('Meowth').
pokemon('Persian').
pokemon('Psyduck').
pokemon('Golduck').
pokemon('Mankey').
pokemon('Primeape').
pokemon('Growlithe').
pokemon('Arcanine').
pokemon('Poliwag').
pokemon('Poliwhirl').
pokemon('Poliwrath').
pokemon('Abra').
pokemon('Kadabra').
pokemon('Alakazam').
pokemon('Machop').
pokemon('Machoke').
pokemon('Machamp').
pokemon('Bellsprout').
pokemon('Weepinbell').
pokemon('Victreebel').
pokemon('Tentacool').
pokemon('Tentacruel').
pokemon('Geodude').
pokemon('Graveler').
pokemon('Golem').
pokemon('Ponyta').
pokemon('Rapidash').
pokemon('Slowpoke').
pokemon('Slowbro').
pokemon('Magnemite').
pokemon('Magneton').
pokemon('Farfetchd').
pokemon('Doduo').
pokemon('Dodrio').
pokemon('Seel').
pokemon('Dewgong').
pokemon('Grimer').
pokemon('Muk').
pokemon('Shellder').
pokemon('Cloyster').
pokemon('Gastly').
pokemon('Haunter').
pokemon('Gengar').
pokemon('Onix').
pokemon('Drowzee').
pokemon('Hypno').
pokemon('Krabby').
pokemon('Kingler').
pokemon('Voltorb').
pokemon('Electrode').
pokemon('Exeggcute').
pokemon('Exeggutor').
pokemon('Cubone').
pokemon('Marowak').
pokemon('Hitmonlee').
pokemon('Hitmonchan').
pokemon('Lickitung').
pokemon('Koffing').
pokemon('Weezing').
pokemon('Rhyhorn').
pokemon('Rhydon').
pokemon('Chansey').
pokemon('Tangela').
pokemon('Kangaskhan').
pokemon('Horsea').
pokemon('Seadra').
pokemon('Goldeen').
pokemon('Seaking').
pokemon('Staryu').
pokemon('Starmie').
pokemon('Mr.Mime').
pokemon('Scyther').
pokemon('Jynx').
pokemon('Electabuzz').
pokemon('Magmar').
pokemon('Pinsir').
pokemon('Tauros').
pokemon('Magikarp').
pokemon('Gyarados').
pokemon('Lapras').
pokemon('Ditto').
pokemon('Eevee').
pokemon('Vaporeon').
pokemon('Jolteon').
pokemon('Flareon').
pokemon('Porygon').
pokemon('Omanyte').
pokemon('Omastar').
pokemon('Kabuto').
pokemon('Kabutops').
pokemon('Aerodactyl').
pokemon('Snorlax').
pokemon('Articuno').
pokemon('Zapdos').
pokemon('Moltres').
pokemon('Dratini').
pokemon('Dragonair').
pokemon('Dragonite').
pokemon('Mewtwo').
pokemon('Mew').
pokemon('Chikorita').
pokemon('Bayleef').
pokemon('Meganium').
pokemon('Cyndaquil').
pokemon('Quilava').
pokemon('Typhlosion').
pokemon('Totodile').
pokemon('Croconaw').
pokemon('Feraligatr').
pokemon('Sentret').
pokemon('Furret').
pokemon('Hoothoot').
pokemon('Noctowl').
pokemon('Ledyba').
pokemon('Ledian').
pokemon('Spinarak').
pokemon('Ariados').
pokemon('Crobat').
pokemon('Chinchou').
pokemon('Lanturn').
pokemon('Pichu').
pokemon('Cleffa').
pokemon('Igglybuff').
pokemon('Togepi').
pokemon('Togetic').
pokemon('Natu').
pokemon('Xatu').
pokemon('Mareep').
pokemon('Flaaffy').
pokemon('Ampharos').
pokemon('Bellossom').
pokemon('Marill').
pokemon('Azumarill').
pokemon('Sudowoodo').
pokemon('Politoed').
pokemon('Hoppip').
pokemon('Skiploom').
pokemon('Jumpluff').
pokemon('Aipom').
pokemon('Sunkern').
pokemon('Sunflora').
pokemon('Yanma').
pokemon('Wooper').
pokemon('Quagsire').
pokemon('Espeon').
pokemon('Umbreon').
pokemon('Murkrow').
pokemon('Slowking').
pokemon('Misdreavus').
pokemon('Unown').
pokemon('Wobbuffet').
pokemon('Girafarig').
pokemon('Pineco').
pokemon('Forretress').
pokemon('Dunsparce').
pokemon('Gligar').
pokemon('Steelix').
pokemon('Snubbull').
pokemon('Granbull').
pokemon('Qwilfish').
pokemon('Scizor').
pokemon('Shuckle').
pokemon('Heracross').
pokemon('Sneasel').
pokemon('Teddiursa').
pokemon('Ursaring').
pokemon('Slugma').
pokemon('Magcargo').
pokemon('Swinub').
pokemon('Piloswine').
pokemon('Corsola').
pokemon('Remoraid').
pokemon('Octillery').
pokemon('Delibird').
pokemon('Mantine').
pokemon('Skarmory').
pokemon('Houndour').
pokemon('Houndoom').
pokemon('Kingdra').
pokemon('Phanpy').
pokemon('Donphan').
pokemon('Porygon2').
pokemon('Stantler').
pokemon('Smeargle').
pokemon('Tyrogue').
pokemon('Hitmontop').
pokemon('Smoochum').
pokemon('Elekid').
pokemon('Magby').
pokemon('Miltank').
pokemon('Blissey').
pokemon('Raikou').
pokemon('Entei').
pokemon('Suicune').
pokemon('Larvitar').
pokemon('Pupitar').
pokemon('Tyranitar').
pokemon('Lugia').
pokemon('Ho-Oh').
pokemon('Celebi').
pokemon('Treecko').
pokemon('Grovyle').
pokemon('Sceptile').
pokemon('Torchic').
pokemon('Combusken').
pokemon('Blaziken').
pokemon('Mudkip').
pokemon('Marshtomp').
pokemon('Swampert').
pokemon('Poochyena').
pokemon('Mightyena').
pokemon('Zigzagoon').
pokemon('Linoone').
pokemon('Wurmple').
pokemon('Silcoon').
pokemon('Beautifly').
pokemon('Cascoon').
pokemon('Dustox').
pokemon('Lotad').
pokemon('Lombre').
pokemon('Ludicolo').
pokemon('Seedot').
pokemon('Nuzleaf').
pokemon('Shiftry').
pokemon('Taillow').
pokemon('Swellow').
pokemon('Wingull').
pokemon('Pelipper').
pokemon('Ralts').
pokemon('Kirlia').
pokemon('Gardevoir').
pokemon('Surskit').
pokemon('Masquerain').
pokemon('Shroomish').
pokemon('Breloom').
pokemon('Slakoth').
pokemon('Vigoroth').
pokemon('Slaking').
pokemon('Nincada').
pokemon('Ninjask').
pokemon('Shedinja').
pokemon('Whismur').
pokemon('Loudred').
pokemon('Exploud').
pokemon('Makuhita').
pokemon('Hariyama').
pokemon('Azurill').
pokemon('Nosepass').
pokemon('Skitty').
pokemon('Delcatty').
pokemon('Sableye').
pokemon('Mawile').
pokemon('Aron').
pokemon('Lairon').
pokemon('Aggron').
pokemon('Meditite').
pokemon('Medicham').
pokemon('Electrike').
pokemon('Manectric').
pokemon('Plusle').
pokemon('Minun').
pokemon('Volbeat').
pokemon('Illumise').
pokemon('Roselia').
pokemon('Gulpin').
pokemon('Swalot').
pokemon('Carvanha').
pokemon('Sharpedo').
pokemon('Wailmer').
pokemon('Wailord').
pokemon('Numel').
pokemon('Camerupt').
pokemon('Torkoal').
pokemon('Spoink').
pokemon('Grumpig').
pokemon('Spinda').
pokemon('Trapinch').
pokemon('Vibrava').
pokemon('Flygon').
pokemon('Cacnea').
pokemon('Cacturne').
pokemon('Swablu').
pokemon('Altaria').
pokemon('Zangoose').
pokemon('Seviper').
pokemon('Lunatone').
pokemon('Solrock').
pokemon('Barboach').
pokemon('Whiscash').
pokemon('Corphish').
pokemon('Crawdaunt').
pokemon('Baltoy').
pokemon('Claydol').
pokemon('Lileep').
pokemon('Cradily').
pokemon('Anorith').
pokemon('Armaldo').
pokemon('Feebas').
pokemon('Milotic').
pokemon('Castform').
pokemon('Kecleon').
pokemon('Shuppet').
pokemon('Banette').
pokemon('Duskull').
pokemon('Dusclops').
pokemon('Tropius').
pokemon('Chimecho').
pokemon('Absol').
pokemon('Wynaut').
pokemon('Snorunt').
pokemon('Glalie').
pokemon('Spheal').
pokemon('Sealeo').
pokemon('Walrein').
pokemon('Clamperl').
pokemon('Huntail').
pokemon('Gorebyss').
pokemon('Relicanth').
pokemon('Luvdisc').
pokemon('Bagon').
pokemon('Shelgon').
pokemon('Salamence').
pokemon('Beldum').
pokemon('Metang').
pokemon('Metagross').
pokemon('Regirock').
pokemon('Regice').
pokemon('Registeel').
pokemon('Latias').
pokemon('Latios').
pokemon('Kyogre').
pokemon('Groudon').
pokemon('Rayquaza').
pokemon('Jirachi').
pokemon('Deoxys').
pokemon('Turtwig').
pokemon('Grotle').
pokemon('Torterra').
pokemon('Chimchar').
pokemon('Monferno').
pokemon('Infernape').
pokemon('Piplup').
pokemon('Prinplup').
pokemon('Empoleon').
pokemon('Starly').
pokemon('Staravia').
pokemon('Staraptor').
pokemon('Bidoof').
pokemon('Bibarel').
pokemon('Kricketot').
pokemon('Kricketune').
pokemon('Shinx').
pokemon('Luxio').
pokemon('Luxray').
pokemon('Budew').
pokemon('Roserade').
pokemon('Cranidos').
pokemon('Rampardos').
pokemon('Shieldon').
pokemon('Bastiodon').
pokemon('Burmy').
pokemon('Wormadam').
pokemon('Mothim').
pokemon('Combee').
pokemon('Vespiquen').
pokemon('Pachirisu').
pokemon('Buizel').
pokemon('Floatzel').
pokemon('Cherubi').
pokemon('Cherrim').
pokemon('Shellos').
pokemon('Gastrodon').
pokemon('Ambipom').
pokemon('Drifloon').
pokemon('Drifblim').
pokemon('Buneary').
pokemon('Lopunny').
pokemon('Mismagius').
pokemon('Honchkrow').
pokemon('Glameow').
pokemon('Purugly').
pokemon('Chingling').
pokemon('Stunky').
pokemon('Skuntank').
pokemon('Bronzor').
pokemon('Bronzong').
pokemon('Bonsly').
pokemon('Mime-Jr.').
pokemon('Happiny').
pokemon('Chatot').
pokemon('Spiritomb').
pokemon('Gible').
pokemon('Gabite').
pokemon('Garchomp').
pokemon('Munchlax').
pokemon('Riolu').
pokemon('Lucario').
pokemon('Hippopotas').
pokemon('Hippowdon').
pokemon('Skorupi').
pokemon('Drapion').
pokemon('Croagunk').
pokemon('Toxicroak').
pokemon('Carnivine').
pokemon('Finneon').
pokemon('Lumineon').
pokemon('Mantyke').
pokemon('Snover').
pokemon('Abomasnow').
pokemon('Weavile').
pokemon('Magnezone').
pokemon('Lickilicky').
pokemon('Rhyperior').
pokemon('Tangrowth').
pokemon('Electivire').
pokemon('Magmortar').
pokemon('Togekiss').
pokemon('Yanmega').
pokemon('Leafeon').
pokemon('Glaceon').
pokemon('Gliscor').
pokemon('Mamoswine').
pokemon('Porygon-Z').
pokemon('Gallade').
pokemon('Probopass').
pokemon('Dusknoir').
pokemon('Froslass').
pokemon('Rotom').
pokemon('Uxie').
pokemon('Mesprit').
pokemon('Azelf').
pokemon('Dialga').
pokemon('Palkia').
pokemon('Heatran').
pokemon('Regigigas').
pokemon('Giratina').
pokemon('Cresselia').
pokemon('Phione').
pokemon('Manaphy').
pokemon('Darkrai').
pokemon('Shaymin').
pokemon('Arceus').
pokemon('Victini').
pokemon('Snivy').
pokemon('Servine').
pokemon('Serperior').
pokemon('Tepig').
pokemon('Pignite').
pokemon('Emboar').
pokemon('Oshawott').
pokemon('Dewott').
pokemon('Samurott').
pokemon('Patrat').
pokemon('Watchog').
pokemon('Lillipup').
pokemon('Herdier').
pokemon('Stoutland').
pokemon('Purrloin').
pokemon('Liepard').
pokemon('Pansage').
pokemon('Simisage').
pokemon('Pansear').
pokemon('Simisear').
pokemon('Panpour').
pokemon('Simipour').
pokemon('Munna').
pokemon('Musharna').
pokemon('Pidove').
pokemon('Tranquill').
pokemon('Unfezant').
pokemon('Blitzle').
pokemon('Zebstrika').
pokemon('Roggenrola').
pokemon('Boldore').
pokemon('Gigalith').
pokemon('Woobat').
pokemon('Swoobat').
pokemon('Drilbur').
pokemon('Excadrill').
pokemon('Audino').
pokemon('Timburr').
pokemon('Gurdurr').
pokemon('Conkeldurr').
pokemon('Tympole').
pokemon('Palpitoad').
pokemon('Seismitoad').
pokemon('Throh').
pokemon('Sawk').
pokemon('Sewaddle').
pokemon('Swadloon').
pokemon('Leavanny').
pokemon('Venipede').
pokemon('Whirlipede').
pokemon('Scolipede').
pokemon('Cottonee').
pokemon('Whimsicott').
pokemon('Petilil').
pokemon('Lilligant').
pokemon('Basculin').
pokemon('Sandile').
pokemon('Krokorok').
pokemon('Krookodile').
pokemon('Darumaka').
pokemon('Darmanitan').
pokemon('Maractus').
pokemon('Dwebble').
pokemon('Crustle').
pokemon('Scraggy').
pokemon('Scrafty').
pokemon('Sigilyph').
pokemon('Yamask').
pokemon('Cofagrigus').
pokemon('Tirtouga').
pokemon('Carracosta').
pokemon('Archen').
pokemon('Archeops').
pokemon('Trubbish').
pokemon('Garbodor').
pokemon('Zorua').
pokemon('Zoroark').
pokemon('Minccino').
pokemon('Cinccino').
pokemon('Gothita').
pokemon('Gothorita').
pokemon('Gothitelle').
pokemon('Solosis').
pokemon('Duosion').
pokemon('Reuniclus').
pokemon('Ducklett').
pokemon('Swanna').
pokemon('Vanillite').
pokemon('Vanillish').
pokemon('Vanilluxe').
pokemon('Deerling').
pokemon('Sawsbuck').
pokemon('Emolga').
pokemon('Karrablast').
pokemon('Escavalier').
pokemon('Foongus').
pokemon('Amoonguss').
pokemon('Frillish').
pokemon('Jellicent').
pokemon('Alomomola').
pokemon('Joltik').
pokemon('Galvantula').
pokemon('Ferroseed').
pokemon('Ferrothorn').
pokemon('Klink').
pokemon('Klang').
pokemon('Klinklang').
pokemon('Tynamo').
pokemon('Eelektrik').
pokemon('Eelektross').
pokemon('Elgyem').
pokemon('Beheeyem').
pokemon('Litwick').
pokemon('Lampent').
pokemon('Chandelure').
pokemon('Axew').
pokemon('Fraxure').
pokemon('Haxorus').
pokemon('Cubchoo').
pokemon('Beartic').
pokemon('Cryogonal').
pokemon('Shelmet').
pokemon('Accelgor').
pokemon('Stunfisk').
pokemon('Mienfoo').
pokemon('Mienshao').
pokemon('Druddigon').
pokemon('Golett').
pokemon('Golurk').
pokemon('Pawniard').
pokemon('Bisharp').
pokemon('Bouffalant').
pokemon('Rufflet').
pokemon('Braviary').
pokemon('Vullaby').
pokemon('Mandibuzz').
pokemon('Heatmor').
pokemon('Durant').
pokemon('Deino').
pokemon('Zweilous').
pokemon('Hydreigon').
pokemon('Larvesta').
pokemon('Volcarona').
pokemon('Cobalion').
pokemon('Terrakion').
pokemon('Virizion').
pokemon('Tornadus').
pokemon('Thundurus').
pokemon('Reshiram').
pokemon('Zekrom').
pokemon('Landorus').
pokemon('Kyurem').
pokemon('Keldeo').
pokemon('Meloetta').
pokemon('Genesect').
pokemon('Chespin').
pokemon('Quilladin').
pokemon('Chesnaught').
pokemon('Fennekin').
pokemon('Braixen').
pokemon('Delphox').
pokemon('Froakie').
pokemon('Frogadier').
pokemon('Greninja').
pokemon('Bunnelby').
pokemon('Diggersby').
pokemon('Fletchling').
pokemon('Fletchinder').
pokemon('Talonflame').
pokemon('Scatterbug').
pokemon('Spewpa').
pokemon('Vivillon').
pokemon('Litleo').
pokemon('Pyroar').
pokemon('Flabébé').
pokemon('Floette').
pokemon('Florges').
pokemon('Skiddo').
pokemon('Gogoat').
pokemon('Pancham').
pokemon('Pangoro').
pokemon('Furfrou').
pokemon('Espurr').
pokemon('Meowstic').
pokemon('Honedge').
pokemon('Doublade').
pokemon('Aegislash').
pokemon('Spritzee').
pokemon('Aromatisse').
pokemon('Swirlix').
pokemon('Slurpuff').
pokemon('Inkay').
pokemon('Malamar').
pokemon('Binacle').
pokemon('Barbaracle').
pokemon('Skrelp').
pokemon('Dragalge').
pokemon('Clauncher').
pokemon('Clawitzer').
pokemon('Helioptile').
pokemon('Heliolisk').
pokemon('Tyrunt').
pokemon('Tyrantrum').
pokemon('Amaura').
pokemon('Aurorus').
pokemon('Sylveon').
pokemon('Hawlucha').
pokemon('Dedenne').
pokemon('Carbink').
pokemon('Goomy').
pokemon('Sliggoo').
pokemon('Goodra').
pokemon('Klefki').
pokemon('Phantump').
pokemon('Trevenant').
pokemon('Pumpkaboo').
pokemon('Gourgeist').
pokemon('Bergmite').
pokemon('Avalugg').
pokemon('Noibat').
pokemon('Noivern').
pokemon('Xerneas').
pokemon('Yveltal').
pokemon('Zygarde').
pokemon('Diancie').
pokemon('Hoopa').
pokemon('Volcanion').
pokemon('Rowlet').
pokemon('Dartrix').
pokemon('Decidueye').
pokemon('Litten').
pokemon('Torracat').
pokemon('Incineroar').
pokemon('Popplio').
pokemon('Brionne').
pokemon('Primarina').
pokemon('Pikipek').
pokemon('Trumbeak').
pokemon('Toucannon').
pokemon('Yungoos').
pokemon('Gumshoos').
pokemon('Grubbin').
pokemon('Charjabug').
pokemon('Vikavolt').
pokemon('Crabrawler').
pokemon('Crabominable').
pokemon('Oricorio').
pokemon('Cutiefly').
pokemon('Ribombee').
pokemon('Rockruff').
pokemon('Lycanroc').
pokemon('Wishiwashi').
pokemon('Mareanie').
pokemon('Toxapex').
pokemon('Mudbray').
pokemon('Mudsdale').
pokemon('Dewpider').
pokemon('Araquanid').
pokemon('Fomantis').
pokemon('Lurantis').
pokemon('Morelull').
pokemon('Shiinotic').
pokemon('Salandit').
pokemon('Salazzle').
pokemon('Stufful').
pokemon('Bewear').
pokemon('Bounsweet').
pokemon('Steenee').
pokemon('Tsareena').
pokemon('Comfey').
pokemon('Oranguru').
pokemon('Passimian').
pokemon('Wimpod').
pokemon('Golisopod').
pokemon('Sandygast').
pokemon('Palossand').
pokemon('Pyukumuku').
pokemon('Type:Null').
pokemon('Silvally').
pokemon('Minior').
pokemon('Komala').
pokemon('Turtonator').
pokemon('Togedemaru').
pokemon('Mimikyu').
pokemon('Bruxish').
pokemon('Drampa').
pokemon('Dhelmise').
pokemon('Jangmo-o').
pokemon('Hakamo-o').
pokemon('Kommo-o').
pokemon('Tapu-Koko').
pokemon('Tapu-Lele').
pokemon('Tapu-Bulu').
pokemon('Tapu-Fini').
pokemon('Cosmog').
pokemon('Cosmoem').
pokemon('Solgaleo').
pokemon('Lunala').
pokemon('Nihilego').
pokemon('Buzzwole').
pokemon('Pheromosa').
pokemon('Xurkitree').
pokemon('Celesteela').
pokemon('Kartana').
pokemon('Guzzlord').
pokemon('Necrozma').
pokemon('Magearna').
pokemon('Marshadow').
pokemon('Poipole').
pokemon('Naganadel').
pokemon('Stakataka').
pokemon('Blacephalon').
pokemon('Zeraora').
pokemon('Meltan').
pokemon('Melmetal').
pokemon('Missingno').