region('Kanto','Bulbasaur').
region('Kanto','Ivysaur').
region('Kanto','Venusaur').
region('Kanto','Charmander').
region('Kanto','Charmeleon').
region('Kanto','Charizard').
region('Kanto','Squirtle').
region('Kanto','Wartortle').
region('Kanto','Blastoise').
region('Kanto','Caterpie').
region('Kanto','Metapod').
region('Kanto','Butterfree').
region('Kanto','Weedle').
region('Kanto','Kakuna').
region('Kanto','Beedrill').
region('Kanto','Pidgey').
region('Kanto','Pidgeotto').
region('Kanto','Pidgeot').
region('Kanto','Rattata').
region('Kanto','Raticate').
region('Kanto','Spearow').
region('Kanto','Fearow').
region('Kanto','Ekans').
region('Kanto','Arbok').
region('Kanto','Pikachu').
region('Kanto','Raichu').
region('Kanto','Sandshrew').
region('Kanto','Sandslash').
region('Kanto','Nidoran-F').
region('Kanto','Nidorina').
region('Kanto','Nidoqueen').
region('Kanto','Nidoran-M').
region('Kanto','Nidorino').
region('Kanto','Nidoking').
region('Kanto','Clefairy').
region('Kanto','Clefable').
region('Kanto','Vulpix').
region('Kanto','Ninetales').
region('Kanto','Jigglypuff').
region('Kanto','Wigglytuff').
region('Kanto','Zubat').
region('Kanto','Golbat').
region('Kanto','Oddish').
region('Kanto','Gloom').
region('Kanto','Vileplume').
region('Kanto','Paras').
region('Kanto','Parasect').
region('Kanto','Venonat').
region('Kanto','Venomoth').
region('Kanto','Diglett').
region('Kanto','Dugtrio').
region('Kanto','Meowth').
region('Kanto','Persian').
region('Kanto','Psyduck').
region('Kanto','Golduck').
region('Kanto','Mankey').
region('Kanto','Primeape').
region('Kanto','Growlithe').
region('Kanto','Arcanine').
region('Kanto','Poliwag').
region('Kanto','Poliwhirl').
region('Kanto','Poliwrath').
region('Kanto','Abra').
region('Kanto','Kadabra').
region('Kanto','Alakazam').
region('Kanto','Machop').
region('Kanto','Machoke').
region('Kanto','Machamp').
region('Kanto','Bellsprout').
region('Kanto','Weepinbell').
region('Kanto','Victreebel').
region('Kanto','Tentacool').
region('Kanto','Tentacruel').
region('Kanto','Geodude').
region('Kanto','Graveler').
region('Kanto','Golem').
region('Kanto','Ponyta').
region('Kanto','Rapidash').
region('Kanto','Slowpoke').
region('Kanto','Slowbro').
region('Kanto','Magnemite').
region('Kanto','Magneton').
region('Kanto','Farfetchd').
region('Kanto','Doduo').
region('Kanto','Dodrio').
region('Kanto','Seel').
region('Kanto','Dewgong').
region('Kanto','Grimer').
region('Kanto','Muk').
region('Kanto','Shellder').
region('Kanto','Cloyster').
region('Kanto','Gastly').
region('Kanto','Haunter').
region('Kanto','Gengar').
region('Kanto','Onix').
region('Kanto','Drowzee').
region('Kanto','Hypno').
region('Kanto','Krabby').
region('Kanto','Kingler').
region('Kanto','Voltorb').
region('Kanto','Electrode').
region('Kanto','Exeggcute').
region('Kanto','Exeggutor').
region('Kanto','Cubone').
region('Kanto','Marowak').
region('Kanto','Hitmonlee').
region('Kanto','Hitmonchan').
region('Kanto','Lickitung').
region('Kanto','Koffing').
region('Kanto','Weezing').
region('Kanto','Rhyhorn').
region('Kanto','Rhydon').
region('Kanto','Chansey').
region('Kanto','Tangela').
region('Kanto','Kangaskhan').
region('Kanto','Horsea').
region('Kanto','Seadra').
region('Kanto','Goldeen').
region('Kanto','Seaking').
region('Kanto','Staryu').
region('Kanto','Starmie').
region('Kanto','Mr.Mime').
region('Kanto','Scyther').
region('Kanto','Jynx').
region('Kanto','Electabuzz').
region('Kanto','Magmar').
region('Kanto','Pinsir').
region('Kanto','Tauros').
region('Kanto','Magikarp').
region('Kanto','Gyarados').
region('Kanto','Lapras').
region('Kanto','Ditto').
region('Kanto','Eevee').
region('Kanto','Vaporeon').
region('Kanto','Jolteon').
region('Kanto','Flareon').
region('Kanto','Porygon').
region('Kanto','Omanyte').
region('Kanto','Omastar').
region('Kanto','Kabuto').
region('Kanto','Kabutops').
region('Kanto','Aerodactyl').
region('Kanto','Snorlax').
region('Kanto','Articuno').
region('Kanto','Zapdos').
region('Kanto','Moltres').
region('Kanto','Dratini').
region('Kanto','Dragonair').
region('Kanto','Dragonite').
region('Kanto','Mewtwo').
region('Kanto','Mew').
region('Johto','Chikorita').
region('Johto','Bayleef').
region('Johto','Meganium').
region('Johto','Cyndaquil').
region('Johto','Quilava').
region('Johto','Typhlosion').
region('Johto','Totodile').
region('Johto','Croconaw').
region('Johto','Feraligatr').
region('Johto','Sentret').
region('Johto','Furret').
region('Johto','Hoothoot').
region('Johto','Noctowl').
region('Johto','Ledyba').
region('Johto','Ledian').
region('Johto','Spinarak').
region('Johto','Ariados').
region('Johto','Crobat').
region('Johto','Chinchou').
region('Johto','Lanturn').
region('Johto','Pichu').
region('Johto','Cleffa').
region('Johto','Igglybuff').
region('Johto','Togepi').
region('Johto','Togetic').
region('Johto','Natu').
region('Johto','Xatu').
region('Johto','Mareep').
region('Johto','Flaaffy').
region('Johto','Ampharos').
region('Johto','Bellossom').
region('Johto','Marill').
region('Johto','Azumarill').
region('Johto','Sudowoodo').
region('Johto','Politoed').
region('Johto','Hoppip').
region('Johto','Skiploom').
region('Johto','Jumpluff').
region('Johto','Aipom').
region('Johto','Sunkern').
region('Johto','Sunflora').
region('Johto','Yanma').
region('Johto','Wooper').
region('Johto','Quagsire').
region('Johto','Espeon').
region('Johto','Umbreon').
region('Johto','Murkrow').
region('Johto','Slowking').
region('Johto','Misdreavus').
region('Johto','Unown').
region('Johto','Wobbuffet').
region('Johto','Girafarig').
region('Johto','Pineco').
region('Johto','Forretress').
region('Johto','Dunsparce').
region('Johto','Gligar').
region('Johto','Steelix').
region('Johto','Snubbull').
region('Johto','Granbull').
region('Johto','Qwilfish').
region('Johto','Scizor').
region('Johto','Shuckle').
region('Johto','Heracross').
region('Johto','Sneasel').
region('Johto','Teddiursa').
region('Johto','Ursaring').
region('Johto','Slugma').
region('Johto','Magcargo').
region('Johto','Swinub').
region('Johto','Piloswine').
region('Johto','Corsola').
region('Johto','Remoraid').
region('Johto','Octillery').
region('Johto','Delibird').
region('Johto','Mantine').
region('Johto','Skarmory').
region('Johto','Houndour').
region('Johto','Houndoom').
region('Johto','Kingdra').
region('Johto','Phanpy').
region('Johto','Donphan').
region('Johto','Porygon2').
region('Johto','Stantler').
region('Johto','Smeargle').
region('Johto','Tyrogue').
region('Johto','Hitmontop').
region('Johto','Smoochum').
region('Johto','Elekid').
region('Johto','Magby').
region('Johto','Miltank').
region('Johto','Blissey').
region('Johto','Raikou').
region('Johto','Entei').
region('Johto','Suicune').
region('Johto','Larvitar').
region('Johto','Pupitar').
region('Johto','Tyranitar').
region('Johto','Lugia').
region('Johto','Ho-Oh').
region('Johto','Celebi').
region('Hoenn','Treecko').
region('Hoenn','Grovyle').
region('Hoenn','Sceptile').
region('Hoenn','Torchic').
region('Hoenn','Combusken').
region('Hoenn','Blaziken').
region('Hoenn','Mudkip').
region('Hoenn','Marshtomp').
region('Hoenn','Swampert').
region('Hoenn','Poochyena').
region('Hoenn','Mightyena').
region('Hoenn','Zigzagoon').
region('Hoenn','Linoone').
region('Hoenn','Wurmple').
region('Hoenn','Silcoon').
region('Hoenn','Beautifly').
region('Hoenn','Cascoon').
region('Hoenn','Dustox').
region('Hoenn','Lotad').
region('Hoenn','Lombre').
region('Hoenn','Ludicolo').
region('Hoenn','Seedot').
region('Hoenn','Nuzleaf').
region('Hoenn','Shiftry').
region('Hoenn','Taillow').
region('Hoenn','Swellow').
region('Hoenn','Wingull').
region('Hoenn','Pelipper').
region('Hoenn','Ralts').
region('Hoenn','Kirlia').
region('Hoenn','Gardevoir').
region('Hoenn','Surskit').
region('Hoenn','Masquerain').
region('Hoenn','Shroomish').
region('Hoenn','Breloom').
region('Hoenn','Slakoth').
region('Hoenn','Vigoroth').
region('Hoenn','Slaking').
region('Hoenn','Nincada').
region('Hoenn','Ninjask').
region('Hoenn','Shedinja').
region('Hoenn','Whismur').
region('Hoenn','Loudred').
region('Hoenn','Exploud').
region('Hoenn','Makuhita').
region('Hoenn','Hariyama').
region('Hoenn','Azurill').
region('Hoenn','Nosepass').
region('Hoenn','Skitty').
region('Hoenn','Delcatty').
region('Hoenn','Sableye').
region('Hoenn','Mawile').
region('Hoenn','Aron').
region('Hoenn','Lairon').
region('Hoenn','Aggron').
region('Hoenn','Meditite').
region('Hoenn','Medicham').
region('Hoenn','Electrike').
region('Hoenn','Manectric').
region('Hoenn','Plusle').
region('Hoenn','Minun').
region('Hoenn','Volbeat').
region('Hoenn','Illumise').
region('Hoenn','Roselia').
region('Hoenn','Gulpin').
region('Hoenn','Swalot').
region('Hoenn','Carvanha').
region('Hoenn','Sharpedo').
region('Hoenn','Wailmer').
region('Hoenn','Wailord').
region('Hoenn','Numel').
region('Hoenn','Camerupt').
region('Hoenn','Torkoal').
region('Hoenn','Spoink').
region('Hoenn','Grumpig').
region('Hoenn','Spinda').
region('Hoenn','Trapinch').
region('Hoenn','Vibrava').
region('Hoenn','Flygon').
region('Hoenn','Cacnea').
region('Hoenn','Cacturne').
region('Hoenn','Swablu').
region('Hoenn','Altaria').
region('Hoenn','Zangoose').
region('Hoenn','Seviper').
region('Hoenn','Lunatone').
region('Hoenn','Solrock').
region('Hoenn','Barboach').
region('Hoenn','Whiscash').
region('Hoenn','Corphish').
region('Hoenn','Crawdaunt').
region('Hoenn','Baltoy').
region('Hoenn','Claydol').
region('Hoenn','Lileep').
region('Hoenn','Cradily').
region('Hoenn','Anorith').
region('Hoenn','Armaldo').
region('Hoenn','Feebas').
region('Hoenn','Milotic').
region('Hoenn','Castform').
region('Hoenn','Kecleon').
region('Hoenn','Shuppet').
region('Hoenn','Banette').
region('Hoenn','Duskull').
region('Hoenn','Dusclops').
region('Hoenn','Tropius').
region('Hoenn','Chimecho').
region('Hoenn','Absol').
region('Hoenn','Wynaut').
region('Hoenn','Snorunt').
region('Hoenn','Glalie').
region('Hoenn','Spheal').
region('Hoenn','Sealeo').
region('Hoenn','Walrein').
region('Hoenn','Clamperl').
region('Hoenn','Huntail').
region('Hoenn','Gorebyss').
region('Hoenn','Relicanth').
region('Hoenn','Luvdisc').
region('Hoenn','Bagon').
region('Hoenn','Shelgon').
region('Hoenn','Salamence').
region('Hoenn','Beldum').
region('Hoenn','Metang').
region('Hoenn','Metagross').
region('Hoenn','Regirock').
region('Hoenn','Regice').
region('Hoenn','Registeel').
region('Hoenn','Latias').
region('Hoenn','Latios').
region('Hoenn','Kyogre').
region('Hoenn','Groudon').
region('Hoenn','Rayquaza').
region('Hoenn','Jirachi').
region('Hoenn','Deoxys').
region('Sinnoh','Turtwig').
region('Sinnoh','Grotle').
region('Sinnoh','Torterra').
region('Sinnoh','Chimchar').
region('Sinnoh','Monferno').
region('Sinnoh','Infernape').
region('Sinnoh','Piplup').
region('Sinnoh','Prinplup').
region('Sinnoh','Empoleon').
region('Sinnoh','Starly').
region('Sinnoh','Staravia').
region('Sinnoh','Staraptor').
region('Sinnoh','Bidoof').
region('Sinnoh','Bibarel').
region('Sinnoh','Kricketot').
region('Sinnoh','Kricketune').
region('Sinnoh','Shinx').
region('Sinnoh','Luxio').
region('Sinnoh','Luxray').
region('Sinnoh','Budew').
region('Sinnoh','Roserade').
region('Sinnoh','Cranidos').
region('Sinnoh','Rampardos').
region('Sinnoh','Shieldon').
region('Sinnoh','Bastiodon').
region('Sinnoh','Burmy').
region('Sinnoh','Wormadam').
region('Sinnoh','Mothim').
region('Sinnoh','Combee').
region('Sinnoh','Vespiquen').
region('Sinnoh','Pachirisu').
region('Sinnoh','Buizel').
region('Sinnoh','Floatzel').
region('Sinnoh','Cherubi').
region('Sinnoh','Cherrim').
region('Sinnoh','Shellos').
region('Sinnoh','Gastrodon').
region('Sinnoh','Ambipom').
region('Sinnoh','Drifloon').
region('Sinnoh','Drifblim').
region('Sinnoh','Buneary').
region('Sinnoh','Lopunny').
region('Sinnoh','Mismagius').
region('Sinnoh','Honchkrow').
region('Sinnoh','Glameow').
region('Sinnoh','Purugly').
region('Sinnoh','Chingling').
region('Sinnoh','Stunky').
region('Sinnoh','Skuntank').
region('Sinnoh','Bronzor').
region('Sinnoh','Bronzong').
region('Sinnoh','Bonsly').
region('Sinnoh','Mime-Jr.').
region('Sinnoh','Happiny').
region('Sinnoh','Chatot').
region('Sinnoh','Spiritomb').
region('Sinnoh','Gible').
region('Sinnoh','Gabite').
region('Sinnoh','Garchomp').
region('Sinnoh','Munchlax').
region('Sinnoh','Riolu').
region('Sinnoh','Lucario').
region('Sinnoh','Hippopotas').
region('Sinnoh','Hippowdon').
region('Sinnoh','Skorupi').
region('Sinnoh','Drapion').
region('Sinnoh','Croagunk').
region('Sinnoh','Toxicroak').
region('Sinnoh','Carnivine').
region('Sinnoh','Finneon').
region('Sinnoh','Lumineon').
region('Sinnoh','Mantyke').
region('Sinnoh','Snover').
region('Sinnoh','Abomasnow').
region('Sinnoh','Weavile').
region('Sinnoh','Magnezone').
region('Sinnoh','Lickilicky').
region('Sinnoh','Rhyperior').
region('Sinnoh','Tangrowth').
region('Sinnoh','Electivire').
region('Sinnoh','Magmortar').
region('Sinnoh','Togekiss').
region('Sinnoh','Yanmega').
region('Sinnoh','Leafeon').
region('Sinnoh','Glaceon').
region('Sinnoh','Gliscor').
region('Sinnoh','Mamoswine').
region('Sinnoh','Porygon-Z').
region('Sinnoh','Gallade').
region('Sinnoh','Probopass').
region('Sinnoh','Dusknoir').
region('Sinnoh','Froslass').
region('Sinnoh','Rotom').
region('Sinnoh','Uxie').
region('Sinnoh','Mesprit').
region('Sinnoh','Azelf').
region('Sinnoh','Dialga').
region('Sinnoh','Palkia').
region('Sinnoh','Heatran').
region('Sinnoh','Regigigas').
region('Sinnoh','Giratina').
region('Sinnoh','Cresselia').
region('Sinnoh','Phione').
region('Sinnoh','Manaphy').
region('Sinnoh','Darkrai').
region('Sinnoh','Shaymin').
region('Sinnoh','Arceus').
region('Unova','Victini').
region('Unova','Snivy').
region('Unova','Servine').
region('Unova','Serperior').
region('Unova','Tepig').
region('Unova','Pignite').
region('Unova','Emboar').
region('Unova','Oshawott').
region('Unova','Dewott').
region('Unova','Samurott').
region('Unova','Patrat').
region('Unova','Watchog').
region('Unova','Lillipup').
region('Unova','Herdier').
region('Unova','Stoutland').
region('Unova','Purrloin').
region('Unova','Liepard').
region('Unova','Pansage').
region('Unova','Simisage').
region('Unova','Pansear').
region('Unova','Simisear').
region('Unova','Panpour').
region('Unova','Simipour').
region('Unova','Munna').
region('Unova','Musharna').
region('Unova','Pidove').
region('Unova','Tranquill').
region('Unova','Unfezant').
region('Unova','Blitzle').
region('Unova','Zebstrika').
region('Unova','Roggenrola').
region('Unova','Boldore').
region('Unova','Gigalith').
region('Unova','Woobat').
region('Unova','Swoobat').
region('Unova','Drilbur').
region('Unova','Excadrill').
region('Unova','Audino').
region('Unova','Timburr').
region('Unova','Gurdurr').
region('Unova','Conkeldurr').
region('Unova','Tympole').
region('Unova','Palpitoad').
region('Unova','Seismitoad').
region('Unova','Throh').
region('Unova','Sawk').
region('Unova','Sewaddle').
region('Unova','Swadloon').
region('Unova','Leavanny').
region('Unova','Venipede').
region('Unova','Whirlipede').
region('Unova','Scolipede').
region('Unova','Cottonee').
region('Unova','Whimsicott').
region('Unova','Petilil').
region('Unova','Lilligant').
region('Unova','Basculin').
region('Unova','Sandile').
region('Unova','Krokorok').
region('Unova','Krookodile').
region('Unova','Darumaka').
region('Unova','Darmanitan').
region('Unova','Maractus').
region('Unova','Dwebble').
region('Unova','Crustle').
region('Unova','Scraggy').
region('Unova','Scrafty').
region('Unova','Sigilyph').
region('Unova','Yamask').
region('Unova','Cofagrigus').
region('Unova','Tirtouga').
region('Unova','Carracosta').
region('Unova','Archen').
region('Unova','Archeops').
region('Unova','Trubbish').
region('Unova','Garbodor').
region('Unova','Zorua').
region('Unova','Zoroark').
region('Unova','Minccino').
region('Unova','Cinccino').
region('Unova','Gothita').
region('Unova','Gothorita').
region('Unova','Gothitelle').
region('Unova','Solosis').
region('Unova','Duosion').
region('Unova','Reuniclus').
region('Unova','Ducklett').
region('Unova','Swanna').
region('Unova','Vanillite').
region('Unova','Vanillish').
region('Unova','Vanilluxe').
region('Unova','Deerling').
region('Unova','Sawsbuck').
region('Unova','Emolga').
region('Unova','Karrablast').
region('Unova','Escavalier').
region('Unova','Foongus').
region('Unova','Amoonguss').
region('Unova','Frillish').
region('Unova','Jellicent').
region('Unova','Alomomola').
region('Unova','Joltik').
region('Unova','Galvantula').
region('Unova','Ferroseed').
region('Unova','Ferrothorn').
region('Unova','Klink').
region('Unova','Klang').
region('Unova','Klinklang').
region('Unova','Tynamo').
region('Unova','Eelektrik').
region('Unova','Eelektross').
region('Unova','Elgyem').
region('Unova','Beheeyem').
region('Unova','Litwick').
region('Unova','Lampent').
region('Unova','Chandelure').
region('Unova','Axew').
region('Unova','Fraxure').
region('Unova','Haxorus').
region('Unova','Cubchoo').
region('Unova','Beartic').
region('Unova','Cryogonal').
region('Unova','Shelmet').
region('Unova','Accelgor').
region('Unova','Stunfisk').
region('Unova','Mienfoo').
region('Unova','Mienshao').
region('Unova','Druddigon').
region('Unova','Golett').
region('Unova','Golurk').
region('Unova','Pawniard').
region('Unova','Bisharp').
region('Unova','Bouffalant').
region('Unova','Rufflet').
region('Unova','Braviary').
region('Unova','Vullaby').
region('Unova','Mandibuzz').
region('Unova','Heatmor').
region('Unova','Durant').
region('Unova','Deino').
region('Unova','Zweilous').
region('Unova','Hydreigon').
region('Unova','Larvesta').
region('Unova','Volcarona').
region('Unova','Cobalion').
region('Unova','Terrakion').
region('Unova','Virizion').
region('Unova','Tornadus').
region('Unova','Thundurus').
region('Unova','Reshiram').
region('Unova','Zekrom').
region('Unova','Landorus').
region('Unova','Kyurem').
region('Unova','Keldeo').
region('Unova','Meloetta').
region('Unova','Genesect').
region('Kalos','Chespin').
region('Kalos','Quilladin').
region('Kalos','Chesnaught').
region('Kalos','Fennekin').
region('Kalos','Braixen').
region('Kalos','Delphox').
region('Kalos','Froakie').
region('Kalos','Frogadier').
region('Kalos','Greninja').
region('Kalos','Bunnelby').
region('Kalos','Diggersby').
region('Kalos','Fletchling').
region('Kalos','Fletchinder').
region('Kalos','Talonflame').
region('Kalos','Scatterbug').
region('Kalos','Spewpa').
region('Kalos','Vivillon').
region('Kalos','Litleo').
region('Kalos','Pyroar').
region('Kalos','Flabébé').
region('Kalos','Floette').
region('Kalos','Florges').
region('Kalos','Skiddo').
region('Kalos','Gogoat').
region('Kalos','Pancham').
region('Kalos','Pangoro').
region('Kalos','Furfrou').
region('Kalos','Espurr').
region('Kalos','Meowstic').
region('Kalos','Honedge').
region('Kalos','Doublade').
region('Kalos','Aegislash').
region('Kalos','Spritzee').
region('Kalos','Aromatisse').
region('Kalos','Swirlix').
region('Kalos','Slurpuff').
region('Kalos','Inkay').
region('Kalos','Malamar').
region('Kalos','Binacle').
region('Kalos','Barbaracle').
region('Kalos','Skrelp').
region('Kalos','Dragalge').
region('Kalos','Clauncher').
region('Kalos','Clawitzer').
region('Kalos','Helioptile').
region('Kalos','Heliolisk').
region('Kalos','Tyrunt').
region('Kalos','Tyrantrum').
region('Kalos','Amaura').
region('Kalos','Aurorus').
region('Kalos','Sylveon').
region('Kalos','Hawlucha').
region('Kalos','Dedenne').
region('Kalos','Carbink').
region('Kalos','Goomy').
region('Kalos','Sliggoo').
region('Kalos','Goodra').
region('Kalos','Klefki').
region('Kalos','Phantump').
region('Kalos','Trevenant').
region('Kalos','Pumpkaboo').
region('Kalos','Gourgeist').
region('Kalos','Bergmite').
region('Kalos','Avalugg').
region('Kalos','Noibat').
region('Kalos','Noivern').
region('Kalos','Xerneas').
region('Kalos','Yveltal').
region('Kalos','Zygarde').
region('Kalos','Diancie').
region('Kalos','Hoopa').
region('Kalos','Volcanion').

region('Alola','Rowlet').
region('Alola','Dartrix').
region('Alola','Decidueye').
region('Alola','Litten').
region('Alola','Torracat').
region('Alola','Incineroar').
region('Alola','Popplio').
region('Alola','Brionne').
region('Alola','Primarina').
region('Alola','Pikipek').
region('Alola','Trumbeak').
region('Alola','Toucannon').
region('Alola','Yungoos').
region('Alola','Gumshoos').
region('Alola','Grubbin').
region('Alola','Charjabug').
region('Alola','Vikavolt').
region('Alola','Crabrawler').
region('Alola','Crabominable').
region('Alola','Oricorio').
region('Alola','Cutiefly').
region('Alola','Ribombee').
region('Alola','Rockruff').
region('Alola','Lycanroc').
region('Alola','Wishiwashi').
region('Alola','Mareanie').
region('Alola','Toxapex').
region('Alola','Mudbray').
region('Alola','Mudsdale').
region('Alola','Dewpider').
region('Alola','Araquanid').
region('Alola','Fomantis').
region('Alola','Lurantis').
region('Alola','Morelull').
region('Alola','Shiinotic').
region('Alola','Salandit').
region('Alola','Salazzle').
region('Alola','Stufful').
region('Alola','Bewear').
region('Alola','Bounsweet').
region('Alola','Steenee').
region('Alola','Tsareena').
region('Alola','Comfey').
region('Alola','Oranguru').
region('Alola','Passimian').
region('Alola','Wimpod').
region('Alola','Golisopod').
region('Alola','Sandygast').
region('Alola','Palossand').
region('Alola','Pyukumuku').
region('Alola','Type:Null').
region('Alola','Silvally').
region('Alola','Minior').
region('Alola','Komala').
region('Alola','Turtonator').
region('Alola','Togedemaru').
region('Alola','Mimikyu').
region('Alola','Bruxish').
region('Alola','Drampa').
region('Alola','Dhelmise').
region('Alola','Jangmo-o').
region('Alola','Hakamo-o').
region('Alola','Kommo-o').
region('Alola','Tapu-Koko').
region('Alola','Tapu-Lele').
region('Alola','Tapu-Bulu').
region('Alola','Tapu-Fini').
region('Alola','Cosmog').
region('Alola','Cosmoem').
region('Alola','Solgaleo').
region('Alola','Lunala').
region('Alola','Nihilego').
region('Alola','Buzzwole').
region('Alola','Pheromosa').
region('Alola','Xurkitree').
region('Alola','Celesteela').
region('Alola','Kartana').
region('Alola','Guzzlord').
region('Alola','Necrozma').
region('Alola','Magearna').
region('Alola','Marshadow').
region('Alola','Poipole').
region('Alola','Naganadel').
region('Alola','Stakataka').
region('Alola','Blacephalon').
region('Alola','Zeraora').
region('Alola','Meltan').
region('Alola','Melmetal').

region('Alola','Exeggutor-de-Alola').
region('Alola','Raichu-de-Alola').
region('Alola','Marowak-de-Alola').
region('Alola','Grimer-de-Alola').
region('Alola','Muk-de-Alola').
region('Alola','Rattata-de-Alola').
region('Alola','Raticate-de-Alola').
region('Alola','Sandshrew-de-Alola').
region('Alola','Sandslash-de-Alola').
region('Alola','Vulpix-de-Alola').
region('Alola','Ninetales-de-Alola').
region('Alola','Diglett-de-Alola').
region('Alola','Dugtrio-de-Alola').
region('Alola','Meowth-de-Alola').
region('Alola','Persian-de-Alola').
region('Alola','Geodude-de-Alola').
region('Alola','Graveler-de-Alola').
region('Alola','Golem-de-Alola').

region('Hoenn','Groudon-Primigenio').
region('Hoenn','Kyogre-Primigenio').

region('Hoenn','Mega-Absol').
region('Hoenn','Mega-Aggron').
region('Hoenn','Mega-Altaria').
region('Hoenn','Mega-Banette').
region('Hoenn','Mega-Blaziken').
region('Hoenn','Mega-Camerupt').
region('Hoenn','Mega-Gardevoir').
region('Hoenn','Mega-Glalie').
region('Hoenn','Mega-Latias').
region('Hoenn','Mega-Latios').
region('Hoenn','Mega-Manectric').
region('Hoenn','Mega-Mawile').
region('Hoenn','Mega-Medicham').
region('Hoenn','Mega-Metagross').
region('Hoenn','Mega-Rayquaza').
region('Hoenn','Mega-Sableye').
region('Hoenn','Mega-Salamence').
region('Hoenn','Mega-Sceptile').
region('Hoenn','Mega-Sharpedo').
region('Hoenn','Mega-Swampert').
region('Johto','Mega-Ampharos').
region('Johto','Mega-Heracross').
region('Johto','Mega-Houndoom').
region('Johto','Mega-Steelix').
region('Johto','Mega-Tyranitar').
region('Kalos','Mega-Diancie').
region('Kanto','Mega-Alakazam').
region('Kanto','Mega-Beedrill').
region('Kanto','Mega-Blastoise').
region('Kanto','Mega-Charizard-X').
region('Kanto','Mega-Charizard-Y').
region('Kanto','Mega-Gengar').
region('Kanto','Mega-Gyarados').
region('Kanto','Mega-Mewtwo-X').
region('Kanto','Mega-Mewtwo-Y').
region('Kanto','Mega-Pidgeot').
region('Kanto','Mega-Pinsir').
region('Kanto','Mega-Scizor').
region('Kanto','Mega-Slowbro').
region('Kanto','Mega-Venusaur').
region('Kanto','Mega-Aerodactyl').
region('Kanto','Mega-Kangaskhan').
region('Sinnoh','Mega-Abomasnow').
region('Sinnoh','Mega-Gallade').
region('Sinnoh','Mega-Garchomp').
region('Sinnoh','Mega-Lucario').
region('Sinnoh','Mega-Lopunny').
region('Unova','Mega-Audino').

region('Unova','Meloetta-Pirueta').
region('Unova','Keldeo-Resolete').
region('Unova','Landorus-Therian').
region('Unova','Thundurus-Therian').
region('Unova','Tornadus-Therian').

region('Sinnoh','Rotom-Calor').
region('Sinnoh','Rotom-Frio').
region('Sinnoh','Rotom-Ventilador').
region('Sinnoh','Rotom-Corte').
region('Sinnoh','Rotom-Lavado').

region('Kanto','Missingno').
