:- pce_image_directory('./imagenes/sprites').
:- style_check(-singleton).

resource('Bulbasaur', image, image('Bulbasaur.jpg')).
resource('Ivysaur',image,image('Ivysaur.jpg')).
resource('Venusaur',image,image('Venusaur.jpg')).
resource('Charmander',image,image('Charmander.jpg')).
resource('Charmeleon',image,image('Charmeleon.jpg')).
resource('Charizard',image,image('Charizard.jpg')).
resource('Squirtle',image,image('Squirtle.jpg')).
resource('Wartortle',image,image('Wartortle.jpg')).
resource('Blastoise',image,image('Blastoise.jpg')).
resource('Caterpie',image,image('Caterpie.jpg')).
resource('Metapod',image,image('Metapod.jpg')).
resource('Butterfree',image,image('Butterfree.jpg')).
resource('Weedle',image,image('Weedle.jpg')).
resource('Kakuna',image,image('Kakuna.jpg')).
resource('Beedrill',image,image('Beedrill.jpg')).
resource('Pidgey',image,image('Pidgey.jpg')).
resource('Pidgeotto',image,image('Pidgeotto.jpg')).
resource('Pidgeot',image,image('Pidgeot.jpg')).
resource('Rattata',image,image('Rattata.jpg')).
resource('Raticate',image,image('Raticate.jpg')).
resource('Spearow',image,image('Spearow.jpg')).
resource('Fearow',image,image('Fearow.jpg')).
resource('Ekans',image,image('Ekans.jpg')).
resource('Arbok',image,image('Arbok.jpg')).
resource('Pikachu',image,image('Pikachu.jpg')).
resource('Raichu',image,image('Raichu.jpg')).
resource('Sandshrew',image,image('Sandshrew.jpg')).
resource('Sandslash',image,image('Sandslash.jpg')).
resource('Nidoran-F',image,image('Nidoran-f.jpg')).
resource('Nidorina',image,image('Nidorina.jpg')).
resource('Nidoqueen',image,image('Nidoqueen.jpg')).
resource('Nidoran-M',image,image('Nidoran-m.jpg')).
resource('Nidorino',image,image('Nidorino.jpg')).
resource('Nidoking',image,image('Nidoking.jpg')).
resource('Clefairy',image,image('Clefairy.jpg')).
resource('Clefable',image,image('Clefable.jpg')).
resource('Vulpix',image,image('Vulpix.jpg')).
resource('Ninetales',image,image('Ninetales.jpg')).
resource('Jigglypuff',image,image('Jigglypuff.jpg')).
resource('Wigglytuff',image,image('Wigglytuff.jpg')).
resource('Zubat',image,image('Zubat.jpg')).
resource('Golbat',image,image('Golbat.jpg')).
resource('Oddish',image,image('Oddish.jpg')).
resource('Gloom',image,image('Gloom.jpg')).
resource('Vileplume',image,image('Vileplume.jpg')).
resource('Paras',image,image('Paras.jpg')).
resource('Parasect',image,image('Parasect.jpg')).
resource('Venonat',image,image('Venonat.jpg')).
resource('Venomoth',image,image('Venomoth.jpg')).
resource('Diglett',image,image('Diglett.jpg')).
resource('Dugtrio',image,image('Dugtrio.jpg')).
resource('Meowth',image,image('Meowth.jpg')).
resource('Persian',image,image('Persian.jpg')).
resource('Psyduck',image,image('Psyduck.jpg')).
resource('Golduck',image,image('Golduck.jpg')).
resource('Mankey',image,image('Mankey.jpg')).
resource('Primeape',image,image('Primeape.jpg')).
resource('Growlithe',image,image('Growlithe.jpg')).
resource('Arcanine',image,image('Arcanine.jpg')).
resource('Poliwag',image,image('Poliwag.jpg')).
resource('Poliwhirl',image,image('Poliwhirl.jpg')).
resource('Poliwrath',image,image('Poliwrath.jpg')).
resource('Abra',image,image('Abra.jpg')).
resource('Kadabra',image,image('Kadabra.jpg')).
resource('Alakazam',image,image('Alakazam.jpg')).
resource('Machop',image,image('Machop.jpg')).
resource('Machoke',image,image('Machoke.jpg')).
resource('Machamp',image,image('Machamp.jpg')).
resource('Bellsprout',image,image('Bellsprout.jpg')).
resource('Weepinbell',image,image('Weepinbell.jpg')).
resource('Victreebel',image,image('Victreebel.jpg')).
resource('Tentacool',image,image('Tentacool.jpg')).
resource('Tentacruel',image,image('Tentacruel.jpg')).
resource('Geodude',image,image('Geodude.jpg')).
resource('Graveler',image,image('Graveler.jpg')).
resource('Golem',image,image('Golem.jpg')).
resource('Ponyta',image,image('Ponyta.jpg')).
resource('Rapidash',image,image('Rapidash.jpg')).
resource('Slowpoke',image,image('Slowpoke.jpg')).
resource('Slowbro',image,image('Slowbro.jpg')).
resource('Magnemite',image,image('Magnemite.jpg')).
resource('Magneton',image,image('Magneton.jpg')).
resource('Farfetchd',image,image('Farfetchd.jpg')).
resource('Doduo',image,image('Doduo.jpg')).
resource('Dodrio',image,image('Dodrio.jpg')).
resource('Seel',image,image('Seel.jpg')).
resource('Dewgong',image,image('Dewgong.jpg')).
resource('Grimer',image,image('Grimer.jpg')).
resource('Muk',image,image('Muk.jpg')).
resource('Shellder',image,image('Shellder.jpg')).
resource('Cloyster',image,image('Cloyster.jpg')).
resource('Gastly',image,image('Gastly.jpg')).
resource('Haunter',image,image('Haunter.jpg')).
resource('Gengar',image,image('Gengar.jpg')).
resource('Onix',image,image('Onix.jpg')).
resource('Drowzee',image,image('Drowzee.jpg')).
resource('Hypno',image,image('Hypno.jpg')).
resource('Krabby',image,image('Krabby.jpg')).
resource('Kingler',image,image('Kingler.jpg')).
resource('Voltorb',image,image('Voltorb.jpg')).
resource('Electrode',image,image('Electrode.jpg')).
resource('Exeggcute',image,image('Exeggcute.jpg')).
resource('Exeggutor',image,image('Exeggutor.jpg')).
resource('Cubone',image,image('Cubone.jpg')).
resource('Marowak',image,image('Marowak.jpg')).
resource('Hitmonlee',image,image('Hitmonlee.jpg')).
resource('Hitmonchan',image,image('Hitmonchan.jpg')).
resource('Lickitung',image,image('Lickitung.jpg')).
resource('Koffing',image,image('Koffing.jpg')).
resource('Weezing',image,image('Weezing.jpg')).
resource('Rhyhorn',image,image('Rhyhorn.jpg')).
resource('Rhydon',image,image('Rhydon.jpg')).
resource('Chansey',image,image('Chansey.jpg')).
resource('Tangela',image,image('Tangela.jpg')).
resource('Kangaskhan',image,image('Kangaskhan.jpg')).
resource('Horsea',image,image('Horsea.jpg')).
resource('Seadra',image,image('Seadra.jpg')).
resource('Goldeen',image,image('Goldeen.jpg')).
resource('Seaking',image,image('Seaking.jpg')).
resource('Staryu',image,image('Staryu.jpg')).
resource('Starmie',image,image('Starmie.jpg')).
resource('Mr.Mime',image,image('Mr-mime.jpg')).
resource('Scyther',image,image('Scyther.jpg')).
resource('Jynx',image,image('Jynx.jpg')).
resource('Electabuzz',image,image('Electabuzz.jpg')).
resource('Magmar',image,image('Magmar.jpg')).
resource('Pinsir',image,image('Pinsir.jpg')).
resource('Tauros',image,image('Tauros.jpg')).
resource('Magikarp',image,image('Magikarp.jpg')).
resource('Gyarados',image,image('Gyarados.jpg')).
resource('Lapras',image,image('Lapras.jpg')).
resource('Ditto',image,image('Ditto.jpg')).
resource('Eevee',image,image('Eevee.jpg')).
resource('Vaporeon',image,image('Vaporeon.jpg')).
resource('Jolteon',image,image('Jolteon.jpg')).
resource('Flareon',image,image('Flareon.jpg')).
resource('Porygon',image,image('Porygon.jpg')).
resource('Omanyte',image,image('Omanyte.jpg')).
resource('Omastar',image,image('Omastar.jpg')).
resource('Kabuto',image,image('Kabuto.jpg')).
resource('Kabutops',image,image('Kabutops.jpg')).
resource('Aerodactyl',image,image('Aerodactyl.jpg')).
resource('Snorlax',image,image('Snorlax.jpg')).
resource('Articuno',image,image('Articuno.jpg')).
resource('Zapdos',image,image('Zapdos.jpg')).
resource('Moltres',image,image('Moltres.jpg')).
resource('Dratini',image,image('Dratini.jpg')).
resource('Dragonair',image,image('Dragonair.jpg')).
resource('Dragonite',image,image('Dragonite.jpg')).
resource('Mewtwo',image,image('Mewtwo.jpg')).
resource('Mew',image,image('Mew.jpg')).
resource('Chikorita',image,image('Chikorita.jpg')).
resource('Bayleef',image,image('Bayleef.jpg')).
resource('Meganium',image,image('Meganium.jpg')).
resource('Cyndaquil',image,image('Cyndaquil.jpg')).
resource('Quilava',image,image('Quilava.jpg')).
resource('Typhlosion',image,image('Typhlosion.jpg')).
resource('Totodile',image,image('Totodile.jpg')).
resource('Croconaw',image,image('Croconaw.jpg')).
resource('Feraligatr',image,image('Feraligatr.jpg')).
resource('Sentret',image,image('Sentret.jpg')).
resource('Furret',image,image('Furret.jpg')).
resource('Hoothoot',image,image('Hoothoot.jpg')).
resource('Noctowl',image,image('Noctowl.jpg')).
resource('Ledyba',image,image('Ledyba.jpg')).
resource('Ledian',image,image('Ledian.jpg')).
resource('Spinarak',image,image('Spinarak.jpg')).
resource('Ariados',image,image('Ariados.jpg')).
resource('Crobat',image,image('Crobat.jpg')).
resource('Chinchou',image,image('Chinchou.jpg')).
resource('Lanturn',image,image('Lanturn.jpg')).
resource('Pichu',image,image('Pichu.jpg')).
resource('Cleffa',image,image('Cleffa.jpg')).
resource('Igglybuff',image,image('Igglybuff.jpg')).
resource('Togepi',image,image('Togepi.jpg')).
resource('Togetic',image,image('Togetic.jpg')).
resource('Natu',image,image('Natu.jpg')).
resource('Xatu',image,image('Xatu.jpg')).
resource('Mareep',image,image('Mareep.jpg')).
resource('Flaaffy',image,image('Flaaffy.jpg')).
resource('Ampharos',image,image('Ampharos.jpg')).
resource('Bellossom',image,image('Bellossom.jpg')).
resource('Marill',image,image('Marill.jpg')).
resource('Azumarill',image,image('Azumarill.jpg')).
resource('Sudowoodo',image,image('Sudowoodo.jpg')).
resource('Politoed',image,image('Politoed.jpg')).
resource('Hoppip',image,image('Hoppip.jpg')).
resource('Skiploom',image,image('Skiploom.jpg')).
resource('Jumpluff',image,image('Jumpluff.jpg')).
resource('Aipom',image,image('Aipom.jpg')).
resource('Sunkern',image,image('Sunkern.jpg')).
resource('Sunflora',image,image('Sunflora.jpg')).
resource('Yanma',image,image('Yanma.jpg')).
resource('Wooper',image,image('Wooper.jpg')).
resource('Quagsire',image,image('Quagsire.jpg')).
resource('Espeon',image,image('Espeon.jpg')).
resource('Umbreon',image,image('Umbreon.jpg')).
resource('Murkrow',image,image('Murkrow.jpg')).
resource('Slowking',image,image('Slowking.jpg')).
resource('Misdreavus',image,image('Misdreavus.jpg')).
resource('Unown',image,image('Unown.jpg')).
resource('Wobbuffet',image,image('Wobbuffet.jpg')).
resource('Girafarig',image,image('Girafarig.jpg')).
resource('Pineco',image,image('Pineco.jpg')).
resource('Forretress',image,image('Forretress.jpg')).
resource('Dunsparce',image,image('Dunsparce.jpg')).
resource('Gligar',image,image('Gligar.jpg')).
resource('Steelix',image,image('Steelix.jpg')).
resource('Snubbull',image,image('Snubbull.jpg')).
resource('Granbull',image,image('Granbull.jpg')).
resource('Qwilfish',image,image('Qwilfish.jpg')).
resource('Scizor',image,image('Scizor.jpg')).
resource('Shuckle',image,image('Shuckle.jpg')).
resource('Heracross',image,image('Heracross.jpg')).
resource('Sneasel',image,image('Sneasel.jpg')).
resource('Teddiursa',image,image('Teddiursa.jpg')).
resource('Ursaring',image,image('Ursaring.jpg')).
resource('Slugma',image,image('Slugma.jpg')).
resource('Magcargo',image,image('Magcargo.jpg')).
resource('Swinub',image,image('Swinub.jpg')).
resource('Piloswine',image,image('Piloswine.jpg')).
resource('Corsola',image,image('Corsola.jpg')).
resource('Remoraid',image,image('Remoraid.jpg')).
resource('Octillery',image,image('Octillery.jpg')).
resource('Delibird',image,image('Delibird.jpg')).
resource('Mantine',image,image('Mantine.jpg')).
resource('Skarmory',image,image('Skarmory.jpg')).
resource('Houndour',image,image('Houndour.jpg')).
resource('Houndoom',image,image('Houndoom.jpg')).
resource('Kingdra',image,image('Kingdra.jpg')).
resource('Phanpy',image,image('Phanpy.jpg')).
resource('Donphan',image,image('Donphan.jpg')).
resource('Porygon2',image,image('Porygon2.jpg')).
resource('Stantler',image,image('Stantler.jpg')).
resource('Smeargle',image,image('Smeargle.jpg')).
resource('Tyrogue',image,image('Tyrogue.jpg')).
resource('Hitmontop',image,image('Hitmontop.jpg')).
resource('Smoochum',image,image('Smoochum.jpg')).
resource('Elekid',image,image('Elekid.jpg')).
resource('Magby',image,image('Magby.jpg')).
resource('Miltank',image,image('Miltank.jpg')).
resource('Blissey',image,image('Blissey.jpg')).
resource('Raikou',image,image('Raikou.jpg')).
resource('Entei',image,image('Entei.jpg')).
resource('Suicune',image,image('Suicune.jpg')).
resource('Larvitar',image,image('Larvitar.jpg')).
resource('Pupitar',image,image('Pupitar.jpg')).
resource('Tyranitar',image,image('Tyranitar.jpg')).
resource('Lugia',image,image('Lugia.jpg')).
resource('Ho-Oh',image,image('Ho-Oh.jpg')).
resource('Celebi',image,image('Celebi.jpg')).
resource('Treecko',image,image('Treecko.jpg')).
resource('Grovyle',image,image('Grovyle.jpg')).
resource('Sceptile',image,image('Sceptile.jpg')).
resource('Torchic',image,image('Torchic.jpg')).
resource('Combusken',image,image('Combusken.jpg')).
resource('Blaziken',image,image('Blaziken.jpg')).
resource('Mudkip',image,image('Mudkip.jpg')).
resource('Marshtomp',image,image('Marshtomp.jpg')).
resource('Swampert',image,image('Swampert.jpg')).
resource('Poochyena',image,image('Poochyena.jpg')).
resource('Mightyena',image,image('Mightyena.jpg')).
resource('Zigzagoon',image,image('Zigzagoon.jpg')).
resource('Linoone',image,image('Linoone.jpg')).
resource('Wurmple',image,image('Wurmple.jpg')).
resource('Silcoon',image,image('Silcoon.jpg')).
resource('Beautifly',image,image('Beautifly.jpg')).
resource('Cascoon',image,image('Cascoon.jpg')).
resource('Dustox',image,image('Dustox.jpg')).
resource('Lotad',image,image('Lotad.jpg')).
resource('Lombre',image,image('Lombre.jpg')).
resource('Ludicolo',image,image('Ludicolo.jpg')).
resource('Seedot',image,image('Seedot.jpg')).
resource('Nuzleaf',image,image('Nuzleaf.jpg')).
resource('Shiftry',image,image('Shiftry.jpg')).
resource('Taillow',image,image('Taillow.jpg')).
resource('Swellow',image,image('Swellow.jpg')).
resource('Wingull',image,image('Wingull.jpg')).
resource('Pelipper',image,image('Pelipper.jpg')).
resource('Ralts',image,image('Ralts.jpg')).
resource('Kirlia',image,image('Kirlia.jpg')).
resource('Gardevoir',image,image('Gardevoir.jpg')).
resource('Surskit',image,image('Surskit.jpg')).
resource('Masquerain',image,image('Masquerain.jpg')).
resource('Shroomish',image,image('Shroomish.jpg')).
resource('Breloom',image,image('Breloom.jpg')).
resource('Slakoth',image,image('Slakoth.jpg')).
resource('Vigoroth',image,image('Vigoroth.jpg')).
resource('Slaking',image,image('Slaking.jpg')).
resource('Nincada',image,image('Nincada.jpg')).
resource('Ninjask',image,image('Ninjask.jpg')).
resource('Shedinja',image,image('Shedinja.jpg')).
resource('Whismur',image,image('Whismur.jpg')).
resource('Loudred',image,image('Loudred.jpg')).
resource('Exploud',image,image('Exploud.jpg')).
resource('Makuhita',image,image('Makuhita.jpg')).
resource('Hariyama',image,image('Hariyama.jpg')).
resource('Azurill',image,image('Azurill.jpg')).
resource('Nosepass',image,image('Nosepass.jpg')).
resource('Skitty',image,image('Skitty.jpg')).
resource('Delcatty',image,image('Delcatty.jpg')).
resource('Sableye',image,image('Sableye.jpg')).
resource('Mawile',image,image('Mawile.jpg')).
resource('Aron',image,image('Aron.jpg')).
resource('Lairon',image,image('Lairon.jpg')).
resource('Aggron',image,image('Aggron.jpg')).
resource('Meditite',image,image('Meditite.jpg')).
resource('Medicham',image,image('Medicham.jpg')).
resource('Electrike',image,image('Electrike.jpg')).
resource('Manectric',image,image('Manectric.jpg')).
resource('Plusle',image,image('Plusle.jpg')).
resource('Minun',image,image('Minun.jpg')).
resource('Volbeat',image,image('Volbeat.jpg')).
resource('Illumise',image,image('Illumise.jpg')).
resource('Roselia',image,image('Roselia.jpg')).
resource('Gulpin',image,image('Gulpin.jpg')).
resource('Swalot',image,image('Swalot.jpg')).
resource('Carvanha',image,image('Carvanha.jpg')).
resource('Sharpedo',image,image('Sharpedo.jpg')).
resource('Wailmer',image,image('Wailmer.jpg')).
resource('Wailord',image,image('Wailord.jpg')).
resource('Numel',image,image('Numel.jpg')).
resource('Camerupt',image,image('Camerupt.jpg')).
resource('Torkoal',image,image('Torkoal.jpg')).
resource('Spoink',image,image('Spoink.jpg')).
resource('Grumpig',image,image('Grumpig.jpg')).
resource('Spinda',image,image('Spinda.jpg')).
resource('Trapinch',image,image('Trapinch.jpg')).
resource('Vibrava',image,image('Vibrava.jpg')).
resource('Flygon',image,image('Flygon.jpg')).
resource('Cacnea',image,image('Cacnea.jpg')).
resource('Cacturne',image,image('Cacturne.jpg')).
resource('Swablu',image,image('Swablu.jpg')).
resource('Altaria',image,image('Altaria.jpg')).
resource('Zangoose',image,image('Zangoose.jpg')).
resource('Seviper',image,image('Seviper.jpg')).
resource('Lunatone',image,image('Lunatone.jpg')).
resource('Solrock',image,image('Solrock.jpg')).
resource('Barboach',image,image('Barboach.jpg')).
resource('Whiscash',image,image('Whiscash.jpg')).
resource('Corphish',image,image('Corphish.jpg')).
resource('Crawdaunt',image,image('Crawdaunt.jpg')).
resource('Baltoy',image,image('Baltoy.jpg')).
resource('Claydol',image,image('Claydol.jpg')).
resource('Lileep',image,image('Lileep.jpg')).
resource('Cradily',image,image('Cradily.jpg')).
resource('Anorith',image,image('Anorith.jpg')).
resource('Armaldo',image,image('Armaldo.jpg')).
resource('Feebas',image,image('Feebas.jpg')).
resource('Milotic',image,image('Milotic.jpg')).
resource('Castform',image,image('Castform.jpg')).
resource('Kecleon',image,image('Kecleon.jpg')).
resource('Shuppet',image,image('Shuppet.jpg')).
resource('Banette',image,image('Banette.jpg')).
resource('Duskull',image,image('Duskull.jpg')).
resource('Dusclops',image,image('Dusclops.jpg')).
resource('Tropius',image,image('Tropius.jpg')).
resource('Chimecho',image,image('Chimecho.jpg')).
resource('Absol',image,image('Absol.jpg')).
resource('Wynaut',image,image('Wynaut.jpg')).
resource('Snorunt',image,image('Snorunt.jpg')).
resource('Glalie',image,image('Glalie.jpg')).
resource('Spheal',image,image('Spheal.jpg')).
resource('Sealeo',image,image('Sealeo.jpg')).
resource('Walrein',image,image('Walrein.jpg')).
resource('Clamperl',image,image('Clamperl.jpg')).
resource('Huntail',image,image('Huntail.jpg')).
resource('Gorebyss',image,image('Gorebyss.jpg')).
resource('Relicanth',image,image('Relicanth.jpg')).
resource('Luvdisc',image,image('Luvdisc.jpg')).
resource('Bagon',image,image('Bagon.jpg')).
resource('Shelgon',image,image('Shelgon.jpg')).
resource('Salamence',image,image('Salamence.jpg')).
resource('Beldum',image,image('Beldum.jpg')).
resource('Metang',image,image('Metang.jpg')).
resource('Metagross',image,image('Metagross.jpg')).
resource('Regirock',image,image('Regirock.jpg')).
resource('Regice',image,image('Regice.jpg')).
resource('Registeel',image,image('Registeel.jpg')).
resource('Latias',image,image('Latias.jpg')).
resource('Latios',image,image('Latios.jpg')).
resource('Kyogre',image,image('Kyogre.jpg')).
resource('Groudon',image,image('Groudon.jpg')).
resource('Rayquaza',image,image('Rayquaza.jpg')).
resource('Jirachi',image,image('Jirachi.jpg')).
resource('Deoxys',image,image('Deoxys.jpg')).
resource('Turtwig',image,image('Turtwig.jpg')).
resource('Grotle',image,image('Grotle.jpg')).
resource('Torterra',image,image('Torterra.jpg')).
resource('Chimchar',image,image('Chimchar.jpg')).
resource('Monferno',image,image('Monferno.jpg')).
resource('Infernape',image,image('Infernape.jpg')).
resource('Piplup',image,image('Piplup.jpg')).
resource('Prinplup',image,image('Prinplup.jpg')).
resource('Empoleon',image,image('Empoleon.jpg')).
resource('Starly',image,image('Starly.jpg')).
resource('Staravia',image,image('Staravia.jpg')).
resource('Staraptor',image,image('Staraptor.jpg')).
resource('Bidoof',image,image('Bidoof.jpg')).
resource('Bibarel',image,image('Bibarel.jpg')).
resource('Kricketot',image,image('Kricketot.jpg')).
resource('Kricketune',image,image('Kricketune.jpg')).
resource('Shinx',image,image('Shinx.jpg')).
resource('Luxio',image,image('Luxio.jpg')).
resource('Luxray',image,image('Luxray.jpg')).
resource('Budew',image,image('Budew.jpg')).
resource('Roserade',image,image('Roserade.jpg')).
resource('Cranidos',image,image('Cranidos.jpg')).
resource('Rampardos',image,image('Rampardos.jpg')).
resource('Shieldon',image,image('Shieldon.jpg')).
resource('Bastiodon',image,image('Bastiodon.jpg')).
resource('Burmy',image,image('Burmy.jpg')).
resource('Wormadam',image,image('Wormadam.jpg')).
resource('Mothim',image,image('Mothim.jpg')).
resource('Combee',image,image('Combee.jpg')).
resource('Vespiquen',image,image('Vespiquen.jpg')).
resource('Pachirisu',image,image('Pachirisu.jpg')).
resource('Buizel',image,image('Buizel.jpg')).
resource('Floatzel',image,image('Floatzel.jpg')).
resource('Cherubi',image,image('Cherubi.jpg')).
resource('Cherrim',image,image('Cherrim.jpg')).
resource('Shellos',image,image('Shellos.jpg')).
resource('Gastrodon',image,image('Gastrodon.jpg')).
resource('Ambipom',image,image('Ambipom.jpg')).
resource('Drifloon',image,image('Drifloon.jpg')).
resource('Drifblim',image,image('Drifblim.jpg')).
resource('Buneary',image,image('Buneary.jpg')).
resource('Lopunny',image,image('Lopunny.jpg')).
resource('Mismagius',image,image('Mismagius.jpg')).
resource('Honchkrow',image,image('Honchkrow.jpg')).
resource('Glameow',image,image('Glameow.jpg')).
resource('Purugly',image,image('Purugly.jpg')).
resource('Chingling',image,image('Chingling.jpg')).
resource('Stunky',image,image('Stunky.jpg')).
resource('Skuntank',image,image('Skuntank.jpg')).
resource('Bronzor',image,image('Bronzor.jpg')).
resource('Bronzong',image,image('Bronzong.jpg')).
resource('Bonsly',image,image('Bonsly.jpg')).
resource('Mime-Jr.',image,image('Mime-Jr.jpg')).
resource('Happiny',image,image('Happiny.jpg')).
resource('Chatot',image,image('Chatot.jpg')).
resource('Spiritomb',image,image('Spiritomb.jpg')).
resource('Gible',image,image('Gible.jpg')).
resource('Gabite',image,image('Gabite.jpg')).
resource('Garchomp',image,image('Garchomp.jpg')).
resource('Munchlax',image,image('Munchlax.jpg')).
resource('Riolu',image,image('Riolu.jpg')).
resource('Lucario',image,image('Lucario.jpg')).
resource('Hippopotas',image,image('Hippopotas.jpg')).
resource('Hippowdon',image,image('Hippowdon.jpg')).
resource('Skorupi',image,image('Skorupi.jpg')).
resource('Drapion',image,image('Drapion.jpg')).
resource('Croagunk',image,image('Croagunk.jpg')).
resource('Toxicroak',image,image('Toxicroak.jpg')).
resource('Carnivine',image,image('Carnivine.jpg')).
resource('Finneon',image,image('Finneon.jpg')).
resource('Lumineon',image,image('Lumineon.jpg')).
resource('Mantyke',image,image('Mantyke.jpg')).
resource('Snover',image,image('Snover.jpg')).
resource('Abomasnow',image,image('Abomasnow.jpg')).
resource('Weavile',image,image('Weavile.jpg')).
resource('Magnezone',image,image('Magnezone.jpg')).
resource('Lickilicky',image,image('Lickilicky.jpg')).
resource('Rhyperior',image,image('Rhyperior.jpg')).
resource('Tangrowth',image,image('Tangrowth.jpg')).
resource('Electivire',image,image('Electivire.jpg')).
resource('Magmortar',image,image('Magmortar.jpg')).
resource('Togekiss',image,image('Togekiss.jpg')).
resource('Yanmega',image,image('Yanmega.jpg')).
resource('Leafeon',image,image('Leafeon.jpg')).
resource('Glaceon',image,image('Glaceon.jpg')).
resource('Gliscor',image,image('Gliscor.jpg')).
resource('Mamoswine',image,image('Mamoswine.jpg')).
resource('Porygon-Z',image,image('Porygon-Z.jpg')).
resource('Gallade',image,image('Gallade.jpg')).
resource('Probopass',image,image('Probopass.jpg')).
resource('Dusknoir',image,image('Dusknoir.jpg')).
resource('Froslass',image,image('Froslass.jpg')).
resource('Rotom',image,image('Rotom.jpg')).
resource('Uxie',image,image('Uxie.jpg')).
resource('Mesprit',image,image('Mesprit.jpg')).
resource('Azelf',image,image('Azelf.jpg')).
resource('Dialga',image,image('Dialga.jpg')).
resource('Palkia',image,image('Palkia.jpg')).
resource('Heatran',image,image('Heatran.jpg')).
resource('Regigigas',image,image('Regigigas.jpg')).
resource('Giratina',image,image('Giratina.jpg')).
resource('Cresselia',image,image('Cresselia.jpg')).
resource('Phione',image,image('Phione.jpg')).
resource('Manaphy',image,image('Manaphy.jpg')).
resource('Darkrai',image,image('Darkrai.jpg')).
resource('Shaymin',image,image('Shaymin.jpg')).
resource('Arceus',image,image('Arceus.jpg')).
resource('Victini',image,image('Victini.jpg')).
resource('Snivy',image,image('Snivy.jpg')).
resource('Servine',image,image('Servine.jpg')).
resource('Serperior',image,image('Serperior.jpg')).
resource('Tepig',image,image('Tepig.jpg')).
resource('Pignite',image,image('Pignite.jpg')).
resource('Emboar',image,image('Emboar.jpg')).
resource('Oshawott',image,image('Oshawott.jpg')).
resource('Dewott',image,image('Dewott.jpg')).
resource('Samurott',image,image('Samurott.jpg')).
resource('Patrat',image,image('Patrat.jpg')).
resource('Watchog',image,image('Watchog.jpg')).
resource('Lillipup',image,image('Lillipup.jpg')).
resource('Herdier',image,image('Herdier.jpg')).
resource('Stoutland',image,image('Stoutland.jpg')).
resource('Purrloin',image,image('Purrloin.jpg')).
resource('Liepard',image,image('Liepard.jpg')).
resource('Pansage',image,image('Pansage.jpg')).
resource('Simisage',image,image('Simisage.jpg')).
resource('Pansear',image,image('Pansear.jpg')).
resource('Simisear',image,image('Simisear.jpg')).
resource('Panpour',image,image('Panpour.jpg')).
resource('Simipour',image,image('Simipour.jpg')).
resource('Munna',image,image('Munna.jpg')).
resource('Musharna',image,image('Musharna.jpg')).
resource('Pidove',image,image('Pidove.jpg')).
resource('Tranquill',image,image('Tranquill.jpg')).
resource('Unfezant',image,image('Unfezant.jpg')).
resource('Blitzle',image,image('Blitzle.jpg')).
resource('Zebstrika',image,image('Zebstrika.jpg')).
resource('Roggenrola',image,image('Roggenrola.jpg')).
resource('Boldore',image,image('Boldore.jpg')).
resource('Gigalith',image,image('Gigalith.jpg')).
resource('Woobat',image,image('Woobat.jpg')).
resource('Swoobat',image,image('Swoobat.jpg')).
resource('Drilbur',image,image('Drilbur.jpg')).
resource('Excadrill',image,image('Excadrill.jpg')).
resource('Audino',image,image('Audino.jpg')).
resource('Timburr',image,image('Timburr.jpg')).
resource('Gurdurr',image,image('Gurdurr.jpg')).
resource('Conkeldurr',image,image('Conkeldurr.jpg')).
resource('Tympole',image,image('Tympole.jpg')).
resource('Palpitoad',image,image('Palpitoad.jpg')).
resource('Seismitoad',image,image('Seismitoad.jpg')).
resource('Throh',image,image('Throh.jpg')).
resource('Sawk',image,image('Sawk.jpg')).
resource('Sewaddle',image,image('Sewaddle.jpg')).
resource('Swadloon',image,image('Swadloon.jpg')).
resource('Leavanny',image,image('Leavanny.jpg')).
resource('Venipede',image,image('Venipede.jpg')).
resource('Whirlipede',image,image('Whirlipede.jpg')).
resource('Scolipede',image,image('Scolipede.jpg')).
resource('Cottonee',image,image('Cottonee.jpg')).
resource('Whimsicott',image,image('Whimsicott.jpg')).
resource('Petilil',image,image('Petilil.jpg')).
resource('Lilligant',image,image('Lilligant.jpg')).
resource('Basculin',image,image('Basculin.jpg')).
resource('Sandile',image,image('Sandile.jpg')).
resource('Krokorok',image,image('Krokorok.jpg')).
resource('Krookodile',image,image('Krookodile.jpg')).
resource('Darumaka',image,image('Darumaka.jpg')).
resource('Darmanitan',image,image('Darmanitan.jpg')).
resource('Maractus',image,image('Maractus.jpg')).
resource('Dwebble',image,image('Dwebble.jpg')).
resource('Crustle',image,image('Crustle.jpg')).
resource('Scraggy',image,image('Scraggy.jpg')).
resource('Scrafty',image,image('Scrafty.jpg')).
resource('Sigilyph',image,image('Sigilyph.jpg')).
resource('Yamask',image,image('Yamask.jpg')).
resource('Cofagrigus',image,image('Cofagrigus.jpg')).
resource('Tirtouga',image,image('Tirtouga.jpg')).
resource('Carracosta',image,image('Carracosta.jpg')).
resource('Archen',image,image('Archen.jpg')).
resource('Archeops',image,image('Archeops.jpg')).
resource('Trubbish',image,image('Trubbish.jpg')).
resource('Garbodor',image,image('Garbodor.jpg')).
resource('Zorua',image,image('Zorua.jpg')).
resource('Zoroark',image,image('Zoroark.jpg')).
resource('Minccino',image,image('Minccino.jpg')).
resource('Cinccino',image,image('Cinccino.jpg')).
resource('Gothita',image,image('Gothita.jpg')).
resource('Gothorita',image,image('Gothorita.jpg')).
resource('Gothitelle',image,image('Gothitelle.jpg')).
resource('Solosis',image,image('Solosis.jpg')).
resource('Duosion',image,image('Duosion.jpg')).
resource('Reuniclus',image,image('Reuniclus.jpg')).
resource('Ducklett',image,image('Ducklett.jpg')).
resource('Swanna',image,image('Swanna.jpg')).
resource('Vanillite',image,image('Vanillite.jpg')).
resource('Vanillish',image,image('Vanillish.jpg')).
resource('Vanilluxe',image,image('Vanilluxe.jpg')).
resource('Deerling',image,image('Deerling.jpg')).
resource('Sawsbuck',image,image('Sawsbuck.jpg')).
resource('Emolga',image,image('Emolga.jpg')).
resource('Karrablast',image,image('Karrablast.jpg')).
resource('Escavalier',image,image('Escavalier.jpg')).
resource('Foongus',image,image('Foongus.jpg')).
resource('Amoonguss',image,image('Amoonguss.jpg')).
resource('Frillish',image,image('Frillish.jpg')).
resource('Jellicent',image,image('Jellicent.jpg')).
resource('Alomomola',image,image('Alomomola.jpg')).
resource('Joltik',image,image('Joltik.jpg')).
resource('Galvantula',image,image('Galvantula.jpg')).
resource('Ferroseed',image,image('Ferroseed.jpg')).
resource('Ferrothorn',image,image('Ferrothorn.jpg')).
resource('Klink',image,image('Klink.jpg')).
resource('Klang',image,image('Klang.jpg')).
resource('Klinklang',image,image('Klinklang.jpg')).
resource('Tynamo',image,image('Tynamo.jpg')).
resource('Eelektrik',image,image('Eelektrik.jpg')).
resource('Eelektross',image,image('Eelektross.jpg')).
resource('Elgyem',image,image('Elgyem.jpg')).
resource('Beheeyem',image,image('Beheeyem.jpg')).
resource('Litwick',image,image('Litwick.jpg')).
resource('Lampent',image,image('Lampent.jpg')).
resource('Chandelure',image,image('Chandelure.jpg')).
resource('Axew',image,image('Axew.jpg')).
resource('Fraxure',image,image('Fraxure.jpg')).
resource('Haxorus',image,image('Haxorus.jpg')).
resource('Cubchoo',image,image('Cubchoo.jpg')).
resource('Beartic',image,image('Beartic.jpg')).
resource('Cryogonal',image,image('Cryogonal.jpg')).
resource('Shelmet',image,image('Shelmet.jpg')).
resource('Accelgor',image,image('Accelgor.jpg')).
resource('Stunfisk',image,image('Stunfisk.jpg')).
resource('Mienfoo',image,image('Mienfoo.jpg')).
resource('Mienshao',image,image('Mienshao.jpg')).
resource('Druddigon',image,image('Druddigon.jpg')).
resource('Golett',image,image('Golett.jpg')).
resource('Golurk',image,image('Golurk.jpg')).
resource('Pawniard',image,image('Pawniard.jpg')).
resource('Bisharp',image,image('Bisharp.jpg')).
resource('Bouffalant',image,image('Bouffalant.jpg')).
resource('Rufflet',image,image('Rufflet.jpg')).
resource('Braviary',image,image('Braviary.jpg')).
resource('Vullaby',image,image('Vullaby.jpg')).
resource('Mandibuzz',image,image('Mandibuzz.jpg')).
resource('Heatmor',image,image('Heatmor.jpg')).
resource('Durant',image,image('Durant.jpg')).
resource('Deino',image,image('Deino.jpg')).
resource('Zweilous',image,image('Zweilous.jpg')).
resource('Hydreigon',image,image('Hydreigon.jpg')).
resource('Larvesta',image,image('Larvesta.jpg')).
resource('Volcarona',image,image('Volcarona.jpg')).
resource('Cobalion',image,image('Cobalion.jpg')).
resource('Terrakion',image,image('Terrakion.jpg')).
resource('Virizion',image,image('Virizion.jpg')).
resource('Tornadus',image,image('Tornadus.jpg')).
resource('Thundurus',image,image('Thundurus.jpg')).
resource('Reshiram',image,image('Reshiram.jpg')).
resource('Zekrom',image,image('Zekrom.jpg')).
resource('Landorus',image,image('Landorus.jpg')).
resource('Kyurem',image,image('Kyurem.jpg')).
resource('Keldeo',image,image('Keldeo.jpg')).
resource('Meloetta',image,image('Meloetta.jpg')).
resource('Genesect',image,image('Genesect.jpg')).
resource('Chespin',image,image('Chespin.jpg')).
resource('Quilladin',image,image('Quilladin.jpg')).
resource('Chesnaught',image,image('Chesnaught.jpg')).
resource('Fennekin',image,image('Fennekin.jpg')).
resource('Braixen',image,image('Braixen.jpg')).
resource('Delphox',image,image('Delphox.jpg')).
resource('Froakie',image,image('Froakie.jpg')).
resource('Frogadier',image,image('Frogadier.jpg')).
resource('Greninja',image,image('Greninja.jpg')).
resource('Bunnelby',image,image('Bunnelby.jpg')).
resource('Diggersby',image,image('Diggersby.jpg')).
resource('Fletchling',image,image('Fletchling.jpg')).
resource('Fletchinder',image,image('Fletchinder.jpg')).
resource('Talonflame',image,image('Talonflame.jpg')).
resource('Scatterbug',image,image('Scatterbug.jpg')).
resource('Spewpa',image,image('Spewpa.jpg')).
resource('Vivillon',image,image('Vivillon.jpg')).
resource('Litleo',image,image('Litleo.jpg')).
resource('Pyroar',image,image('Pyroar.jpg')).
resource('Flabébé',image,image('Flabébé.jpg')).
resource('Floette',image,image('Floette.jpg')).
resource('Florges',image,image('Florges.jpg')).
resource('Skiddo',image,image('Skiddo.jpg')).
resource('Gogoat',image,image('Gogoat.jpg')).
resource('Pancham',image,image('Pancham.jpg')).
resource('Pangoro',image,image('Pangoro.jpg')).
resource('Furfrou',image,image('Furfrou.jpg')).
resource('Espurr',image,image('Espurr.jpg')).
resource('Meowstic',image,image('Meowstic.jpg')).
resource('Honedge',image,image('Honedge.jpg')).
resource('Doublade',image,image('Doublade.jpg')).
resource('Aegislash',image,image('Aegislash.jpg')).
resource('Spritzee',image,image('Spritzee.jpg')).
resource('Aromatisse',image,image('Aromatisse.jpg')).
resource('Swirlix',image,image('Swirlix.jpg')).
resource('Slurpuff',image,image('Slurpuff.jpg')).
resource('Inkay',image,image('Inkay.jpg')).
resource('Malamar',image,image('Malamar.jpg')).
resource('Binacle',image,image('Binacle.jpg')).
resource('Barbaracle',image,image('Barbaracle.jpg')).
resource('Skrelp',image,image('Skrelp.jpg')).
resource('Dragalge',image,image('Dragalge.jpg')).
resource('Clauncher',image,image('Clauncher.jpg')).
resource('Clawitzer',image,image('Clawitzer.jpg')).
resource('Helioptile',image,image('Helioptile.jpg')).
resource('Heliolisk',image,image('Heliolisk.jpg')).
resource('Tyrunt',image,image('Tyrunt.jpg')).
resource('Tyrantrum',image,image('Tyrantrum.jpg')).
resource('Amaura',image,image('Amaura.jpg')).
resource('Aurorus',image,image('Aurorus.jpg')).
resource('Sylveon',image,image('Sylveon.jpg')).
resource('Hawlucha',image,image('Hawlucha.jpg')).
resource('Dedenne',image,image('Dedenne.jpg')).
resource('Carbink',image,image('Carbink.jpg')).
resource('Goomy',image,image('Goomy.jpg')).
resource('Sliggoo',image,image('Sliggoo.jpg')).
resource('Goodra',image,image('Goodra.jpg')).
resource('Klefki',image,image('Klefki.jpg')).
resource('Phantump',image,image('Phantump.jpg')).
resource('Trevenant',image,image('Trevenant.jpg')).
resource('Pumpkaboo',image,image('Pumpkaboo.jpg')).
resource('Gourgeist',image,image('Gourgeist.jpg')).
resource('Bergmite',image,image('Bergmite.jpg')).
resource('Avalugg',image,image('Avalugg.jpg')).
resource('Noibat',image,image('Noibat.jpg')).
resource('Noivern',image,image('Noivern.jpg')).
resource('Xerneas',image,image('Xerneas.jpg')).
resource('Yveltal',image,image('Yveltal.jpg')).
resource('Zygarde',image,image('Zygarde.jpg')).
resource('Diancie',image,image('Diancie.jpg')).
resource('Hoopa',image,image('Hoopa.jpg')).
resource('Volcanion',image,image('Volcanion.jpg')).
resource('Rowlet',image,image('Rowlet.jpg')).
resource('Dartrix',image,image('Dartrix.jpg')).
resource('Decidueye',image,image('Decidueye.jpg')).
resource('Litten',image,image('Litten.jpg')).
resource('Torracat',image,image('Torracat.jpg')).
resource('Incineroar',image,image('Incineroar.jpg')).
resource('Popplio',image,image('Popplio.jpg')).
resource('Brionne',image,image('Brionne.jpg')).
resource('Primarina',image,image('Primarina.jpg')).
resource('Pikipek',image,image('Pikipek.jpg')).
resource('Trumbeak',image,image('Trumbeak.jpg')).
resource('Toucannon',image,image('Toucannon.jpg')).
resource('Yungoos',image,image('Yungoos.jpg')).
resource('Gumshoos',image,image('Gumshoos.jpg')).
resource('Grubbin',image,image('Grubbin.jpg')).
resource('Charjabug',image,image('Charjabug.jpg')).
resource('Vikavolt',image,image('Vikavolt.jpg')).
resource('Crabrawler',image,image('Crabrawler.jpg')).
resource('Crabominable',image,image('Crabominable.jpg')).
resource('Oricorio',image,image('Oricorio.jpg')).
resource('Cutiefly',image,image('Cutiefly.jpg')).
resource('Ribombee',image,image('Ribombee.jpg')).
resource('Rockruff',image,image('Rockruff.jpg')).
resource('Lycanroc',image,image('Lycanroc.jpg')).
resource('Wishiwashi',image,image('Wishiwashi.jpg')).
resource('Mareanie',image,image('Mareanie.jpg')).
resource('Toxapex',image,image('Toxapex.jpg')).
resource('Mudbray',image,image('Mudbray.jpg')).
resource('Mudsdale',image,image('Mudsdale.jpg')).
resource('Dewpider',image,image('Dewpider.jpg')).
resource('Araquanid',image,image('Araquanid.jpg')).
resource('Fomantis',image,image('Fomantis.jpg')).
resource('Lurantis',image,image('Lurantis.jpg')).
resource('Morelull',image,image('Morelull.jpg')).
resource('Shiinotic',image,image('Shiinotic.jpg')).
resource('Salandit',image,image('Salandit.jpg')).
resource('Salazzle',image,image('Salazzle.jpg')).
resource('Stufful',image,image('Stufful.jpg')).
resource('Bewear',image,image('Bewear.jpg')).
resource('Bounsweet',image,image('Bounsweet.jpg')).
resource('Steenee',image,image('Steenee.jpg')).
resource('Tsareena',image,image('Tsareena.jpg')).
resource('Comfey',image,image('Comfey.jpg')).
resource('Oranguru',image,image('Oranguru.jpg')).
resource('Passimian',image,image('Passimian.jpg')).
resource('Wimpod',image,image('Wimpod.jpg')).
resource('Golisopod',image,image('Golisopod.jpg')).
resource('Sandygast',image,image('Sandygast.jpg')).
resource('Palossand',image,image('Palossand.jpg')).
resource('Pyukumuku',image,image('Pyukumuku.jpg')).
resource('Type:Null',image,image('TypeNull.jpg')).
resource('Silvally',image,image('Silvally.jpg')).
resource('Minior',image,image('Minior.jpg')).
resource('Komala',image,image('Komala.jpg')).
resource('Turtonator',image,image('Turtonator.jpg')).
resource('Togedemaru',image,image('Togedemaru.jpg')).
resource('Mimikyu',image,image('Mimikyu.jpg')).
resource('Bruxish',image,image('Bruxish.jpg')).
resource('Drampa',image,image('Drampa.jpg')).
resource('Dhelmise',image,image('Dhelmise.jpg')).
resource('Jangmo-o',image,image('Jangmo-o.jpg')).
resource('Hakamo-o',image,image('Hakamo-o.jpg')).
resource('Kommo-o',image,image('Kommo-o.jpg')).
resource('Tapu-Koko',image,image('Tapu-Koko.jpg')).
resource('Tapu-Lele',image,image('Tapu-Lele.jpg')).
resource('Tapu-Bulu',image,image('Tapu-Bulu.jpg')).
resource('Tapu-Fini',image,image('Tapu-Fini.jpg')).
resource('Cosmog',image,image('Cosmog.jpg')).
resource('Cosmoem',image,image('Cosmoem.jpg')).
resource('Solgaleo',image,image('Solgaleo.jpg')).
resource('Lunala',image,image('Lunala.jpg')).
resource('Nihilego',image,image('Nihilego.jpg')).
resource('Buzzwole',image,image('Buzzwole.jpg')).
resource('Pheromosa',image,image('Pheromosa.jpg')).
resource('Xurkitree',image,image('Xurkitree.jpg')).
resource('Celesteela',image,image('Celesteela.jpg')).
resource('Kartana',image,image('Kartana.jpg')).
resource('Guzzlord',image,image('Guzzlord.jpg')).
resource('Necrozma',image,image('Necrozma.jpg')).
resource('Magearna',image,image('Magearna.jpg')).
resource('Marshadow',image,image('Marshadow.jpg')).
resource('Poipole',image,image('Poipole.jpg')).
resource('Naganadel',image,image('Naganadel.jpg')).
resource('Stakataka',image,image('Stakataka.jpg')).
resource('Blacephalon',image,image('Blacephalon.jpg')).
resource('Zeraora',image,image('Zeraora.jpg')).
resource('Meltan',image,image('Meltan.jpg')).
resource('Melmetal',image,image('Melmetal.jpg')).

resource('Mega-Charizard-X',image,image('Mega-Charizard-X.jpg')).
resource('Mega-Abomasnow',image,image('Mega-Abomasnow.jpg')).
resource('Mega-Absol',image,image('Mega-Absol.jpg')).
resource('Mega-Aerodactyl',image,image('Mega-Aerodactyl.jpg')).
resource('Mega-Aggron',image,image('Mega-Aggron.jpg')).
resource('Mega-Alakazam',image,image('Mega-Alakazam.jpg')).
resource('Mega-Altaria',image,image('Mega-Altaria.jpg')).
resource('Mega-Ampharos',image,image('Mega-Ampharos.jpg')).
resource('Mega-Audino',image,image('Mega-Audino.jpg')).
resource('Mega-Banette',image,image('Mega-Banette.jpg')).
resource('Mega-Beedrill',image,image('Mega-Beedrill.jpg')).
resource('Mega-Blastoise',image,image('Mega-Blastoise.jpg')).
resource('Mega-Blaziken',image,image('Mega-Blaziken.jpg')).
resource('Mega-Camerupt',image,image('Mega-Camerupt.jpg')).
resource('Mega-Charizard-Y',image,image('Mega-Charizard-Y.jpg')).
resource('Mega-Diancie',image,image('Mega-Diancie.jpg')).
resource('Mega-Gallade',image,image('Mega-Gallade.jpg')).
resource('Mega-Garchomp',image,image('Mega-Garchomp.jpg')).
resource('Mega-Gardevoir',image,image('Mega-Gardevoir.jpg')).
resource('Mega-Gengar',image,image('Mega-Gengar.jpg')).
resource('Mega-Glalie',image,image('Mega-Glalie.jpg')).
resource('Mega-Gyarados',image,image('Mega-Gyarados.jpg')).
resource('Mega-Heracross',image,image('Mega-Heracross.jpg')).
resource('Mega-Houndoom',image,image('Mega-Houndoom.jpg')).
resource('Mega-Kangaskhan',image,image('Mega-Kangaskhan.jpg')).
resource('Mega-Latias',image,image('Mega-Latias.jpg')).
resource('Mega-Latios',image,image('Mega-Latios.jpg')).
resource('Mega-Lopunny',image,image('Mega-Lopunny.jpg')).
resource('Mega-Lucario',image,image('Mega-Lucario.jpg')).
resource('Mega-Manectric',image,image('Mega-Manectric.jpg')).
resource('Mega-Mawile',image,image('Mega-Mawile.jpg')).
resource('Mega-Medicham',image,image('Mega-Medicham.jpg')).
resource('Mega-Metagross',image,image('Mega-Metagross.jpg')).
resource('Mega-Mewtwo-X',image,image('Mega-Mewtwo-X.jpg')).
resource('Mega-Mewtwo-Y',image,image('Mega-Mewtwo-Y.jpg')).
resource('Mega-Pidgeot',image,image('Mega-Pidgeot.jpg')).
resource('Mega-Pinsir',image,image('Mega-Pinsir.jpg')).
resource('Mega-Rayquaza',image,image('Mega-Rayquaza.jpg')).
resource('Mega-Sableye',image,image('Mega-Sableye.jpg')).
resource('Mega-Salamence',image,image('Mega-Salamence.jpg')).
resource('Mega-Sceptile',image,image('Mega-Sceptile.jpg')).
resource('Mega-Scizor',image,image('Mega-Scizor.jpg')).
resource('Mega-Sharpedo',image,image('Mega-Sharpedo.jpg')).
resource('Mega-Slowbro',image,image('Mega-Slowbro.jpg')).
resource('Mega-Steelix',image,image('Mega-Steelix.jpg')).
resource('Mega-Swampert',image,image('Mega-Swampert.jpg')).
resource('Mega-Tyranitar',image,image('Mega-Tyranitar.jpg')).
resource('Mega-Venusaur',image,image('Mega-Venusaur.jpg')).

resource('Marowak-de-Alola',image,image('Marowak-de-Alola.jpg')).
resource('Exeggutor-de-Alola',image,image('Exeggutor-de-Alola.jpg')).
resource('Raichu-de-Alola',image,image('Raichu-de-Alola.jpg')).
resource('Grimer-de-Alola',image,image('Grimer-de-Alola.jpg')).
resource('Muk-de-Alola',image,image('Muk-de-Alola.jpg')).
resource('Rattata-de-Alola',image,image('Rattata-de-Alola.jpg')).
resource('Raticate-de-Alola',image,image('Raticate-de-Alola.jpg')).
resource('Sandshrew-de-Alola',image,image('Sandshrew-de-Alola.jpg')).
resource('Sandslash-de-Alola',image,image('Sandslash-de-Alola.jpg')).
resource('Vulpix-de-Alola',image,image('Vulpix-de-Alola.jpg')).
resource('Ninetales-de-Alola',image,image('Ninetales-de-Alola.jpg')).
resource('Diglett-de-Alola',image,image('Diglett-de-Alola.jpg')).
resource('Dugtrio-de-Alola',image,image('Dugtrio-de-Alola.jpg')).
resource('Meowth-de-Alola',image,image('Meowth-de-Alola.jpg')).
resource('Persian-de-Alola',image,image('Persian-de-Alola.jpg')).
resource('Geodude-de-Alola',image,image('Geodude-de-Alola.jpg')).
resource('Graveler-de-Alola',image,image('Graveler-de-Alola.jpg')).
resource('Golem-de-Alola',image,image('Golem-de-Alola.jpg')).

resource('Rotom-Calor',image,image('Rotom-Calor.jpg')).
resource('Rotom-Frio',image,image('Rotom-Frio.jpg')).
resource('Rotom-Ventilador',image,image('Rotom-Ventilador.jpg')).
resource('Rotom-Corte',image,image('Rotom-Corte.jpg')).
resource('Rotom-Lavado',image,image('Rotom-Lavado.jpg')).

resource('Groudon-Primigenio',image,image('Groudon-Primigenio.jpg')).
resource('Kyogre-Primigenio',image,image('Kyogre-Primigenio.jpg')).

resource('Meloetta-Pirueta',image,image('Meloetta-Pirueta.jpg')).

resource('Keldeo-Resolete',image,image('Keldeo-Resolete.jpg')).

resource('Tornadus-Therian',image,image('Tornadus-Therianjpg')).
resource('Thundurus-Therian',image,image('Thundurus-Therian.jpg')).
resource('Landorus-Therian',image,image('Landorus-Therian.jpg')).

resource('Missingno',image,image('Missingno.jpg')).

sprite('Bulbasaur').
sprite('Ivysaur').
sprite('Venusaur').
sprite('Charmander').
sprite('Charmeleon').
sprite('Charizard').
sprite('Squirtle').
sprite('Wartortle').
sprite('Blastoise').
sprite('Caterpie').
sprite('Metapod').
sprite('Butterfree').
sprite('Weedle').
sprite('Kakuna').
sprite('Beedrill').
sprite('Pidgey').
sprite('Pidgeotto').
sprite('Pidgeot').
sprite('Rattata').
sprite('Raticate').
sprite('Spearow').
sprite('Fearow').
sprite('Ekans').
sprite('Arbok').
sprite('Pikachu').
sprite('Raichu').
sprite('Sandshrew').
sprite('Sandslash').
sprite('Nidoran-F').
sprite('Nidorina').
sprite('Nidoqueen').
sprite('Nidoran-M').
sprite('Nidorino').
sprite('Nidoking').
sprite('Clefairy').
sprite('Clefable').
sprite('Vulpix').
sprite('Ninetales').
sprite('Jigglypuff').
sprite('Wigglytuff').
sprite('Zubat').
sprite('Golbat').
sprite('Oddish').
sprite('Gloom').
sprite('Vileplume').
sprite('Paras').
sprite('Parasect').
sprite('Venonat').
sprite('Venomoth').
sprite('Diglett').
sprite('Dugtrio').
sprite('Meowth').
sprite('Persian').
sprite('Psyduck').
sprite('Golduck').
sprite('Mankey').
sprite('Primeape').
sprite('Growlithe').
sprite('Arcanine').
sprite('Poliwag').
sprite('Poliwhirl').
sprite('Poliwrath').
sprite('Abra').
sprite('Kadabra').
sprite('Alakazam').
sprite('Machop').
sprite('Machoke').
sprite('Machamp').
sprite('Bellsprout').
sprite('Weepinbell').
sprite('Victreebel').
sprite('Tentacool').
sprite('Tentacruel').
sprite('Geodude').
sprite('Graveler').
sprite('Golem').
sprite('Ponyta').
sprite('Rapidash').
sprite('Slowpoke').
sprite('Slowbro').
sprite('Magnemite').
sprite('Magneton').
sprite('Farfetchd').
sprite('Doduo').
sprite('Dodrio').
sprite('Seel').
sprite('Dewgong').
sprite('Grimer').
sprite('Muk').
sprite('Shellder').
sprite('Cloyster').
sprite('Gastly').
sprite('Haunter').
sprite('Gengar').
sprite('Onix').
sprite('Drowzee').
sprite('Hypno').
sprite('Krabby').
sprite('Kingler').
sprite('Voltorb').
sprite('Electrode').
sprite('Exeggcute').
sprite('Exeggutor').
sprite('Cubone').
sprite('Marowak').
sprite('Hitmonlee').
sprite('Hitmonchan').
sprite('Lickitung').
sprite('Koffing').
sprite('Weezing').
sprite('Rhyhorn').
sprite('Rhydon').
sprite('Chansey').
sprite('Tangela').
sprite('Kangaskhan').
sprite('Horsea').
sprite('Seadra').
sprite('Goldeen').
sprite('Seaking').
sprite('Staryu').
sprite('Starmie').
sprite('Mr.Mime').
sprite('Scyther').
sprite('Jynx').
sprite('Electabuzz').
sprite('Magmar').
sprite('Pinsir').
sprite('Tauros').
sprite('Magikarp').
sprite('Gyarados').
sprite('Lapras').
sprite('Ditto').
sprite('Eevee').
sprite('Vaporeon').
sprite('Jolteon').
sprite('Flareon').
sprite('Porygon').
sprite('Omanyte').
sprite('Omastar').
sprite('Kabuto').
sprite('Kabutops').
sprite('Aerodactyl').
sprite('Snorlax').
sprite('Articuno').
sprite('Zapdos').
sprite('Moltres').
sprite('Dratini').
sprite('Dragonair').
sprite('Dragonite').
sprite('Mewtwo').
sprite('Mew').
sprite('Chikorita').
sprite('Bayleef').
sprite('Meganium').
sprite('Cyndaquil').
sprite('Quilava').
sprite('Typhlosion').
sprite('Totodile').
sprite('Croconaw').
sprite('Feraligatr').
sprite('Sentret').
sprite('Furret').
sprite('Hoothoot').
sprite('Noctowl').
sprite('Ledyba').
sprite('Ledian').
sprite('Spinarak').
sprite('Ariados').
sprite('Crobat').
sprite('Chinchou').
sprite('Lanturn').
sprite('Pichu').
sprite('Cleffa').
sprite('Igglybuff').
sprite('Togepi').
sprite('Togetic').
sprite('Natu').
sprite('Xatu').
sprite('Mareep').
sprite('Flaaffy').
sprite('Ampharos').
sprite('Bellossom').
sprite('Marill').
sprite('Azumarill').
sprite('Sudowoodo').
sprite('Politoed').
sprite('Hoppip').
sprite('Skiploom').
sprite('Jumpluff').
sprite('Aipom').
sprite('Sunkern').
sprite('Sunflora').
sprite('Yanma').
sprite('Wooper').
sprite('Quagsire').
sprite('Espeon').
sprite('Umbreon').
sprite('Murkrow').
sprite('Slowking').
sprite('Misdreavus').
sprite('Unown').
sprite('Wobbuffet').
sprite('Girafarig').
sprite('Pineco').
sprite('Forretress').
sprite('Dunsparce').
sprite('Gligar').
sprite('Steelix').
sprite('Snubbull').
sprite('Granbull').
sprite('Qwilfish').
sprite('Scizor').
sprite('Shuckle').
sprite('Heracross').
sprite('Sneasel').
sprite('Teddiursa').
sprite('Ursaring').
sprite('Slugma').
sprite('Magcargo').
sprite('Swinub').
sprite('Piloswine').
sprite('Corsola').
sprite('Remoraid').
sprite('Octillery').
sprite('Delibird').
sprite('Mantine').
sprite('Skarmory').
sprite('Houndour').
sprite('Houndoom').
sprite('Kingdra').
sprite('Phanpy').
sprite('Donphan').
sprite('Porygon2').
sprite('Stantler').
sprite('Smeargle').
sprite('Tyrogue').
sprite('Hitmontop').
sprite('Smoochum').
sprite('Elekid').
sprite('Magby').
sprite('Miltank').
sprite('Blissey').
sprite('Raikou').
sprite('Entei').
sprite('Suicune').
sprite('Larvitar').
sprite('Pupitar').
sprite('Tyranitar').
sprite('Lugia').
sprite('Ho-Oh').
sprite('Celebi').
sprite('Treecko').
sprite('Grovyle').
sprite('Sceptile').
sprite('Torchic').
sprite('Combusken').
sprite('Blaziken').
sprite('Mudkip').
sprite('Marshtomp').
sprite('Swampert').
sprite('Poochyena').
sprite('Mightyena').
sprite('Zigzagoon').
sprite('Linoone').
sprite('Wurmple').
sprite('Silcoon').
sprite('Beautifly').
sprite('Cascoon').
sprite('Dustox').
sprite('Lotad').
sprite('Lombre').
sprite('Ludicolo').
sprite('Seedot').
sprite('Nuzleaf').
sprite('Shiftry').
sprite('Taillow').
sprite('Swellow').
sprite('Wingull').
sprite('Pelipper').
sprite('Ralts').
sprite('Kirlia').
sprite('Gardevoir').
sprite('Surskit').
sprite('Masquerain').
sprite('Shroomish').
sprite('Breloom').
sprite('Slakoth').
sprite('Vigoroth').
sprite('Slaking').
sprite('Nincada').
sprite('Ninjask').
sprite('Shedinja').
sprite('Whismur').
sprite('Loudred').
sprite('Exploud').
sprite('Makuhita').
sprite('Hariyama').
sprite('Azurill').
sprite('Nosepass').
sprite('Skitty').
sprite('Delcatty').
sprite('Sableye').
sprite('Mawile').
sprite('Aron').
sprite('Lairon').
sprite('Aggron').
sprite('Meditite').
sprite('Medicham').
sprite('Electrike').
sprite('Manectric').
sprite('Plusle').
sprite('Minun').
sprite('Volbeat').
sprite('Illumise').
sprite('Roselia').
sprite('Gulpin').
sprite('Swalot').
sprite('Carvanha').
sprite('Sharpedo').
sprite('Wailmer').
sprite('Wailord').
sprite('Numel').
sprite('Camerupt').
sprite('Torkoal').
sprite('Spoink').
sprite('Grumpig').
sprite('Spinda').
sprite('Trapinch').
sprite('Vibrava').
sprite('Flygon').
sprite('Cacnea').
sprite('Cacturne').
sprite('Swablu').
sprite('Altaria').
sprite('Zangoose').
sprite('Seviper').
sprite('Lunatone').
sprite('Solrock').
sprite('Barboach').
sprite('Whiscash').
sprite('Corphish').
sprite('Crawdaunt').
sprite('Baltoy').
sprite('Claydol').
sprite('Lileep').
sprite('Cradily').
sprite('Anorith').
sprite('Armaldo').
sprite('Feebas').
sprite('Milotic').
sprite('Castform').
sprite('Kecleon').
sprite('Shuppet').
sprite('Banette').
sprite('Duskull').
sprite('Dusclops').
sprite('Tropius').
sprite('Chimecho').
sprite('Absol').
sprite('Wynaut').
sprite('Snorunt').
sprite('Glalie').
sprite('Spheal').
sprite('Sealeo').
sprite('Walrein').
sprite('Clamperl').
sprite('Huntail').
sprite('Gorebyss').
sprite('Relicanth').
sprite('Luvdisc').
sprite('Bagon').
sprite('Shelgon').
sprite('Salamence').
sprite('Beldum').
sprite('Metang').
sprite('Metagross').
sprite('Regirock').
sprite('Regice').
sprite('Registeel').
sprite('Latias').
sprite('Latios').
sprite('Kyogre').
sprite('Groudon').
sprite('Rayquaza').
sprite('Jirachi').
sprite('Deoxys').
sprite('Turtwig').
sprite('Grotle').
sprite('Torterra').
sprite('Chimchar').
sprite('Monferno').
sprite('Infernape').
sprite('Piplup').
sprite('Prinplup').
sprite('Empoleon').
sprite('Starly').
sprite('Staravia').
sprite('Staraptor').
sprite('Bidoof').
sprite('Bibarel').
sprite('Kricketot').
sprite('Kricketune').
sprite('Shinx').
sprite('Luxio').
sprite('Luxray').
sprite('Budew').
sprite('Roserade').
sprite('Cranidos').
sprite('Rampardos').
sprite('Shieldon').
sprite('Bastiodon').
sprite('Burmy').
sprite('Wormadam').
sprite('Mothim').
sprite('Combee').
sprite('Vespiquen').
sprite('Pachirisu').
sprite('Buizel').
sprite('Floatzel').
sprite('Cherubi').
sprite('Cherrim').
sprite('Shellos').
sprite('Gastrodon').
sprite('Ambipom').
sprite('Drifloon').
sprite('Drifblim').
sprite('Buneary').
sprite('Lopunny').
sprite('Mismagius').
sprite('Honchkrow').
sprite('Glameow').
sprite('Purugly').
sprite('Chingling').
sprite('Stunky').
sprite('Skuntank').
sprite('Bronzor').
sprite('Bronzong').
sprite('Bonsly').
sprite('Mime-Jr.').
sprite('Happiny').
sprite('Chatot').
sprite('Spiritomb').
sprite('Gible').
sprite('Gabite').
sprite('Garchomp').
sprite('Munchlax').
sprite('Riolu').
sprite('Lucario').
sprite('Hippopotas').
sprite('Hippowdon').
sprite('Skorupi').
sprite('Drapion').
sprite('Croagunk').
sprite('Toxicroak').
sprite('Carnivine').
sprite('Finneon').
sprite('Lumineon').
sprite('Mantyke').
sprite('Snover').
sprite('Abomasnow').
sprite('Weavile').
sprite('Magnezone').
sprite('Lickilicky').
sprite('Rhyperior').
sprite('Tangrowth').
sprite('Electivire').
sprite('Magmortar').
sprite('Togekiss').
sprite('Yanmega').
sprite('Leafeon').
sprite('Glaceon').
sprite('Gliscor').
sprite('Mamoswine').
sprite('Porygon-Z').
sprite('Gallade').
sprite('Probopass').
sprite('Dusknoir').
sprite('Froslass').
sprite('Rotom').
sprite('Uxie').
sprite('Mesprit').
sprite('Azelf').
sprite('Dialga').
sprite('Palkia').
sprite('Heatran').
sprite('Regigigas').
sprite('Giratina').
sprite('Cresselia').
sprite('Phione').
sprite('Manaphy').
sprite('Darkrai').
sprite('Shaymin').
sprite('Arceus').
sprite('Victini').
sprite('Snivy').
sprite('Servine').
sprite('Serperior').
sprite('Tepig').
sprite('Pignite').
sprite('Emboar').
sprite('Oshawott').
sprite('Dewott').
sprite('Samurott').
sprite('Patrat').
sprite('Watchog').
sprite('Lillipup').
sprite('Herdier').
sprite('Stoutland').
sprite('Purrloin').
sprite('Liepard').
sprite('Pansage').
sprite('Simisage').
sprite('Pansear').
sprite('Simisear').
sprite('Panpour').
sprite('Simipour').
sprite('Munna').
sprite('Musharna').
sprite('Pidove').
sprite('Tranquill').
sprite('Unfezant').
sprite('Blitzle').
sprite('Zebstrika').
sprite('Roggenrola').
sprite('Boldore').
sprite('Gigalith').
sprite('Woobat').
sprite('Swoobat').
sprite('Drilbur').
sprite('Excadrill').
sprite('Audino').
sprite('Timburr').
sprite('Gurdurr').
sprite('Conkeldurr').
sprite('Tympole').
sprite('Palpitoad').
sprite('Seismitoad').
sprite('Throh').
sprite('Sawk').
sprite('Sewaddle').
sprite('Swadloon').
sprite('Leavanny').
sprite('Venipede').
sprite('Whirlipede').
sprite('Scolipede').
sprite('Cottonee').
sprite('Whimsicott').
sprite('Petilil').
sprite('Lilligant').
sprite('Basculin').
sprite('Sandile').
sprite('Krokorok').
sprite('Krookodile').
sprite('Darumaka').
sprite('Darmanitan').
sprite('Maractus').
sprite('Dwebble').
sprite('Crustle').
sprite('Scraggy').
sprite('Scrafty').
sprite('Sigilyph').
sprite('Yamask').
sprite('Cofagrigus').
sprite('Tirtouga').
sprite('Carracosta').
sprite('Archen').
sprite('Archeops').
sprite('Trubbish').
sprite('Garbodor').
sprite('Zorua').
sprite('Zoroark').
sprite('Minccino').
sprite('Cinccino').
sprite('Gothita').
sprite('Gothorita').
sprite('Gothitelle').
sprite('Solosis').
sprite('Duosion').
sprite('Reuniclus').
sprite('Ducklett').
sprite('Swanna').
sprite('Vanillite').
sprite('Vanillish').
sprite('Vanilluxe').
sprite('Deerling').
sprite('Sawsbuck').
sprite('Emolga').
sprite('Karrablast').
sprite('Escavalier').
sprite('Foongus').
sprite('Amoonguss').
sprite('Frillish').
sprite('Jellicent').
sprite('Alomomola').
sprite('Joltik').
sprite('Galvantula').
sprite('Ferroseed').
sprite('Ferrothorn').
sprite('Klink').
sprite('Klang').
sprite('Klinklang').
sprite('Tynamo').
sprite('Eelektrik').
sprite('Eelektross').
sprite('Elgyem').
sprite('Beheeyem').
sprite('Litwick').
sprite('Lampent').
sprite('Chandelure').
sprite('Axew').
sprite('Fraxure').
sprite('Haxorus').
sprite('Cubchoo').
sprite('Beartic').
sprite('Cryogonal').
sprite('Shelmet').
sprite('Accelgor').
sprite('Stunfisk').
sprite('Mienfoo').
sprite('Mienshao').
sprite('Druddigon').
sprite('Golett').
sprite('Golurk').
sprite('Pawniard').
sprite('Bisharp').
sprite('Bouffalant').
sprite('Rufflet').
sprite('Braviary').
sprite('Vullaby').
sprite('Mandibuzz').
sprite('Heatmor').
sprite('Durant').
sprite('Deino').
sprite('Zweilous').
sprite('Hydreigon').
sprite('Larvesta').
sprite('Volcarona').
sprite('Cobalion').
sprite('Terrakion').
sprite('Virizion').
sprite('Tornadus').
sprite('Thundurus').
sprite('Reshiram').
sprite('Zekrom').
sprite('Landorus').
sprite('Kyurem').
sprite('Keldeo').
sprite('Meloetta').
sprite('Genesect').
sprite('Chespin').
sprite('Quilladin').
sprite('Chesnaught').
sprite('Fennekin').
sprite('Braixen').
sprite('Delphox').
sprite('Froakie').
sprite('Frogadier').
sprite('Greninja').
sprite('Bunnelby').
sprite('Diggersby').
sprite('Fletchling').
sprite('Fletchinder').
sprite('Talonflame').
sprite('Scatterbug').
sprite('Spewpa').
sprite('Vivillon').
sprite('Litleo').
sprite('Pyroar').
sprite('Flabébé').
sprite('Floette').
sprite('Florges').
sprite('Skiddo').
sprite('Gogoat').
sprite('Pancham').
sprite('Pangoro').
sprite('Furfrou').
sprite('Espurr').
sprite('Meowstic').
sprite('Honedge').
sprite('Doublade').
sprite('Aegislash').
sprite('Spritzee').
sprite('Aromatisse').
sprite('Swirlix').
sprite('Slurpuff').
sprite('Inkay').
sprite('Malamar').
sprite('Binacle').
sprite('Barbaracle').
sprite('Skrelp').
sprite('Dragalge').
sprite('Clauncher').
sprite('Clawitzer').
sprite('Helioptile').
sprite('Heliolisk').
sprite('Tyrunt').
sprite('Tyrantrum').
sprite('Amaura').
sprite('Aurorus').
sprite('Sylveon').
sprite('Hawlucha').
sprite('Dedenne').
sprite('Carbink').
sprite('Goomy').
sprite('Sliggoo').
sprite('Goodra').
sprite('Klefki').
sprite('Phantump').
sprite('Trevenant').
sprite('Pumpkaboo').
sprite('Gourgeist').
sprite('Bergmite').
sprite('Avalugg').
sprite('Noibat').
sprite('Noivern').
sprite('Xerneas').
sprite('Yveltal').
sprite('Zygarde').
sprite('Diancie').
sprite('Hoopa').
sprite('Volcanion').
sprite('Rowlet').
sprite('Dartrix').
sprite('Decidueye').
sprite('Litten').
sprite('Torracat').
sprite('Incineroar').
sprite('Popplio').
sprite('Brionne').
sprite('Primarina').
sprite('Pikipek').
sprite('Trumbeak').
sprite('Toucannon').
sprite('Yungoos').
sprite('Gumshoos').
sprite('Grubbin').
sprite('Charjabug').
sprite('Vikavolt').
sprite('Crabrawler').
sprite('Crabominable').
sprite('Oricorio').
sprite('Cutiefly').
sprite('Ribombee').
sprite('Rockruff').
sprite('Lycanroc').
sprite('Wishiwashi').
sprite('Mareanie').
sprite('Toxapex').
sprite('Mudbray').
sprite('Mudsdale').
sprite('Dewpider').
sprite('Araquanid').
sprite('Fomantis').
sprite('Lurantis').
sprite('Morelull').
sprite('Shiinotic').
sprite('Salandit').
sprite('Salazzle').
sprite('Stufful').
sprite('Bewear').
sprite('Bounsweet').
sprite('Steenee').
sprite('Tsareena').
sprite('Comfey').
sprite('Oranguru').
sprite('Passimian').
sprite('Wimpod').
sprite('Golisopod').
sprite('Sandygast').
sprite('Palossand').
sprite('Pyukumuku').
sprite('Type:Null').
sprite('Silvally').
sprite('Minior').
sprite('Komala').
sprite('Turtonator').
sprite('Togedemaru').
sprite('Mimikyu').
sprite('Bruxish').
sprite('Drampa').
sprite('Dhelmise').
sprite('Jangmo-o').
sprite('Hakamo-o').
sprite('Kommo-o').
sprite('Tapu-Koko').
sprite('Tapu-Lele').
sprite('Tapu-Bulu').
sprite('Tapu-Fini').
sprite('Cosmog').
sprite('Cosmoem').
sprite('Solgaleo').
sprite('Lunala').
sprite('Nihilego').
sprite('Buzzwole').
sprite('Pheromosa').
sprite('Xurkitree').
sprite('Celesteela').
sprite('Kartana').
sprite('Guzzlord').
sprite('Necrozma').
sprite('Magearna').
sprite('Marshadow').
sprite('Poipole').
sprite('Naganadel').
sprite('Stakataka').
sprite('Blacephalon').
sprite('Zeraora').
sprite('Meltan').
sprite('Melmetal').

sprite('Mega-Abomasnow').
sprite('Mega-Absol').
sprite('Mega-Aerodactyl').
sprite('Mega-Aggron').
sprite('Mega-Alakazam').
sprite('Mega-Altaria').
sprite('Mega-Ampharos').
sprite('Mega-Audino').
sprite('Mega-Banette').
sprite('Mega-Beedrill').
sprite('Mega-Blastoise').
sprite('Mega-Blaziken').
sprite('Mega-Camerupt').
sprite('Mega-Charizard-X').
sprite('Mega-Charizard-Y').
sprite('Mega-Diancie').
sprite('Mega-Gallade').
sprite('Mega-Garchomp').
sprite('Mega-Gardevoir').
sprite('Mega-Gengar').
sprite('Mega-Glalie').
sprite('Mega-Gyarados').
sprite('Mega-Heracross').
sprite('Mega-Houndoom').
sprite('Mega-Kangaskhan').
sprite('Mega-Latias').
sprite('Mega-Latios').
sprite('Mega-Lopunny').
sprite('Mega-Lucario').
sprite('Mega-Manectric').
sprite('Mega-Mawile').
sprite('Mega-Medicham').
sprite('Mega-Metagross').
sprite('Mega-Mewtwo-X').
sprite('Mega-Mewtwo-Y').
sprite('Mega-Pidgeot').
sprite('Mega-Pinsir').
sprite('Mega-Rayquaza').
sprite('Mega-Sableye').
sprite('Mega-Salamence').
sprite('Mega-Sceptile').
sprite('Mega-Scizor').
sprite('Mega-Sharpedo').
sprite('Mega-Slowbro').
sprite('Mega-Steelix').
sprite('Mega-Swampert').
sprite('Mega-Tyranitar').
sprite('Mega-Venusaur').

sprite('Marowak-de-Alola').
sprite('Exeggutor-de-Alola').
sprite('Raichu-de-Alola').
sprite('Grimer-de-Alola').
sprite('Muk-de-Alola').
sprite('Rattata-de-Alola').
sprite('Raticate-de-Alola').
sprite('Sandshrew-de-Alola').
sprite('Sandslash-de-Alola').
sprite('Vulpix-de-Alola').
sprite('Ninetales-de-Alola').
sprite('Diglett-de-Alola').
sprite('Dugtrio-de-Alola').
sprite('Meowth-de-Alola').
sprite('Persian-de-Alola').
sprite('Geodude-de-Alola').
sprite('Graveler-de-Alola').
sprite('Golem-de-Alola').

sprite('Rotom-Calor').
sprite('Rotom-Frio').
sprite('Rotom-Ventilador').
sprite('Rotom-Corte').
sprite('Rotom-Lavado').

sprite('Groudon-Primigenio').
sprite('Kyogre-Primigenio').

sprite('Meloetta-Pirueta').
sprite('Keldeo-Resolete').
sprite('Tornadus-Therian').
sprite('Thundurus-Therian').
sprite('Landorus-Therian').

sprite('Missingno').