tipo('Abomasnow','Planta','Hielo').
tipo('Abra','Psiquico','Ninguno').
tipo('Absol','Siniestro','Ninguno').
tipo('Accelgor','Bicho','Ninguno').
tipo('Aegislash','Acero','Fantasma').
tipo('Aerodactyl','Roca','Volador').
tipo('Aggron','Acero','Roca').
tipo('Aipom','Normal','Ninguno').
tipo('Alakazam','Psiquico','Ninguno').
tipo('Alomomola','Agua','Ninguno').
tipo('Altaria','Dragon','Volador').
tipo('Amaura','Roca','Hielo').
tipo('Ambipom','Normal','Ninguno').
tipo('Amoonguss','Planta','Veneno').
tipo('Ampharos','Electrico','Ninguno').
tipo('Anorith','Roca','Bicho').
tipo('Araquanid','Agua','Bicho').
tipo('Arbok','Veneno','Ninguno').
tipo('Arcanine','Fuego','Ninguno').
tipo('Arceus','Normal','Ninguno').
tipo('Archen','Roca','Volador').
tipo('Archeops','Roca','Volador').
tipo('Ariados','Bicho','Veneno').
tipo('Armaldo','Roca','Bicho').
tipo('Aromatisse','Hada','Ninguno').
tipo('Aron','Acero','Roca').
tipo('Articuno','Hielo','Volador').
tipo('Audino','Normal','Ninguno').
tipo('Aurorus','Roca','Hielo').
tipo('Avalugg','Hielo','Ninguno').
tipo('Axew','Dragon','Ninguno').
tipo('Azelf','Psiquico','Ninguno').
tipo('Azumarill','Agua','Hada').
tipo('Azurill','Normal','Hada').
tipo('Bagon','Dragon','Ninguno').
tipo('Baltoy','Tierra','Psiquico').
tipo('Banette','Fantasma','Ninguno').
tipo('Barbaracle','Roca','Agua').
tipo('Barboach','Agua','Tierra').
tipo('Basculin','Agua','Ninguno').
tipo('Bastiodon','Roca','Acero').
tipo('Bayleef','Planta','Ninguno').
tipo('Beartic','Hielo','Ninguno').
tipo('Beautifly','Bicho','Volador').
tipo('Beedrill','Bicho','Veneno').
tipo('Beheeyem','Psiquico','Ninguno').
tipo('Beldum','Acero','Psiquico').
tipo('Bellossom','Planta','Ninguno').
tipo('Bellsprout','Planta','Veneno').
tipo('Bergmite','Hielo','Ninguno').
tipo('Bewear','Normal','Lucha').
tipo('Bibarel','Normal','Agua').
tipo('Bidoof','Normal','Ninguno').
tipo('Binacle','Roca','Agua').
tipo('Bisharp','Siniestro','Acero').
tipo('Blacephalon','Fuego','Fantasma').
tipo('Blastoise','Agua','Ninguno').
tipo('Blaziken','Fuego','Lucha').
tipo('Blissey','Normal','Ninguno').
tipo('Blitzle','Electrico','Ninguno').
tipo('Boldore','Roca','Ninguno').
tipo('Bonsly','Roca','Ninguno').
tipo('Bouffalant','Normal','Ninguno').
tipo('Bounsweet','Planta','Ninguno').
tipo('Braixen','Fuego','Ninguno').
tipo('Braviary','Normal','Volador').
tipo('Breloom','Planta','Lucha').
tipo('Brionne','Agua','Ninguno').
tipo('Bronzong','Acero','Psiquico').
tipo('Bronzor','Acero','Psiquico').
tipo('Bruxish','Agua','Psiquico').
tipo('Budew','Planta','Veneno').
tipo('Buizel','Agua','Ninguno').
tipo('Bulbasaur','Planta','Veneno').
tipo('Buneary','Normal','Ninguno').
tipo('Bunnelby','Normal','Ninguno').
tipo('Burmy','Bicho','Ninguno').
tipo('Burmy','Bicho','Ninguno').
tipo('Burmy','Bicho','Ninguno').
tipo('Butterfree','Bicho','Volador').
tipo('Buzzwole','Bicho','Lucha').
tipo('Cacnea','Planta','Ninguno').
tipo('Cacturne','Planta','Siniestro').
tipo('Camerupt','Fuego','Tierra').
tipo('Carbink','Roca','Hada').
tipo('Carnivine','Planta','Ninguno').
tipo('Carracosta','Agua','Roca').
tipo('Carvanha','Agua','Siniestro').
tipo('Cascoon','Bicho','Ninguno').
tipo('Castform','Normal','Ninguno').
tipo('Castform-Rainy','Agua','Ninguno').
tipo('Castform-Snowy','Hielo','Ninguno').
tipo('Castform-Sunny','Fuego','Ninguno').
tipo('Caterpie','Bicho','Ninguno').
tipo('Celebi','Psiquico','Planta').
tipo('Celesteela','Acero','Volador').
tipo('Chandelure','Fantasma','Fuego').
tipo('Chansey','Normal','Ninguno').
tipo('Charizard','Fuego','Volador').
tipo('Charjabug','Bicho','Electrico').
tipo('Charmander','Fuego','Ninguno').
tipo('Charmeleon','Fuego','Ninguno').
tipo('Chatot','Normal','Volador').
tipo('Cherrim','Planta','Ninguno').
tipo('Cherubi','Planta','Ninguno').
tipo('Chesnaught','Planta','Lucha').
tipo('Chespin','Planta','Ninguno').
tipo('Chikorita','Planta','Ninguno').
tipo('Chimchar','Fuego','Ninguno').
tipo('Chimecho','Psiquico','Ninguno').
tipo('Chinchou','Agua','Electrico').
tipo('Chingling','Psiquico','Ninguno').
tipo('Cinccino','Normal','Ninguno').
tipo('Clamperl','Agua','Ninguno').
tipo('Clauncher','Agua','Ninguno').
tipo('Clawitzer','Agua','Ninguno').
tipo('Claydol','Tierra','Psiquico').
tipo('Clefable','Hada','Ninguno').
tipo('Clefairy','Hada','Ninguno').
tipo('Cleffa','Hada','Ninguno').
tipo('Cloyster','Agua','Hielo').
tipo('Cobalion','Acero','Lucha').
tipo('Cofagrigus','Fantasma','Ninguno').
tipo('Combee','Bicho','Volador').
tipo('Combusken','Fuego','Lucha').
tipo('Comfey','Hada','Ninguno').
tipo('Conkeldurr','Lucha','Ninguno').
tipo('Corphish','Agua','Ninguno').
tipo('Corsola','Agua','Roca').
tipo('Cosmoem','Psiquico','Ninguno').
tipo('Cosmog','Psiquico','Ninguno').
tipo('Cottonee','Planta','Hada').
tipo('Crabominable','Lucha','Hielo').
tipo('Crabrawler','Lucha','Ninguno').
tipo('Cradily','Roca','Planta').
tipo('Cranidos','Roca','Ninguno').
tipo('Crawdaunt','Agua','Siniestro').
tipo('Cresselia','Psiquico','Ninguno').
tipo('Croagunk','Veneno','Lucha').
tipo('Crobat','Veneno','Volador').
tipo('Croconaw','Agua','Ninguno').
tipo('Crustle','Bicho','Roca').
tipo('Cryogonal','Hielo','Ninguno').
tipo('Cubchoo','Hielo','Ninguno').
tipo('Cubone','Tierra','Ninguno').
tipo('Cutiefly','Bicho','Hada').
tipo('Cyndaquil','Fuego','Ninguno').
tipo('Darkrai','Siniestro','Ninguno').
tipo('Darmanitan','Fuego','Ninguno').
tipo('Darmanitan','Fuego','Psiquico').
tipo('Dartrix','Planta','Volador').
tipo('Darumaka','Fuego','Ninguno').
tipo('Decidueye','Planta','Fantasma').
tipo('Dedenne','Electrico','Hada').
tipo('Deerling','Normal','Planta').
tipo('Deino','Siniestro','Dragon').
tipo('Delcatty','Normal','Ninguno').
tipo('Delibird','Hielo','Volador').
tipo('Delphox','Fuego','Psiquico').
tipo('Deoxys','Psiquico','Ninguno').
tipo('Dewgong','Agua','Hielo').
tipo('Dewott','Agua','Ninguno').
tipo('Dewpider','Agua','Bicho').
tipo('Dhelmise','Fantasma','Planta').
tipo('Dialga','Acero','Dragon').
tipo('Diancie','Roca','Hada').
tipo('Diggersby','Normal','Tierra').
tipo('Diglett','Tierra','Ninguno').
tipo('Diglett-de-Alola','Tierra','Acero').
tipo('Ditto','Normal','Ninguno').
tipo('Dodrio','Normal','Volador').
tipo('Doduo','Normal','Volador').
tipo('Donphan','Tierra','Ninguno').
tipo('Doublade','Acero','Fantasma').
tipo('Dragalge','Veneno','Dragon').
tipo('Dragonair','Dragon','Ninguno').
tipo('Dragonite','Dragon','Volador').
tipo('Drampa','Normal','Dragon').
tipo('Drapion','Veneno','Siniestro').
tipo('Dratini','Dragon','Ninguno').
tipo('Drifblim','Fantasma','Volador').
tipo('Drifloon','Fantasma','Volador').
tipo('Drilbur','Tierra','Ninguno').
tipo('Drowzee','Psiquico','Ninguno').
tipo('Druddigon','Dragon','Ninguno').
tipo('Ducklett','Agua','Volador').
tipo('Dugtrio','Tierra','Ninguno').
tipo('Dugtrio-de-Alola','Tierra','Acero').
tipo('Dunsparce','Normal','Ninguno').
tipo('Duosion','Psiquico','Ninguno').
tipo('Durant','Bicho','Acero').
tipo('Dusclops','Fantasma','Ninguno').
tipo('Dusknoir','Fantasma','Ninguno').
tipo('Duskull','Fantasma','Ninguno').
tipo('Dustox','Bicho','Veneno').
tipo('Dwebble','Bicho','Roca').
tipo('Eelektrik','Electrico','Ninguno').
tipo('Eelektross','Electrico','Ninguno').
tipo('Eevee','Normal','Ninguno').
tipo('Ekans','Veneno','Ninguno').
tipo('Electabuzz','Electrico','Ninguno').
tipo('Electivire','Electrico','Ninguno').
tipo('Electrike','Electrico','Ninguno').
tipo('Electrode','Electrico','Ninguno').
tipo('Elekid','Electrico','Ninguno').
tipo('Elgyem','Psiquico','Ninguno').
tipo('Emboar','Fuego','Lucha').
tipo('Emolga','Electrico','Volador').
tipo('Empoleon','Agua','Acero').
tipo('Entei','Fuego','Ninguno').
tipo('Escavalier','Bicho','Acero').
tipo('Espeon','Psiquico','Ninguno').
tipo('Espurr','Psiquico','Ninguno').
tipo('Excadrill','Tierra','Acero').
tipo('Exeggcute','Planta','Psiquico').
tipo('Exeggutor','Planta','Psiquico').
tipo('Exeggutor-de-Alola','Planta','Dragon').
tipo('Exploud','Normal','Ninguno').
tipo('Farfetchd','Normal','Volador').
tipo('Fearow','Normal','Volador').
tipo('Feebas','Agua','Ninguno').
tipo('Fennekin','Fuego','Ninguno').
tipo('Feraligatr','Agua','Ninguno').
tipo('Ferroseed','Planta','Acero').
tipo('Ferrothorn','Planta','Acero').
tipo('Finneon','Agua','Ninguno').
tipo('Flaaffy','Electrico','Ninguno').
tipo('Flabebe','Hada','Ninguno').
tipo('Flareon','Fuego','Ninguno').
tipo('Fletchinder','Fuego','Volador').
tipo('Fletchling','Normal','Volador').
tipo('Floatzel','Agua','Ninguno').
tipo('Floette','Hada','Ninguno').
tipo('Florges','Hada','Ninguno').
tipo('Flygon','Tierra','Dragon').
tipo('Fomantis','Planta','Ninguno').
tipo('Foongus','Planta','Veneno').
tipo('Forretress','Bicho','Acero').
tipo('Fraxure','Dragon','Ninguno').
tipo('Frillish','Agua','Fantasma').
tipo('Froakie','Agua','Ninguno').
tipo('Frogadier','Agua','Ninguno').
tipo('Froslass','Hielo','Fantasma').
tipo('Furfrou','Normal','Ninguno').
tipo('Furret','Normal','Ninguno').
tipo('Gabite','Dragon','Tierra').
tipo('Gallade','Psiquico','Lucha').
tipo('Galvantula','Bicho','Electrico').
tipo('Garbodor','Veneno','Ninguno').
tipo('Garchomp','Dragon','Tierra').
tipo('Gardevoir','Psiquico','Hada').
tipo('Gastly','Fantasma','Veneno').
tipo('Gastrodon','Agua','Tierra').
tipo('Genesect','Bicho','Acero').
tipo('Gengar','Fantasma','Veneno').
tipo('Geodude','Roca','Tierra').
tipo('Geodude-de-Alola','Roca','Electrico').
tipo('Gible','Dragon','Tierra').
tipo('Gigalith','Roca','Ninguno').
tipo('Girafarig','Normal','Psiquico').
tipo('Giratina','Fantasma','Dragon').
tipo('Glaceon','Hielo','Ninguno').
tipo('Glalie','Hielo','Ninguno').
tipo('Glameow','Normal','Ninguno').
tipo('Gligar','Tierra','Volador').
tipo('Gliscor','Tierra','Volador').
tipo('Gloom','Planta','Veneno').
tipo('Gogoat','Planta','Ninguno').
tipo('Golbat','Veneno','Volador').
tipo('Goldeen','Agua','Ninguno').
tipo('Golduck','Agua','Ninguno').
tipo('Golem','Roca','Tierra').
tipo('Golem-de-Alola','Roca','Electrico').
tipo('Golett','Tierra','Fantasma').
tipo('Golisopod','Bicho','Agua').
tipo('Golurk','Tierra','Fantasma').
tipo('Goodra','Dragon','Ninguno').
tipo('Goomy','Dragon','Ninguno').
tipo('Gorebyss','Agua','Ninguno').
tipo('Gothita','Psiquico','Ninguno').
tipo('Gothitelle','Psiquico','Ninguno').
tipo('Gothorita','Psiquico','Ninguno').
tipo('Gourgeist','Fantasma','Planta').
tipo('Granbull','Hada','Ninguno').
tipo('Graveler','Roca','Tierra').
tipo('Graveler-de-Alola','Roca','Electrico').
tipo('Greninja','Agua','Siniestro').
tipo('Grimer','Veneno','Ninguno').
tipo('Grimer-de-Alola','Veneno','Siniestro').
tipo('Grotle','Planta','Ninguno').
tipo('Groudon','Tierra','Ninguno').
tipo('Groudon-Primigenio','Tierra','Fuego').
tipo('Grovyle','Planta','Ninguno').
tipo('Growlithe','Fuego','Ninguno').
tipo('Grubbin','Bicho','Ninguno').
tipo('Grumpig','Psiquico','Ninguno').
tipo('Gulpin','Veneno','Ninguno').
tipo('Gumshoos','Normal','Ninguno').
tipo('Gurdurr','Lucha','Ninguno').
tipo('Guzzlord','Siniestro','Dragon').
tipo('Gyarados','Agua','Volador').
tipo('Hakamo-o','Dragon','Lucha').
tipo('Happiny','Normal','Ninguno').
tipo('Hariyama','Lucha','Ninguno').
tipo('Haunter','Fantasma','Veneno').
tipo('Hawlucha','Lucha','Volador').
tipo('Haxorus','Dragon','Ninguno').
tipo('Heatmor','Fuego','Ninguno').
tipo('Heatran','Fuego','Acero').
tipo('Heliolisk','Electrico','Normal').
tipo('Helioptile','Electrico','Normal').
tipo('Heracross','Bicho','Lucha').
tipo('Herdier','Normal','Ninguno').
tipo('Hippopotas','Tierra','Ninguno').
tipo('Hippowdon','Tierra','Ninguno').
tipo('Hitmonchan','Lucha','Ninguno').
tipo('Hitmonlee','Lucha','Ninguno').
tipo('Hitmontop','Lucha','Ninguno').
tipo('Ho-Oh','Fuego','Volador').
tipo('Honchkrow','Siniestro','Volador').
tipo('Honedge','Acero','Fantasma').
tipo('Hoopa','Psiquico','Fantasma').
tipo('Hoopa','Psiquico','Siniestro').
tipo('Hoothoot','Normal','Volador').
tipo('Hoppip','Planta','Volador').
tipo('Horsea','Agua','Ninguno').
tipo('Houndoom','Siniestro','Fuego').
tipo('Houndour','Siniestro','Fuego').
tipo('Huntail','Agua','Ninguno').
tipo('Hydreigon','Siniestro','Dragon').
tipo('Hypno','Psiquico','Ninguno').
tipo('Igglybuff','Normal','Hada').
tipo('Illumise','Bicho','Ninguno').
tipo('Incineroar','Fuego','Siniestro').
tipo('Infernape','Fuego','Lucha').
tipo('Inkay','Siniestro','Psiquico').
tipo('Ivysaur','Planta','Veneno').
tipo('Jangmo-o','Dragon','Ninguno').
tipo('Jellicent','Agua','Fantasma').
tipo('Jigglypuff','Normal','Hada').
tipo('Jirachi','Acero','Psiquico').
tipo('Jolteon','Electrico','Ninguno').
tipo('Joltik','Bicho','Electrico').
tipo('Jumpluff','Planta','Volador').
tipo('Jynx','Hielo','Psiquico').
tipo('Kabuto','Roca','Agua').
tipo('Kabutops','Roca','Agua').
tipo('Kadabra','Psiquico','Ninguno').
tipo('Kakuna','Bicho','Veneno').
tipo('Kangaskhan','Normal','Ninguno').
tipo('Karrablast','Bicho','Ninguno').
tipo('Kartana','Planta','Acero').
tipo('Kecleon','Normal','Ninguno').
tipo('Keldeo','Agua','Lucha').
tipo('Keldeo-Resolete','Agua','Lucha').
tipo('Kingdra','Agua','Dragon').
tipo('Kingler','Agua','Ninguno').
tipo('Kirlia','Psiquico','Hada').
tipo('Klang','Acero','Ninguno').
tipo('Klefki','Acero','Hada').
tipo('Klink','Acero','Ninguno').
tipo('Klinklang','Acero','Ninguno').
tipo('Koffing','Veneno','Ninguno').
tipo('Komala','Normal','Ninguno').
tipo('Kommo-o','Dragon','Lucha').
tipo('Krabby','Agua','Ninguno').
tipo('Kricketot','Bicho','Ninguno').
tipo('Kricketune','Bicho','Ninguno').
tipo('Krokorok','Tierra','Siniestro').
tipo('Krookodile','Tierra','Siniestro').
tipo('Kyogre','Agua','Ninguno').
tipo('Kyogre-Primigenio','Agua','Ninguno').
tipo('Kyurem','Dragon','Hielo').
tipo('Lairon','Acero','Roca').
tipo('Lampent','Fantasma','Fuego').
tipo('Landorus','Tierra','Volador').
tipo('Landorus-Therian','Tierra','Volador').
tipo('Lanturn','Agua','Electrico').
tipo('Lapras','Agua','Hielo').
tipo('Larvesta','Bicho','Fuego').
tipo('Larvitar','Roca','Tierra').
tipo('Latias','Dragon','Psiquico').
tipo('Latios','Dragon','Psiquico').
tipo('Leafeon','Planta','Ninguno').
tipo('Leavanny','Bicho','Planta').
tipo('Ledian','Bicho','Volador').
tipo('Ledyba','Bicho','Volador').
tipo('Lickilicky','Normal','Ninguno').
tipo('Lickitung','Normal','Ninguno').
tipo('Liepard','Siniestro','Ninguno').
tipo('Lileep','Roca','Planta').
tipo('Lilligant','Planta','Ninguno').
tipo('Lillipup','Normal','Ninguno').
tipo('Linoone','Normal','Ninguno').
tipo('Litleo','Fuego','Normal').
tipo('Litten','Fuego','Ninguno').
tipo('Litwick','Fantasma','Fuego').
tipo('Lombre','Agua','Planta').
tipo('Lopunny','Normal','Ninguno').
tipo('Lotad','Agua','Planta').
tipo('Loudred','Normal','Ninguno').
tipo('Lucario','Lucha','Acero').
tipo('Ludicolo','Agua','Planta').
tipo('Lugia','Psiquico','Volador').
tipo('Lumineon','Agua','Ninguno').
tipo('Lunala','Psiquico','Fantasma').
tipo('Lunatone','Roca','Psiquico').
tipo('Lurantis','Planta','Ninguno').
tipo('Luvdisc','Agua','Ninguno').
tipo('Luxio','Electrico','Ninguno').
tipo('Luxray','Electrico','Ninguno').
tipo('Lycanroc','Roca','Ninguno').
tipo('Machamp','Lucha','Ninguno').
tipo('Machoke','Lucha','Ninguno').
tipo('Machop','Lucha','Ninguno').
tipo('Magby','Fuego','Ninguno').
tipo('Magcargo','Fuego','Roca').
tipo('Magearna','Acero','Hada').
tipo('Magikarp','Agua','Ninguno').
tipo('Magmar','Fuego','Ninguno').
tipo('Magmortar','Fuego','Ninguno').
tipo('Magnemite','Electrico','Acero').
tipo('Magneton','Electrico','Acero').
tipo('Magnezone','Electrico','Acero').
tipo('Makuhita','Lucha','Ninguno').
tipo('Malamar','Siniestro','Psiquico').
tipo('Mamoswine','Hielo','Tierra').
tipo('Manaphy','Agua','Ninguno').
tipo('Mandibuzz','Siniestro','Volador').
tipo('Manectric','Electrico','Ninguno').
tipo('Mankey','Lucha','Ninguno').
tipo('Mantine','Agua','Volador').
tipo('Mantyke','Agua','Volador').
tipo('Maractus','Planta','Ninguno').
tipo('Mareanie','Veneno','Agua').
tipo('Mareep','Electrico','Ninguno').
tipo('Marill','Agua','Hada').
tipo('Marowak','Tierra','Ninguno').
tipo('Marowak-de-Alola','Fuego','Fantasma').
tipo('Marshadow','Lucha','Fantasma').
tipo('Marshtomp','Agua','Tierra').
tipo('Masquerain','Bicho','Volador').
tipo('Mawile','Acero','Hada').
tipo('Medicham','Lucha','Psiquico').
tipo('Meditite','Lucha','Psiquico').
tipo('Mega-Abomasnow','Planta','Hielo').
tipo('Mega-Absol','Siniestro','Ninguno').
tipo('Mega-Aerodactyl','Roca','Volador').
tipo('Mega-Aggron','Acero','Ninguno').
tipo('Mega-Alakazam','Psiquico','Ninguno').
tipo('Mega-Altaria','Dragon','Hada').
tipo('Mega-Ampharos','Electrico','Dragon').
tipo('Mega-Audino','Normal','Hada').
tipo('Mega-Banette','Fantasma','Ninguno').
tipo('Mega-Beedrill','Bicho','Veneno').
tipo('Mega-Blastoise','Agua','Ninguno').
tipo('Mega-Blaziken','Fuego','Lucha').
tipo('Mega-Camerupt','Fuego','Tierra').
tipo('Mega-Charizard-X','Fuego','Dragon').
tipo('Mega-Charizard-Y','Fuego','Volador').
tipo('Mega-Diancie','Roca','Hada').
tipo('Mega-Gallade','Psiquico','Lucha').
tipo('Mega-Garchomp','Dragon','Tierra').
tipo('Mega-Gardevoir','Psiquico','Hada').
tipo('Mega-Gengar','Fantasma','Veneno').
tipo('Mega-Glalie','Hielo','Ninguno').
tipo('Mega-Gyarados','Agua','Siniestro').
tipo('Mega-Heracross','Bicho','Lucha').
tipo('Mega-Houndoom','Siniestro','Fuego').
tipo('Mega-Kangaskhan','Normal','Ninguno').
tipo('Mega-Latias','Dragon','Psiquico').
tipo('Mega-Latios','Dragon','Psiquico').
tipo('Mega-Lopunny','Normal','Lucha').
tipo('Mega-Lucario','Lucha','Acero').
tipo('Mega-Manectric','Electrico','Ninguno').
tipo('Mega-Mawile','Acero','Hada').
tipo('Mega-Medicham','Lucha','Psiquico').
tipo('Mega-Metagross','Acero','Psiquico').
tipo('Mega-Mewtwo-X','Psiquico','Ninguno').
tipo('Mega-Mewtwo-Y','Psiquico','Ninguno').
tipo('Mega-Pidgeot','Normal','Volador').
tipo('Mega-Pinsir','Bicho','Volador').
tipo('Mega-Rayquaza','Dragon','Volador').
tipo('Mega-Sableye','Siniestro','Fantasma').
tipo('Mega-Salamence','Dragon','Volador').
tipo('Mega-Sceptile','Planta','Dragon').
tipo('Mega-Scizor','Bicho','Acero').
tipo('Mega-Sharpedo','Agua','Siniestro').
tipo('Mega-Slowbro','Agua','Psiquico').
tipo('Mega-Steelix','Acero','Tierra').
tipo('Mega-Swampert','Agua','Tierra').
tipo('Mega-Tyranitar','Roca','Siniestro').
tipo('Mega-Venusaur','Planta','Veneno').
tipo('Meganium','Planta','Ninguno').
tipo('Melmetal','Acero','Ninguno').
tipo('Meloetta','Normal','Psiquico').
tipo('Meloetta-Pirueta','Normal','Lucha').
tipo('Meltan','Acero','Ninguno').
tipo('Meowstic','Psiquico','Ninguno').
tipo('Meowth','Normal','Ninguno').
tipo('Meowth-de-Alola','Siniestro','Ninguno').
tipo('Mesprit','Psiquico','Ninguno').
tipo('Metagross','Acero','Psiquico').
tipo('Metang','Acero','Psiquico').
tipo('Metapod','Bicho','Ninguno').
tipo('Mew','Psiquico','Ninguno').
tipo('Mewtwo','Psiquico','Ninguno').
tipo('Mienfoo','Lucha','Ninguno').
tipo('Mienshao','Lucha','Ninguno').
tipo('Mightyena','Siniestro','Ninguno').
tipo('Milotic','Agua','Ninguno').
tipo('Miltank','Normal','Ninguno').
tipo('Mime-Jr.','Psiquico','Hada').
tipo('Mimikyu','Fantasma','Hada').
tipo('Minccino','Normal','Ninguno').
tipo('Minior','Roca','Volador').
tipo('Minun','Electrico','Ninguno').
tipo('Misdreavus','Fantasma','Ninguno').
tipo('Mismagius','Fantasma','Ninguno').
tipo('Moltres','Fuego','Volador').
tipo('Monferno','Fuego','Lucha').
tipo('Morelull','Planta','Hada').
tipo('Mothim','Bicho','Volador').
tipo('Mr.Mime','Psiquico','Hada').
tipo('Mudbray','Tierra','Ninguno').
tipo('Mudkip','Agua','Ninguno').
tipo('Mudsdale','Tierra','Ninguno').
tipo('Muk','Veneno','Ninguno').
tipo('Muk-de-Alola','Veneno','Siniestro').
tipo('Munchlax','Normal','Ninguno').
tipo('Munna','Psiquico','Ninguno').
tipo('Murkrow','Siniestro','Volador').
tipo('Musharna','Psiquico','Ninguno').
tipo('Naganadel','Veneno','Dragon').
tipo('Natu','Psiquico','Volador').
tipo('Necrozma','Psiquico','Ninguno').
tipo('Nidoking','Veneno','Tierra').
tipo('Nidoqueen','Veneno','Tierra').
tipo('Nidoran-F','Veneno','Ninguno').
tipo('Nidoran-M','Veneno','Ninguno').
tipo('Nidorina','Veneno','Ninguno').
tipo('Nidorino','Veneno','Ninguno').
tipo('Nihilego','Roca','Veneno').
tipo('Nincada','Bicho','Tierra').
tipo('Ninetales','Fuego','Ninguno').
tipo('Ninetales-de-Alola','Hielo','Hada').
tipo('Ninjask','Bicho','Volador').
tipo('Noctowl','Normal','Volador').
tipo('Noibat','Volador','Dragon').
tipo('Noivern','Volador','Dragon').
tipo('Nosepass','Roca','Ninguno').
tipo('Numel','Fuego','Tierra').
tipo('Nuzleaf','Planta','Siniestro').
tipo('Octillery','Agua','Ninguno').
tipo('Oddish','Planta','Veneno').
tipo('Omanyte','Roca','Agua').
tipo('Omastar','Roca','Agua').
tipo('Onix','Roca','Tierra').
tipo('Oranguru','Normal','Psiquico').
tipo('Oricorio-E','Electrico','Volador').
tipo('Oricorio-F','Fuego','Volador').
tipo('Oricorio-G','Fantasma','Volador').
tipo('Oricorio-P','Psiquico','Volador').
tipo('Oshawott','Agua','Ninguno').
tipo('Pachirisu','Electrico','Ninguno').
tipo('Palkia','Agua','Dragon').
tipo('Palossand','Fantasma','Tierra').
tipo('Palpitoad','Agua','Tierra').
tipo('Pancham','Lucha','Ninguno').
tipo('Pangoro','Lucha','Siniestro').
tipo('Panpour','Agua','Ninguno').
tipo('Pansage','Planta','Ninguno').
tipo('Pansear','Fuego','Ninguno').
tipo('Paras','Bicho','Planta').
tipo('Parasect','Bicho','Planta').
tipo('Passimian','Lucha','Ninguno').
tipo('Patrat','Normal','Ninguno').
tipo('Pawniard','Siniestro','Acero').
tipo('Pelipper','Agua','Volador').
tipo('Persian','Normal','Ninguno').
tipo('Persian-de-Alola','Siniestro','Ninguno').
tipo('Petilil','Planta','Ninguno').
tipo('Phanpy','Tierra','Ninguno').
tipo('Phantump','Fantasma','Planta').
tipo('Pheromosa','Bicho','Lucha').
tipo('Phione','Agua','Ninguno').
tipo('Pichu','Electrico','Ninguno').
tipo('Pidgeot','Normal','Volador').
tipo('Pidgeotto','Normal','Volador').
tipo('Pidgey','Normal','Volador').
tipo('Pidove','Normal','Volador').
tipo('Pignite','Fuego','Lucha').
tipo('Pikachu','Electrico','Ninguno').
tipo('Pikipek','Normal','Volador').
tipo('Piloswine','Hielo','Tierra').
tipo('Pineco','Bicho','Ninguno').
tipo('Pinsir','Bicho','Ninguno').
tipo('Piplup','Agua','Ninguno').
tipo('Plusle','Electrico','Ninguno').
tipo('Poipole','Veneno','Ninguno').
tipo('Politoed','Agua','Ninguno').
tipo('Poliwag','Agua','Ninguno').
tipo('Poliwhirl','Agua','Ninguno').
tipo('Poliwrath','Agua','Lucha').
tipo('Ponyta','Fuego','Ninguno').
tipo('Poochyena','Siniestro','Ninguno').
tipo('Popplio','Agua','Ninguno').
tipo('Porygon','Normal','Ninguno').
tipo('Porygon2','Normal','Ninguno').
tipo('PorygonZ','Normal','Ninguno').
tipo('Primarina','Agua','Hada').
tipo('Primeape','Lucha','Ninguno').
tipo('Prinplup','Agua','Ninguno').
tipo('Probopass','Roca','Acero').
tipo('Psyduck','Agua','Ninguno').
tipo('Pumpkaboo','Fantasma','Planta').
tipo('Pupitar','Roca','Tierra').
tipo('Purrloin','Siniestro','Ninguno').
tipo('Purugly','Normal','Ninguno').
tipo('Pyroar','Fuego','Normal').
tipo('Pyukumuku','Agua','Ninguno').
tipo('Quagsire','Agua','Tierra').
tipo('Quilava','Fuego','Ninguno').
tipo('Quilladin','Planta','Ninguno').
tipo('Qwilfish','Agua','Veneno').
tipo('Raichu','Electrico','Ninguno').
tipo('Raichu-de-Alola','Electrico','Psiquico').
tipo('Raikou','Electrico','Ninguno').
tipo('Ralts','Psiquico','Hada').
tipo('Rampardos','Roca','Ninguno').
tipo('Rapidash','Fuego','Ninguno').
tipo('Raticate','Normal','Ninguno').
tipo('Raticate-de-Alola','Siniestro','Normal').
tipo('Rattata','Normal','Ninguno').
tipo('Rattata-de-Alola','Siniestro','Normal').
tipo('Rayquaza','Dragon','Volador').
tipo('Regice','Hielo','Ninguno').
tipo('Regigigas','Normal','Ninguno').
tipo('Regirock','Roca','Ninguno').
tipo('Registeel','Acero','Ninguno').
tipo('Relicanth','Agua','Roca').
tipo('Remoraid','Agua','Ninguno').
tipo('Reshiram','Dragon','Fuego').
tipo('Reuniclus','Psiquico','Ninguno').
tipo('Rhydon','Tierra','Roca').
tipo('Rhyhorn','Tierra','Roca').
tipo('Rhyperior','Tierra','Roca').
tipo('Ribombee','Bicho','Hada').
tipo('Riolu','Lucha','Ninguno').
tipo('Rockruff','Roca','Ninguno').
tipo('Roggenrola','Roca','Ninguno').
tipo('Roselia','Planta','Veneno').
tipo('Roserade','Planta','Veneno').
tipo('Rotom','Electrico','Fantasma').
tipo('Rotom-Ventilador','Electrico','Volador').
tipo('Rotom-Frio','Electrico','Hielo').
tipo('Rotom-Calor','Electrico','Fuego').
tipo('Rotom-Corte','Electrico','Planta').
tipo('Rotom-Lavado','Electrico','Agua').
tipo('Rowlet','Planta','Volador').
tipo('Rufflet','Normal','Volador').
tipo('Sableye','Siniestro','Fantasma').
tipo('Salamence','Dragon','Volador').
tipo('Salandit','Veneno','Fuego').
tipo('Salazzle','Veneno','Fuego').
tipo('Samurott','Agua','Ninguno').
tipo('Sandile','Tierra','Siniestro').
tipo('Sandshrew','Tierra','Ninguno').
tipo('Sandshrew-de-Alola','Hielo','Acero').
tipo('Sandslash','Tierra','Ninguno').
tipo('Sandslash-de-Alola','Hielo','Acero').
tipo('Sandygast','Fantasma','Tierra').
tipo('Sawk','Lucha','Ninguno').
tipo('Sawsbuck','Normal','Planta').
tipo('Scatterbug','Bicho','Ninguno').
tipo('Sceptile','Planta','Ninguno').
tipo('Scizor','Bicho','Acero').
tipo('Scolipede','Bicho','Veneno').
tipo('Scrafty','Siniestro','Lucha').
tipo('Scraggy','Siniestro','Lucha').
tipo('Scyther','Bicho','Volador').
tipo('Seadra','Agua','Ninguno').
tipo('Seaking','Agua','Ninguno').
tipo('Sealeo','Hielo','Agua').
tipo('Seedot','Planta','Ninguno').
tipo('Seel','Agua','Ninguno').
tipo('Seismitoad','Agua','Tierra').
tipo('Sentret','Normal','Ninguno').
tipo('Serperior','Planta','Ninguno').
tipo('Servine','Planta','Ninguno').
tipo('Seviper','Veneno','Ninguno').
tipo('Sewaddle','Bicho','Planta').
tipo('Sharpedo','Agua','Siniestro').
tipo('Shaymin','Planta','Ninguno').
tipo('Shaymin-Sky','Planta','Volador').
tipo('Shedinja','Bicho','Fantasma').
tipo('Shelgon','Dragon','Ninguno').
tipo('Shellder','Agua','Ninguno').
tipo('Shellos','Agua','Ninguno').
tipo('Shelmet','Bicho','Ninguno').
tipo('Shieldon','Roca','Acero').
tipo('Shiftry','Planta','Siniestro').
tipo('Shiinotic','Planta','Hada').
tipo('Shinx','Electrico','Ninguno').
tipo('Shroomish','Planta','Ninguno').
tipo('Shuckle','Bicho','Roca').
tipo('Shuppet','Fantasma','Ninguno').
tipo('Sigilyph','Psiquico','Volador').
tipo('Silcoon','Bicho','Ninguno').
tipo('Silvally','Normal','Ninguno').
tipo('Simipour','Agua','Ninguno').
tipo('Simisage','Planta','Ninguno').
tipo('Simisear','Fuego','Ninguno').
tipo('Skarmory','Acero','Volador').
tipo('Skiddo','Planta','Ninguno').
tipo('Skiploom','Planta','Volador').
tipo('Skitty','Normal','Ninguno').
tipo('Skorupi','Veneno','Bicho').
tipo('Skrelp','Veneno','Agua').
tipo('Skuntank','Veneno','Siniestro').
tipo('Slaking','Normal','Ninguno').
tipo('Slakoth','Normal','Ninguno').
tipo('Sliggoo','Dragon','Ninguno').
tipo('Slowbro','Agua','Psiquico').
tipo('Slowking','Agua','Psiquico').
tipo('Slowpoke','Agua','Psiquico').
tipo('Slugma','Fuego','Ninguno').
tipo('Slurpuff','Hada','Ninguno').
tipo('Smeargle','Normal','Ninguno').
tipo('Smoochum','Hielo','Psiquico').
tipo('Sneasel','Siniestro','Hielo').
tipo('Snivy','Planta','Ninguno').
tipo('Snorlax','Normal','Ninguno').
tipo('Snorunt','Hielo','Ninguno').
tipo('Snover','Planta','Hielo').
tipo('Snubbull','Hada','Ninguno').
tipo('Solgaleo','Psiquico','Acero').
tipo('Solosis','Psiquico','Ninguno').
tipo('Solrock','Roca','Psiquico').
tipo('Spearow','Normal','Volador').
tipo('Spewpa','Bicho','Ninguno').
tipo('Spheal','Hielo','Agua').
tipo('Spinarak','Bicho','Veneno').
tipo('Spinda','Normal','Ninguno').
tipo('Spiritomb','Fantasma','Siniestro').
tipo('Spoink','Psiquico','Ninguno').
tipo('Spritzee','Hada','Ninguno').
tipo('Squirtle','Agua','Ninguno').
tipo('Stakataka','Roca','Acero').
tipo('Stantler','Normal','Ninguno').
tipo('Staraptor','Normal','Volador').
tipo('Staravia','Normal','Volador').
tipo('Starly','Normal','Volador').
tipo('Starmie','Agua','Psiquico').
tipo('Staryu','Agua','Ninguno').
tipo('Steelix','Acero','Tierra').
tipo('Steenee','Planta','Ninguno').
tipo('Stoutland','Normal','Ninguno').
tipo('Stufful','Normal','Lucha').
tipo('Stunfisk','Tierra','Electrico').
tipo('Stunky','Veneno','Siniestro').
tipo('Sudowoodo','Roca','Ninguno').
tipo('Suicune','Agua','Ninguno').
tipo('Sunflora','Planta','Ninguno').
tipo('Sunkern','Planta','Ninguno').
tipo('Surskit','Bicho','Agua').
tipo('Swablu','Normal','Volador').
tipo('Swadloon','Bicho','Planta').
tipo('Swalot','Veneno','Ninguno').
tipo('Swampert','Agua','Tierra').
tipo('Swanna','Agua','Volador').
tipo('Swellow','Normal','Volador').
tipo('Swinub','Hielo','Tierra').
tipo('Swirlix','Hada','Ninguno').
tipo('Swoobat','Psiquico','Volador').
tipo('Sylveon','Hada','Ninguno').
tipo('Taillow','Normal','Volador').
tipo('Talonflame','Fuego','Volador').
tipo('Tangela','Planta','Ninguno').
tipo('Tangrowth','Planta','Ninguno').
tipo('Tapu-Bulu','Planta','Hada').
tipo('Tapu-Fini','Agua','Hada').
tipo('Tapu-Koko','Electrico','Hada').
tipo('Tapu-Lele','Psiquico','Hada').
tipo('Tauros','Normal','Ninguno').
tipo('Teddiursa','Normal','Ninguno').
tipo('Tentacool','Agua','Veneno').
tipo('Tentacruel','Agua','Veneno').
tipo('Tepig','Fuego','Ninguno').
tipo('Terrakion','Roca','Lucha').
tipo('Throh','Lucha','Ninguno').
tipo('Thundurus','Electrico','Volador').
tipo('Thundurus-Therian','Electrico','Volador').
tipo('Timburr','Lucha','Ninguno').
tipo('Tirtouga','Agua','Roca').
tipo('Togedemaru','Electrico','Acero').
tipo('Togekiss','Hada','Volador').
tipo('Togepi','Hada','Ninguno').
tipo('Togetic','Hada','Volador').
tipo('Torchic','Fuego','Ninguno').
tipo('Torkoal','Fuego','Ninguno').
tipo('Tornadus','Volador','Ninguno').
tipo('Tornadus-Therian','Volador','Ninguno').
tipo('Torracat','Fuego','Ninguno').
tipo('Torterra','Planta','Tierra').
tipo('Totodile','Agua','Ninguno').
tipo('Toucannon','Normal','Volador').
tipo('Toxapex','Veneno','Agua').
tipo('Toxicroak','Veneno','Lucha').
tipo('Tranquill','Normal','Volador').
tipo('Trapinch','Tierra','Ninguno').
tipo('Treecko','Planta','Ninguno').
tipo('Trevenant','Fantasma','Planta').
tipo('Tropius','Planta','Volador').
tipo('Trubbish','Veneno','Ninguno').
tipo('Trumbeak','Normal','Volador').
tipo('Tsareena','Planta','Ninguno').
tipo('Turtonator','Fuego','Dragon').
tipo('Turtwig','Planta','Ninguno').
tipo('Tympole','Agua','Ninguno').
tipo('Tynamo','Electrico','Ninguno').
tipo('Type:Null','Normal','Ninguno').
tipo('Typhlosion','Fuego','Ninguno').
tipo('Tyranitar','Roca','Siniestro').
tipo('Tyrantrum','Roca','Dragon').
tipo('Tyrogue','Lucha','Ninguno').
tipo('Tyrunt','Roca','Dragon').
tipo('Umbreon','Siniestro','Ninguno').
tipo('Unfezant','Normal','Volador').
tipo('Unown','Psiquico','Ninguno').
tipo('Ursaring','Normal','Ninguno').
tipo('Uxie','Psiquico','Ninguno').
tipo('Vanillish','Hielo','Ninguno').
tipo('Vanillite','Hielo','Ninguno').
tipo('Vanilluxe','Hielo','Ninguno').
tipo('Vaporeon','Agua','Ninguno').
tipo('Venipede','Bicho','Veneno').
tipo('Venomoth','Bicho','Veneno').
tipo('Venonat','Bicho','Veneno').
tipo('Venusaur','Planta','Veneno').
tipo('Vespiquen','Bicho','Volador').
tipo('Vibrava','Tierra','Dragon').
tipo('Victini','Psiquico','Fuego').
tipo('Victreebel','Planta','Veneno').
tipo('Vigoroth','Normal','Ninguno').
tipo('Vikavolt','Bicho','Electrico').
tipo('Vileplume','Planta','Veneno').
tipo('Virizion','Planta','Lucha').
tipo('Vivillon','Bicho','Volador').
tipo('Volbeat','Bicho','Ninguno').
tipo('Volcanion','Fuego','Agua').
tipo('Volcarona','Bicho','Fuego').
tipo('Voltorb','Electrico','Ninguno').
tipo('Vullaby','Siniestro','Volador').
tipo('Vulpix','Fuego','Ninguno').
tipo('Vulpix-de-Alola','Hielo','Ninguno').
tipo('Wailmer','Agua','Ninguno').
tipo('Wailord','Agua','Ninguno').
tipo('Walrein','Hielo','Agua').
tipo('Wartortle','Agua','Ninguno').
tipo('Watchog','Normal','Ninguno').
tipo('Weavile','Siniestro','Hielo').
tipo('Weedle','Bicho','Veneno').
tipo('Weepinbell','Planta','Veneno').
tipo('Weezing','Veneno','Ninguno').
tipo('Whimsicott','Planta','Hada').
tipo('Whirlipede','Bicho','Veneno').
tipo('Whiscash','Agua','Tierra').
tipo('Whismur','Normal','Ninguno').
tipo('Wigglytuff','Normal','Hada').
tipo('Wimpod','Bicho','Agua').
tipo('Wingull','Agua','Volador').
tipo('Wishiwashi','Agua','Ninguno').
tipo('Wobbuffet','Psiquico','Ninguno').
tipo('Woobat','Psiquico','Volador').
tipo('Wooper','Agua','Tierra').
tipo('Wormadam-Tronco-Arena','Bicho','Tierra').
tipo('Wormadam-Tronco-Basura','Bicho','Acero').
tipo('Wormadam-Tronco-Planta','Bicho','Planta').
tipo('Wurmple','Bicho','Ninguno').
tipo('Wynaut','Psiquico','Ninguno').
tipo('Xatu','Psiquico','Volador').
tipo('Xerneas','Hada','Ninguno').
tipo('Xurkitree','Electrico','Ninguno').
tipo('Yamask','Fantasma','Ninguno').
tipo('Yanma','Bicho','Volador').
tipo('Yanmega','Bicho','Volador').
tipo('Yungoos','Normal','Ninguno').
tipo('Yveltal','Siniestro','Volador').
tipo('Zangoose','Normal','Ninguno').
tipo('Zapdos','Electrico','Volador').
tipo('Zebstrika','Electrico','Ninguno').
tipo('Zekrom','Dragon','Electrico').
tipo('Zeraora','Electrico','Ninguno').
tipo('Zigzagoon','Normal','Ninguno').
tipo('Zoroark','Siniestro','Ninguno').
tipo('Zorua','Siniestro','Ninguno').
tipo('Zubat','Veneno','Volador').
tipo('Zweilous','Siniestro','Dragon').
tipo('Zygarde','Dragon','Tierra').

tipo('Missingno','Ninguno','Ninguno').