%Megas
mega('Mega-Abomasnow','Abomasnow').
mega('Mega-Absol','Absol').
mega('Mega-Aerodactyl','Aerodactyl').
mega('Mega-Aggron','Aggron').
mega('Mega-Alakazam','Alakazam').
mega('Mega-Altaria','Altaria').
mega('Mega-Ampharos','Ampharos').
mega('Mega-Audino','Audino').
mega('Mega-Banette','Banette').
mega('Mega-Beedrill','Beedrill').
mega('Mega-Blastoise','Blastoise').
mega('Mega-Blaziken','Blaziken').
mega('Mega-Camerupt','Camerupt').
mega('Mega-Charizard-X','Charizard').
mega('Mega-Charizard-Y','Charizard').
mega('Mega-Diancie','Diancie').
mega('Mega-Gallade','Gallade').
mega('Mega-Garchomp','Garchomp').
mega('Mega-Gardevoir','Gardevoir').
mega('Mega-Gengar','Gengar').
mega('Mega-Glalie','Glalie').
mega('Mega-Gyarados','Gyarados').
mega('Mega-Heracross','Heracross').
mega('Mega-Houndoom','Houndoom').
mega('Mega-Kangaskhan','Kangaskhan').
mega('Mega-Latias','Latias').
mega('Mega-Latios','Latios').
mega('Mega-Lopunny','Lopunny').
mega('Mega-Lucario','Lucario').
mega('Mega-Manectric','Manectric').
mega('Mega-Mawile','Mawile').
mega('Mega-Medicham','Medicham').
mega('Mega-Metagross','Metagross').
mega('Mega-Mewtwo-X','Mewtwo').
mega('Mega-Mewtwo-Y','Mewtwo').
mega('Mega-Pidgeot','Pidgeot').
mega('Mega-Pinsir','Pinsir').
mega('Mega-Rayquaza','Rayquaza').
mega('Mega-Sableye','Sableye').
mega('Mega-Salamence','Salamence').
mega('Mega-Sceptile','Sceptile').
mega('Mega-Scizor','Scizor').
mega('Mega-Sharpedo','Sharpedo').
mega('Mega-Slowbro','Slowbro').
mega('Mega-Steelix','Steelix').
mega('Mega-Swampert','Swampert').
mega('Mega-Tyranitar','Tyranitar').
mega('Mega-Venusaur','Venusaur').

%Primigenio
primigenio('Groudon-Primigenio','Groudon').
primigenio('Kyogre-Primigenio','Kyogre').

%Alternas
pirueta('Meloetta-Pirueta','Meloetta').
resolete('Keldeo-Resolete','Keldeo').
therian('Tornadus-Therian','Tornadus').
therian('Thundurus-Therian','Thundurus').
therian('Landorus-Therian','Landorus').

%Alola
alola('Marowak-de-Alola','Marowak').
alola('Exeggutor-de-Alola','Exeggutor').
alola('Raichu-de-Alola','Raichu').
alola('Grimer-de-Alola','Grimer').
alola('Muk-de-Alola','Muk').
alola('Rattata-de-Alola','Rattata').
alola('Raticate-de-Alola','Raticate').
alola('Sandshrew-de-Alola','Sandshrew').
alola('Sandslash-de-Alola','Sandslash').
alola('Vulpix-de-Alola','Vulpix').
alola('Ninetales-de-Alola','Ninetales').
alola('Diglett-de-Alola','Diglett').
alola('Dugtrio-de-Alola','Dugtrio').
alola('Meowth-de-Alola','Meowth').
alola('Persian-de-Alola','Persian').
alola('Geodude-de-Alola','Geodude').
alola('Graveler-de-Alola','Graveler').
alola('Golem-de-Alola','Golem').

rotom('Rotom-Calor','Rotom').
rotom('Rotom-Frio','Rotom').
rotom('Rotom-Ventilador','Rotom').
rotom('Rotom-Corte','Rotom').
rotom('Rotom-Lavado','Rotom').